// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"database/sql"
	"database/sql/driver"
	"encoding/json"
	"fmt"
	"time"
)

type EstimatesStatus string

const (
	EstimatesStatusOk       EstimatesStatus = "ok"
	EstimatesStatusFailed   EstimatesStatus = "failed"
	EstimatesStatusNoResult EstimatesStatus = "no_result"
)

func (e *EstimatesStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = EstimatesStatus(s)
	case string:
		*e = EstimatesStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for EstimatesStatus: %T", src)
	}
	return nil
}

type NullEstimatesStatus struct {
	EstimatesStatus EstimatesStatus
	Valid           bool // Valid is true if EstimatesStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullEstimatesStatus) Scan(value interface{}) error {
	if value == nil {
		ns.EstimatesStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.EstimatesStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullEstimatesStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.EstimatesStatus), nil
}

type OfficialStatusLastResult string

const (
	OfficialStatusLastResultAvailable OfficialStatusLastResult = "available"
	OfficialStatusLastResultPreorder  OfficialStatusLastResult = "preorder"
	OfficialStatusLastResultSoldout   OfficialStatusLastResult = "soldout"
	OfficialStatusLastResultEnded     OfficialStatusLastResult = "ended"
	OfficialStatusLastResultUnknown   OfficialStatusLastResult = "unknown"
	OfficialStatusLastResultAmbiguous OfficialStatusLastResult = "ambiguous"
	OfficialStatusLastResultBlocked   OfficialStatusLastResult = "blocked"
	OfficialStatusLastResultFailed    OfficialStatusLastResult = "failed"
)

func (e *OfficialStatusLastResult) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OfficialStatusLastResult(s)
	case string:
		*e = OfficialStatusLastResult(s)
	default:
		return fmt.Errorf("unsupported scan type for OfficialStatusLastResult: %T", src)
	}
	return nil
}

type NullOfficialStatusLastResult struct {
	OfficialStatusLastResult OfficialStatusLastResult
	Valid                    bool // Valid is true if OfficialStatusLastResult is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOfficialStatusLastResult) Scan(value interface{}) error {
	if value == nil {
		ns.OfficialStatusLastResult, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OfficialStatusLastResult.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOfficialStatusLastResult) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OfficialStatusLastResult), nil
}

type OfficialStatusPreviousStatus string

const (
	OfficialStatusPreviousStatusAvailable OfficialStatusPreviousStatus = "available"
	OfficialStatusPreviousStatusPreorder  OfficialStatusPreviousStatus = "preorder"
	OfficialStatusPreviousStatusSoldout   OfficialStatusPreviousStatus = "soldout"
	OfficialStatusPreviousStatusEnded     OfficialStatusPreviousStatus = "ended"
	OfficialStatusPreviousStatusUnknown   OfficialStatusPreviousStatus = "unknown"
	OfficialStatusPreviousStatusAmbiguous OfficialStatusPreviousStatus = "ambiguous"
	OfficialStatusPreviousStatusBlocked   OfficialStatusPreviousStatus = "blocked"
	OfficialStatusPreviousStatusFailed    OfficialStatusPreviousStatus = "failed"
)

func (e *OfficialStatusPreviousStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OfficialStatusPreviousStatus(s)
	case string:
		*e = OfficialStatusPreviousStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for OfficialStatusPreviousStatus: %T", src)
	}
	return nil
}

type NullOfficialStatusPreviousStatus struct {
	OfficialStatusPreviousStatus OfficialStatusPreviousStatus
	Valid                        bool // Valid is true if OfficialStatusPreviousStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOfficialStatusPreviousStatus) Scan(value interface{}) error {
	if value == nil {
		ns.OfficialStatusPreviousStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OfficialStatusPreviousStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOfficialStatusPreviousStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OfficialStatusPreviousStatus), nil
}

type OfficialStatusStatus string

const (
	OfficialStatusStatusAvailable OfficialStatusStatus = "available"
	OfficialStatusStatusPreorder  OfficialStatusStatus = "preorder"
	OfficialStatusStatusSoldout   OfficialStatusStatus = "soldout"
	OfficialStatusStatusEnded     OfficialStatusStatus = "ended"
	OfficialStatusStatusUnknown   OfficialStatusStatus = "unknown"
	OfficialStatusStatusAmbiguous OfficialStatusStatus = "ambiguous"
	OfficialStatusStatusBlocked   OfficialStatusStatus = "blocked"
	OfficialStatusStatusFailed    OfficialStatusStatus = "failed"
)

func (e *OfficialStatusStatus) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = OfficialStatusStatus(s)
	case string:
		*e = OfficialStatusStatus(s)
	default:
		return fmt.Errorf("unsupported scan type for OfficialStatusStatus: %T", src)
	}
	return nil
}

type NullOfficialStatusStatus struct {
	OfficialStatusStatus OfficialStatusStatus
	Valid                bool // Valid is true if OfficialStatusStatus is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullOfficialStatusStatus) Scan(value interface{}) error {
	if value == nil {
		ns.OfficialStatusStatus, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.OfficialStatusStatus.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullOfficialStatusStatus) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.OfficialStatusStatus), nil
}

type SitesFetchType string

const (
	SitesFetchTypeApi      SitesFetchType = "api"
	SitesFetchTypeScrape   SitesFetchType = "scrape"
	SitesFetchTypeHeadless SitesFetchType = "headless"
	SitesFetchTypeLinkOnly SitesFetchType = "link_only"
)

func (e *SitesFetchType) Scan(src interface{}) error {
	switch s := src.(type) {
	case []byte:
		*e = SitesFetchType(s)
	case string:
		*e = SitesFetchType(s)
	default:
		return fmt.Errorf("unsupported scan type for SitesFetchType: %T", src)
	}
	return nil
}

type NullSitesFetchType struct {
	SitesFetchType SitesFetchType
	Valid          bool // Valid is true if SitesFetchType is not NULL
}

// Scan implements the Scanner interface.
func (ns *NullSitesFetchType) Scan(value interface{}) error {
	if value == nil {
		ns.SitesFetchType, ns.Valid = "", false
		return nil
	}
	ns.Valid = true
	return ns.SitesFetchType.Scan(value)
}

// Value implements the driver Valuer interface.
func (ns NullSitesFetchType) Value() (driver.Value, error) {
	if !ns.Valid {
		return nil, nil
	}
	return string(ns.SitesFetchType), nil
}

type Estimate struct {
	ItemID          int64
	SiteID          int64
	Low             sql.NullInt32
	Mid             sql.NullInt32
	Count           int32
	SuspiciousCount int32
	Status          EstimatesStatus
	FetchedAt       time.Time
	InStockCount    int32
}

type Genre struct {
	ID            int64
	Name          string
	QueryTemplate string
	SortOrder     int32
}

type GenreAlias struct {
	ID         int64
	GenreID    int64
	GroupNo    int32
	Alias      string
	Normalized string
}

type GenreSite struct {
	GenreID   int64
	SiteID    int64
	SortOrder int32
}

type Item struct {
	ID            int64
	GenreID       int64
	Name          string
	OptionText    sql.NullString
	QueryOverride sql.NullString
	ImagePath     string
	SourceUrl     sql.NullString
	MinPrice      sql.NullInt32
	SortOrder     int32
	CreatedAt     time.Time
	UpdatedAt     time.Time
	WatchOfficial bool
}

type ItemSiteOverride struct {
	ItemID  int64
	SiteID  int64
	Query   sql.NullString
	Enabled bool
}

type Listing struct {
	ID                int64
	ItemID            int64
	SiteID            int64
	Title             string
	Price             int32
	Url               string
	ImageUrl          sql.NullString
	InStock           bool
	SuspiciousReasons json.RawMessage
	FetchedAt         time.Time
}

type OfficialStatus struct {
	ItemID         int64
	Status         OfficialStatusStatus
	Evidence       json.RawMessage
	CheckedAt      time.Time
	ChangedAt      sql.NullTime
	PreviousStatus NullOfficialStatusPreviousStatus
	LastResult     OfficialStatusLastResult
	LastAttemptAt  time.Time
}

type PriceHistory struct {
	ItemID     int64
	SiteID     int64
	Day        time.Time
	Low        int32
	Mid        sql.NullInt32
	Count      int32
	RecordedAt time.Time
}

type Site struct {
	ID                int64
	Name              string
	SearchUrlTemplate string
	FetchType         SitesFetchType
	IsReference       bool
}
