apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pokecalc
resources:
  - ../../base
images:
  - name: pokecalc/judge
    newName: localhost:5000/pokecalc/judge
    digest: sha256:6c6e82aaf9b00ed9560fb0bea1c9e98815e9068b2cc4487320f182d138813fcc
