// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
)

// Defines values for DefenderPreset.
const (
	DefenderPresetHb      DefenderPreset = "hb"
	DefenderPresetHbBoost DefenderPreset = "hb_boost"
	DefenderPresetHbFull  DefenderPreset = "hb_full"
	DefenderPresetHd      DefenderPreset = "hd"
	DefenderPresetHdBoost DefenderPreset = "hd_boost"
	DefenderPresetHdFull  DefenderPreset = "hd_full"
	DefenderPresetHp      DefenderPreset = "hp"
	DefenderPresetNone    DefenderPreset = "none"
)

// Valid indicates whether the value is a known member of the DefenderPreset enum.
func (e DefenderPreset) Valid() bool {
	switch e {
	case DefenderPresetHb:
		return true
	case DefenderPresetHbBoost:
		return true
	case DefenderPresetHbFull:
		return true
	case DefenderPresetHd:
		return true
	case DefenderPresetHdBoost:
		return true
	case DefenderPresetHdFull:
		return true
	case DefenderPresetHp:
		return true
	case DefenderPresetNone:
		return true
	default:
		return false
	}
}

// Defines values for Format.
const (
	Double Format = "double"
	Single Format = "single"
)

// Valid indicates whether the value is a known member of the Format enum.
func (e Format) Valid() bool {
	switch e {
	case Double:
		return true
	case Single:
		return true
	default:
		return false
	}
}

// Defines values for MoveCategory.
const (
	Physical MoveCategory = "physical"
	Special  MoveCategory = "special"
	Status   MoveCategory = "status"
)

// Valid indicates whether the value is a known member of the MoveCategory enum.
func (e MoveCategory) Valid() bool {
	switch e {
	case Physical:
		return true
	case Special:
		return true
	case Status:
		return true
	default:
		return false
	}
}

// Defines values for PokeType.
const (
	PokeTypeBug      PokeType = "bug"
	PokeTypeDark     PokeType = "dark"
	PokeTypeDragon   PokeType = "dragon"
	PokeTypeElectric PokeType = "electric"
	PokeTypeFairy    PokeType = "fairy"
	PokeTypeFighting PokeType = "fighting"
	PokeTypeFire     PokeType = "fire"
	PokeTypeFlying   PokeType = "flying"
	PokeTypeGhost    PokeType = "ghost"
	PokeTypeGrass    PokeType = "grass"
	PokeTypeGround   PokeType = "ground"
	PokeTypeIce      PokeType = "ice"
	PokeTypeNormal   PokeType = "normal"
	PokeTypePoison   PokeType = "poison"
	PokeTypePsychic  PokeType = "psychic"
	PokeTypeRock     PokeType = "rock"
	PokeTypeSteel    PokeType = "steel"
	PokeTypeWater    PokeType = "water"
)

// Valid indicates whether the value is a known member of the PokeType enum.
func (e PokeType) Valid() bool {
	switch e {
	case PokeTypeBug:
		return true
	case PokeTypeDark:
		return true
	case PokeTypeDragon:
		return true
	case PokeTypeElectric:
		return true
	case PokeTypeFairy:
		return true
	case PokeTypeFighting:
		return true
	case PokeTypeFire:
		return true
	case PokeTypeFlying:
		return true
	case PokeTypeGhost:
		return true
	case PokeTypeGrass:
		return true
	case PokeTypeGround:
		return true
	case PokeTypeIce:
		return true
	case PokeTypeNormal:
		return true
	case PokeTypePoison:
		return true
	case PokeTypePsychic:
		return true
	case PokeTypeRock:
		return true
	case PokeTypeSteel:
		return true
	case PokeTypeWater:
		return true
	default:
		return false
	}
}

// Defines values for ReverseSide.
const (
	Attacker ReverseSide = "attacker"
	Defender ReverseSide = "defender"
)

// Valid indicates whether the value is a known member of the ReverseSide enum.
func (e ReverseSide) Valid() bool {
	switch e {
	case Attacker:
		return true
	case Defender:
		return true
	default:
		return false
	}
}

// Defines values for StatKey.
const (
	StatKeyAtk StatKey = "atk"
	StatKeyDef StatKey = "def"
	StatKeyHp  StatKey = "hp"
	StatKeySpa StatKey = "spa"
	StatKeySpd StatKey = "spd"
	StatKeySpe StatKey = "spe"
)

// Valid indicates whether the value is a known member of the StatKey enum.
func (e StatKey) Valid() bool {
	switch e {
	case StatKeyAtk:
		return true
	case StatKeyDef:
		return true
	case StatKeyHp:
		return true
	case StatKeySpa:
		return true
	case StatKeySpd:
		return true
	case StatKeySpe:
		return true
	default:
		return false
	}
}

// Defines values for StatusCondition.
const (
	StatusConditionBadlyPoison StatusCondition = "badly_poison"
	StatusConditionBurn        StatusCondition = "burn"
	StatusConditionFreeze      StatusCondition = "freeze"
	StatusConditionNone        StatusCondition = "none"
	StatusConditionParalysis   StatusCondition = "paralysis"
	StatusConditionPoison      StatusCondition = "poison"
	StatusConditionSleep       StatusCondition = "sleep"
)

// Valid indicates whether the value is a known member of the StatusCondition enum.
func (e StatusCondition) Valid() bool {
	switch e {
	case StatusConditionBadlyPoison:
		return true
	case StatusConditionBurn:
		return true
	case StatusConditionFreeze:
		return true
	case StatusConditionNone:
		return true
	case StatusConditionParalysis:
		return true
	case StatusConditionPoison:
		return true
	case StatusConditionSleep:
		return true
	default:
		return false
	}
}

// Defines values for Terrain.
const (
	TerrainElectric Terrain = "electric"
	TerrainGrassy   Terrain = "grassy"
	TerrainMisty    Terrain = "misty"
	TerrainNone     Terrain = "none"
	TerrainPsychic  Terrain = "psychic"
)

// Valid indicates whether the value is a known member of the Terrain enum.
func (e Terrain) Valid() bool {
	switch e {
	case TerrainElectric:
		return true
	case TerrainGrassy:
		return true
	case TerrainMisty:
		return true
	case TerrainNone:
		return true
	case TerrainPsychic:
		return true
	default:
		return false
	}
}

// Defines values for Weather.
const (
	WeatherNone Weather = "none"
	WeatherRain Weather = "rain"
	WeatherSand Weather = "sand"
	WeatherSnow Weather = "snow"
	WeatherSun  Weather = "sun"
)

// Valid indicates whether the value is a known member of the Weather enum.
func (e Weather) Valid() bool {
	switch e {
	case WeatherNone:
		return true
	case WeatherRain:
		return true
	case WeatherSand:
		return true
	case WeatherSnow:
		return true
	case WeatherSun:
		return true
	default:
		return false
	}
}

// Ability defines model for Ability.
type Ability struct {
	Id     string `json:"id"`
	NameJa string `json:"nameJa"`
}

// BulkCalcRequest defines model for BulkCalcRequest.
type BulkCalcRequest struct {
	// Attacker 計算に使う個体。SP と性格 ID から実数値を導出する
	Attacker Individual `json:"attacker"`

	// DefenderSpeciesKey {図鑑番号4桁}-{フォルム3桁}
	//
	// Example: 0445-000
	DefenderSpeciesKey SpeciesKey  `json:"defenderSpeciesKey"`
	Field              *FieldState `json:"field,omitempty"`
	Format             Format      `json:"format"`

	// ItemVariants 差し替えて比較する持ち物 ID(省略時は素の1通り)
	ItemVariants *[]*string   `json:"itemVariants,omitempty"`
	MoveId       string       `json:"moveId"`
	Options      *CalcOptions `json:"options,omitempty"`

	// Presets 省略時(空配列を含む)は技の分類に応じた既定セット。
	// 物理技は 5 件(none, hp, hb_boost, hb, hb_full)、
	// 特殊技は 5 件(none, hp, hd_boost, hd, hd_full)、
	// 変化技は 2 件(none, hp)。指定したときはその順に行を返す。
	Presets *[]DefenderPreset `json:"presets,omitempty"`
}

// BulkCalcResult defines model for BulkCalcResult.
type BulkCalcResult struct {
	// DefenderSpeciesKey {図鑑番号4桁}-{フォルム3桁}
	//
	// Example: 0445-000
	DefenderSpeciesKey SpeciesKey    `json:"defenderSpeciesKey"`
	Rows               []BulkCalcRow `json:"rows"`
}

// BulkCalcRow defines model for BulkCalcRow.
type BulkCalcRow struct {
	ItemId *string `json:"itemId,omitempty"`

	// Preset 防御側の代表調整(耐久が上がる順)。SP は能力ポイント(Lv50・個体値31固定)。
	// 性格の「無補正」は上昇・下降なし、「+B/-A」は防御上昇・攻撃下降のこと。
	// engine の PresetKey と同一文字列(docs/adr/0009-bulk-calc-presets.md §1)。
	// - `none`: 無振り(SP なし・無補正)。全分類
	// - `hp`: H振り(HP 32・無補正)。全分類
	// - `hb_boost`: H振り+B補正(HP 32・防御上昇 +B/-A)。物理
	// - `hb`: HB振り(HP 32・防御 32・無補正)。物理
	// - `hb_full`: HB特化(HP 32・防御 32・防御上昇 +B/-A)。物理
	// - `hd_boost`: H振り+D補正(HP 32・特防上昇 +D/-A)。特殊
	// - `hd`: HD振り(HP 32・特防 32・無補正)。特殊
	// - `hd_full`: HD特化(HP 32・特防 32・特防上昇 +D/-A)。特殊
	Preset DefenderPreset `json:"preset"`

	// PresetLabel 表示名(例 HB振り / HB特化 / H振り+B補正)
	PresetLabel string     `json:"presetLabel"`
	Result      CalcResult `json:"result"`
}

// CalcOptions defines model for CalcOptions.
type CalcOptions struct {
	// Critical 急所
	Critical *bool `json:"critical,omitempty"`
}

// CalcRequest defines model for CalcRequest.
type CalcRequest struct {
	// Attacker 計算に使う個体。SP と性格 ID から実数値を導出する
	Attacker Individual `json:"attacker"`

	// Defender 計算に使う個体。SP と性格 ID から実数値を導出する
	Defender Individual  `json:"defender"`
	Field    *FieldState `json:"field,omitempty"`
	Format   Format      `json:"format"`

	// MoveId 使用する技(attacker.moveId より優先)
	MoveId  string       `json:"moveId"`
	Options *CalcOptions `json:"options,omitempty"`
}

// CalcResult defines model for CalcResult.
type CalcResult struct {
	DefenderHP int `json:"defenderHP"`

	// Effectiveness タイプ相性(0, 0.25, 0.5, 1, 2, 4)
	Effectiveness float32 `json:"effectiveness"`

	// Ko 確定数/乱数n発
	Ko         KOChance `json:"ko"`
	MaxDamage  int      `json:"maxDamage"`
	MaxPercent float32  `json:"maxPercent"`
	MinDamage  int      `json:"minDamage"`
	MinPercent float32  `json:"minPercent"`

	// Rolls 16 段階の乱数ダメージ(非減少)
	Rolls []int `json:"rolls"`

	// Stab タイプ一致
	Stab bool `json:"stab"`
}

// DefenderPreset 防御側の代表調整(耐久が上がる順)。SP は能力ポイント(Lv50・個体値31固定)。
// 性格の「無補正」は上昇・下降なし、「+B/-A」は防御上昇・攻撃下降のこと。
// engine の PresetKey と同一文字列(docs/adr/0009-bulk-calc-presets.md §1)。
// - `none`: 無振り(SP なし・無補正)。全分類
// - `hp`: H振り(HP 32・無補正)。全分類
// - `hb_boost`: H振り+B補正(HP 32・防御上昇 +B/-A)。物理
// - `hb`: HB振り(HP 32・防御 32・無補正)。物理
// - `hb_full`: HB特化(HP 32・防御 32・防御上昇 +B/-A)。物理
// - `hd_boost`: H振り+D補正(HP 32・特防上昇 +D/-A)。特殊
// - `hd`: HD振り(HP 32・特防 32・無補正)。特殊
// - `hd_full`: HD特化(HP 32・特防 32・特防上昇 +D/-A)。特殊
type DefenderPreset string

// Error defines model for Error.
type Error struct {
	// Code Example: invalid_request
	Code    string `json:"code"`
	Message string `json:"message"`
}

// FieldState defines model for FieldState.
type FieldState struct {
	AttackerScreens *Screens `json:"attackerScreens,omitempty"`
	DefenderScreens *Screens `json:"defenderScreens,omitempty"`
	Terrain         *Terrain `json:"terrain,omitempty"`
	Weather         *Weather `json:"weather,omitempty"`
}

// Format defines model for Format.
type Format string

// Individual 計算に使う個体。SP と性格 ID から実数値を導出する
type Individual struct {
	AbilityId *string `json:"abilityId,omitempty"`
	ItemId    *string `json:"itemId,omitempty"`
	Level     *int    `json:"level,omitempty"`

	// MoveId 攻撃側で使う技
	MoveId   *string `json:"moveId,omitempty"`
	NatureId string  `json:"natureId"`

	// Ranks ランク補正(-6..+6)。HP は持たない
	Ranks *RankBlock `json:"ranks,omitempty"`

	// Sp 能力ポイント。各 0..32、合計 <= 66
	Sp StatBlock `json:"sp"`

	// SpeciesKey {図鑑番号4桁}-{フォルム3桁}
	//
	// Example: 0445-000
	SpeciesKey SpeciesKey       `json:"speciesKey"`
	Status     *StatusCondition `json:"status,omitempty"`
	TeraType   *PokeType        `json:"teraType,omitempty"`
}

// Item defines model for Item.
type Item struct {
	Id     string `json:"id"`
	NameJa string `json:"nameJa"`
}

// KOChance 確定数/乱数n発
type KOChance struct {
	// ChancePercent guaranteed が false のとき、hits 回で倒せる確率(%)
	ChancePercent *float32 `json:"chancePercent,omitempty"`

	// Guaranteed 最小ダメージでも hits 回で倒せるなら true(確定n発)
	Guaranteed bool `json:"guaranteed"`

	// Hits 最大ダメージで倒すのに必要な攻撃回数
	Hits int `json:"hits"`
}

// Move defines model for Move.
type Move struct {
	Category MoveCategory `json:"category"`
	Id       string       `json:"id"`
	NameJa   string       `json:"nameJa"`

	// Power 威力(0 は変化技/固定ダメージ)
	Power    int      `json:"power"`
	Priority *int     `json:"priority,omitempty"`
	Type     PokeType `json:"type"`
}

// MoveCategory defines model for MoveCategory.
type MoveCategory string

// Nature defines model for Nature.
type Nature struct {
	// Id Example: adamant
	Id string `json:"id"`

	// Minus 下降補正(-10%)を受ける能力。無補正性格は null
	Minus *StatKey `json:"minus,omitempty"`

	// NameJa Example: いじっぱり
	NameJa string `json:"nameJa"`

	// Plus 上昇補正(+10%)を受ける能力。無補正性格は null
	Plus *StatKey `json:"plus,omitempty"`
}

// Observation defines model for Observation.
type Observation struct {
	Note *string `json:"note,omitempty"`

	// ObservedPercent ゲーム内表示に合わせた HP 減少割合(%)
	ObservedPercent float32 `json:"observedPercent"`
}

// PokeType defines model for PokeType.
type PokeType string

// RankBlock ランク補正(-6..+6)。HP は持たない
type RankBlock struct {
	Atk *int `json:"atk,omitempty"`
	Def *int `json:"def,omitempty"`
	Spa *int `json:"spa,omitempty"`
	Spd *int `json:"spd,omitempty"`
	Spe *int `json:"spe,omitempty"`
}

// ReverseCandidate defines model for ReverseCandidate.
type ReverseCandidate struct {
	ItemId *string `json:"itemId,omitempty"`

	// MatchScore 観測との一致度(0..1、高いほど一致)
	MatchScore float32 `json:"matchScore"`
	NatureId   *string `json:"natureId,omitempty"`

	// PresetLabel 型の名前(例 HB特化)
	PresetLabel string `json:"presetLabel"`

	// RangePercent この候補での想定ダメージ幅 [min, max]
	RangePercent *[]float32 `json:"rangePercent,omitempty"`

	// Sp 6ステータスの値(種族値・実数値・SPなどに共用)
	Sp StatBlock `json:"sp"`
}

// ReverseRequest defines model for ReverseRequest.
type ReverseRequest struct {
	// Attacker 計算に使う個体。SP と性格 ID から実数値を導出する
	Attacker Individual `json:"attacker"`

	// DefenderSpeciesKey {図鑑番号4桁}-{フォルム3桁}
	//
	// Example: 0445-000
	DefenderSpeciesKey SpeciesKey    `json:"defenderSpeciesKey"`
	Field              *FieldState   `json:"field,omitempty"`
	Format             Format        `json:"format"`
	MoveId             string        `json:"moveId"`
	Observations       []Observation `json:"observations"`
	Options            *CalcOptions  `json:"options,omitempty"`

	// Side どちら側の調整を逆算するか(defender=与ダメ観測 / attacker=被ダメ観測)
	Side ReverseSide `json:"side"`
}

// ReverseResult defines model for ReverseResult.
type ReverseResult struct {
	// Candidates 一致度の高い順
	Candidates []ReverseCandidate `json:"candidates"`
}

// ReverseSide どちら側の調整を逆算するか(defender=与ダメ観測 / attacker=被ダメ観測)
type ReverseSide string

// Screens defines model for Screens.
type Screens struct {
	AuroraVeil  *bool `json:"auroraVeil,omitempty"`
	LightScreen *bool `json:"lightScreen,omitempty"`
	Reflect     *bool `json:"reflect,omitempty"`
}

// SpeciesDetail defines model for SpeciesDetail.
type SpeciesDetail struct {
	Abilities []Ability `json:"abilities"`

	// BaseStats 6ステータスの値(種族値・実数値・SPなどに共用)
	BaseStats StatBlock `json:"baseStats"`
	DexNo     int       `json:"dexNo"`

	// Form フォルム番号
	Form int `json:"form"`

	// Key {図鑑番号4桁}-{フォルム3桁}
	//
	// Example: 0445-000
	Key SpeciesKey `json:"key"`

	// Learnset 覚える技の ID 一覧
	Learnset *[]string  `json:"learnset,omitempty"`
	NameJa   string     `json:"nameJa"`
	Types    []PokeType `json:"types"`
}

// SpeciesKey {図鑑番号4桁}-{フォルム3桁}
//
// Example: 0445-000
type SpeciesKey = string

// SpeciesSummary defines model for SpeciesSummary.
type SpeciesSummary struct {
	DexNo int `json:"dexNo"`

	// Form フォルム番号
	Form int `json:"form"`

	// Key {図鑑番号4桁}-{フォルム3桁}
	//
	// Example: 0445-000
	Key    SpeciesKey `json:"key"`
	NameJa string     `json:"nameJa"`
	Types  []PokeType `json:"types"`
}

// StatBlock 6ステータスの値(種族値・実数値・SPなどに共用)
type StatBlock struct {
	Atk int `json:"atk"`
	Def int `json:"def"`
	Hp  int `json:"hp"`
	Spa int `json:"spa"`
	Spd int `json:"spd"`
	Spe int `json:"spe"`
}

// StatKey defines model for StatKey.
type StatKey string

// StatusCondition defines model for StatusCondition.
type StatusCondition string

// Terrain defines model for Terrain.
type Terrain string

// Weather defines model for Weather.
type Weather string

// DeviceId defines model for DeviceId.
type DeviceId = string

// SessionId defines model for SessionId.
type SessionId = string

// CalcDamageParams defines parameters for CalcDamage.
type CalcDamageParams struct {
	// XDeviceId クライアント生成の端末 UUID
	XDeviceId DeviceId `json:"X-Device-Id"`

	// XSessionId セッション UUID
	XSessionId SessionId `json:"X-Session-Id"`
}

// CalcBulkParams defines parameters for CalcBulk.
type CalcBulkParams struct {
	// XDeviceId クライアント生成の端末 UUID
	XDeviceId DeviceId `json:"X-Device-Id"`

	// XSessionId セッション UUID
	XSessionId SessionId `json:"X-Session-Id"`
}

// CalcReverseParams defines parameters for CalcReverse.
type CalcReverseParams struct {
	// XDeviceId クライアント生成の端末 UUID
	XDeviceId DeviceId `json:"X-Device-Id"`

	// XSessionId セッション UUID
	XSessionId SessionId `json:"X-Session-Id"`
}

// SearchItemsParams defines parameters for SearchItems.
type SearchItemsParams struct {
	Q     *string `form:"q,omitempty" json:"q,omitempty"`
	Limit *int    `form:"limit,omitempty" json:"limit,omitempty"`

	// XDeviceId クライアント生成の端末 UUID
	XDeviceId DeviceId `json:"X-Device-Id"`

	// XSessionId セッション UUID
	XSessionId SessionId `json:"X-Session-Id"`
}

// SearchMovesParams defines parameters for SearchMoves.
type SearchMovesParams struct {
	Q     *string `form:"q,omitempty" json:"q,omitempty"`
	Limit *int    `form:"limit,omitempty" json:"limit,omitempty"`

	// XDeviceId クライアント生成の端末 UUID
	XDeviceId DeviceId `json:"X-Device-Id"`

	// XSessionId セッション UUID
	XSessionId SessionId `json:"X-Session-Id"`
}

// ListNaturesParams defines parameters for ListNatures.
type ListNaturesParams struct {
	// XDeviceId クライアント生成の端末 UUID
	XDeviceId DeviceId `json:"X-Device-Id"`

	// XSessionId セッション UUID
	XSessionId SessionId `json:"X-Session-Id"`
}

// SearchSpeciesParams defines parameters for SearchSpecies.
type SearchSpeciesParams struct {
	// Q 日本語名の前方一致(空なら全件・limit まで)
	Q      *string `form:"q,omitempty" json:"q,omitempty"`
	Format *Format `form:"format,omitempty" json:"format,omitempty"`
	Limit  *int    `form:"limit,omitempty" json:"limit,omitempty"`

	// XDeviceId クライアント生成の端末 UUID
	XDeviceId DeviceId `json:"X-Device-Id"`

	// XSessionId セッション UUID
	XSessionId SessionId `json:"X-Session-Id"`
}

// GetSpeciesParams defines parameters for GetSpecies.
type GetSpeciesParams struct {
	// XDeviceId クライアント生成の端末 UUID
	XDeviceId DeviceId `json:"X-Device-Id"`

	// XSessionId セッション UUID
	XSessionId SessionId `json:"X-Session-Id"`
}

// CalcDamageJSONRequestBody defines body for CalcDamage for application/json ContentType.
type CalcDamageJSONRequestBody = CalcRequest

// CalcBulkJSONRequestBody defines body for CalcBulk for application/json ContentType.
type CalcBulkJSONRequestBody = BulkCalcRequest

// CalcReverseJSONRequestBody defines body for CalcReverse for application/json ContentType.
type CalcReverseJSONRequestBody = ReverseRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// CalcDamage 1 vs 1 のダメージ計算
	// (POST /api/calc)
	CalcDamage(ctx echo.Context, params CalcDamageParams) error
	// CalcBulk 防御側の代表調整すべてに対する一括計算
	// (POST /api/calc/bulk)
	CalcBulk(ctx echo.Context, params CalcBulkParams) error
	// CalcReverse 観測ダメージから相手の調整候補を逆算
	// (POST /api/calc/reverse)
	CalcReverse(ctx echo.Context, params CalcReverseParams) error
	// SearchItems 持ち物を日本語名で前方一致検索
	// (GET /api/pokedex/items)
	SearchItems(ctx echo.Context, params SearchItemsParams) error
	// SearchMoves 技を日本語名で前方一致検索
	// (GET /api/pokedex/moves)
	SearchMoves(ctx echo.Context, params SearchMovesParams) error
	// ListNatures 性格の一覧(補正する能力)
	// (GET /api/pokedex/natures)
	ListNatures(ctx echo.Context, params ListNaturesParams) error
	// SearchSpecies ポケモンを日本語名で前方一致検索
	// (GET /api/pokedex/species)
	SearchSpecies(ctx echo.Context, params SearchSpeciesParams) error
	// GetSpecies 種族の詳細(タイプ・種族値・特性・覚える技)
	// (GET /api/pokedex/species/{key})
	GetSpecies(ctx echo.Context, key SpeciesKey, params GetSpeciesParams) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// CalcDamage converts echo context to params.
func (w *ServerInterfaceWrapper) CalcDamage(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params CalcDamageParams

	headers := ctx.Request().Header
	// ------------- Required header parameter "X-Device-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Device-Id")]; found {
		var XDeviceId DeviceId
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-Device-Id, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Device-Id", valueList[0], &XDeviceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-Device-Id: %s", err))
		}

		params.XDeviceId = XDeviceId
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter X-Device-Id is required, but not found"))
	}
	// ------------- Required header parameter "X-Session-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Session-Id")]; found {
		var XSessionId SessionId
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-Session-Id, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Session-Id", valueList[0], &XSessionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-Session-Id: %s", err))
		}

		params.XSessionId = XSessionId
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter X-Session-Id is required, but not found"))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CalcDamage(ctx, params)
	return err
}

// CalcBulk converts echo context to params.
func (w *ServerInterfaceWrapper) CalcBulk(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params CalcBulkParams

	headers := ctx.Request().Header
	// ------------- Required header parameter "X-Device-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Device-Id")]; found {
		var XDeviceId DeviceId
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-Device-Id, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Device-Id", valueList[0], &XDeviceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-Device-Id: %s", err))
		}

		params.XDeviceId = XDeviceId
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter X-Device-Id is required, but not found"))
	}
	// ------------- Required header parameter "X-Session-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Session-Id")]; found {
		var XSessionId SessionId
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-Session-Id, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Session-Id", valueList[0], &XSessionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-Session-Id: %s", err))
		}

		params.XSessionId = XSessionId
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter X-Session-Id is required, but not found"))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CalcBulk(ctx, params)
	return err
}

// CalcReverse converts echo context to params.
func (w *ServerInterfaceWrapper) CalcReverse(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params CalcReverseParams

	headers := ctx.Request().Header
	// ------------- Required header parameter "X-Device-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Device-Id")]; found {
		var XDeviceId DeviceId
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-Device-Id, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Device-Id", valueList[0], &XDeviceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-Device-Id: %s", err))
		}

		params.XDeviceId = XDeviceId
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter X-Device-Id is required, but not found"))
	}
	// ------------- Required header parameter "X-Session-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Session-Id")]; found {
		var XSessionId SessionId
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-Session-Id, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Session-Id", valueList[0], &XSessionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-Session-Id: %s", err))
		}

		params.XSessionId = XSessionId
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter X-Session-Id is required, but not found"))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CalcReverse(ctx, params)
	return err
}

// SearchItems converts echo context to params.
func (w *ServerInterfaceWrapper) SearchItems(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params SearchItemsParams
	// ------------- Optional query parameter "q" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "q", ctx.QueryParams(), &params.Q, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter q: %s", err))
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", ctx.QueryParams(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	headers := ctx.Request().Header
	// ------------- Required header parameter "X-Device-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Device-Id")]; found {
		var XDeviceId DeviceId
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-Device-Id, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Device-Id", valueList[0], &XDeviceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-Device-Id: %s", err))
		}

		params.XDeviceId = XDeviceId
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter X-Device-Id is required, but not found"))
	}
	// ------------- Required header parameter "X-Session-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Session-Id")]; found {
		var XSessionId SessionId
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-Session-Id, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Session-Id", valueList[0], &XSessionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-Session-Id: %s", err))
		}

		params.XSessionId = XSessionId
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter X-Session-Id is required, but not found"))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.SearchItems(ctx, params)
	return err
}

// SearchMoves converts echo context to params.
func (w *ServerInterfaceWrapper) SearchMoves(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params SearchMovesParams
	// ------------- Optional query parameter "q" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "q", ctx.QueryParams(), &params.Q, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter q: %s", err))
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", ctx.QueryParams(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	headers := ctx.Request().Header
	// ------------- Required header parameter "X-Device-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Device-Id")]; found {
		var XDeviceId DeviceId
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-Device-Id, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Device-Id", valueList[0], &XDeviceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-Device-Id: %s", err))
		}

		params.XDeviceId = XDeviceId
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter X-Device-Id is required, but not found"))
	}
	// ------------- Required header parameter "X-Session-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Session-Id")]; found {
		var XSessionId SessionId
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-Session-Id, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Session-Id", valueList[0], &XSessionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-Session-Id: %s", err))
		}

		params.XSessionId = XSessionId
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter X-Session-Id is required, but not found"))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.SearchMoves(ctx, params)
	return err
}

// ListNatures converts echo context to params.
func (w *ServerInterfaceWrapper) ListNatures(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListNaturesParams

	headers := ctx.Request().Header
	// ------------- Required header parameter "X-Device-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Device-Id")]; found {
		var XDeviceId DeviceId
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-Device-Id, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Device-Id", valueList[0], &XDeviceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-Device-Id: %s", err))
		}

		params.XDeviceId = XDeviceId
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter X-Device-Id is required, but not found"))
	}
	// ------------- Required header parameter "X-Session-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Session-Id")]; found {
		var XSessionId SessionId
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-Session-Id, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Session-Id", valueList[0], &XSessionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-Session-Id: %s", err))
		}

		params.XSessionId = XSessionId
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter X-Session-Id is required, but not found"))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListNatures(ctx, params)
	return err
}

// SearchSpecies converts echo context to params.
func (w *ServerInterfaceWrapper) SearchSpecies(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params SearchSpeciesParams
	// ------------- Optional query parameter "q" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "q", ctx.QueryParams(), &params.Q, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter q: %s", err))
	}

	// ------------- Optional query parameter "format" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "format", ctx.QueryParams(), &params.Format, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter format: %s", err))
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", ctx.QueryParams(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	headers := ctx.Request().Header
	// ------------- Required header parameter "X-Device-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Device-Id")]; found {
		var XDeviceId DeviceId
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-Device-Id, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Device-Id", valueList[0], &XDeviceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-Device-Id: %s", err))
		}

		params.XDeviceId = XDeviceId
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter X-Device-Id is required, but not found"))
	}
	// ------------- Required header parameter "X-Session-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Session-Id")]; found {
		var XSessionId SessionId
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-Session-Id, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Session-Id", valueList[0], &XSessionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-Session-Id: %s", err))
		}

		params.XSessionId = XSessionId
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter X-Session-Id is required, but not found"))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.SearchSpecies(ctx, params)
	return err
}

// GetSpecies converts echo context to params.
func (w *ServerInterfaceWrapper) GetSpecies(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "key" -------------
	var key SpeciesKey

	err = runtime.BindStyledParameterWithOptions("simple", "key", ctx.Param("key"), &key, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter key: %s", err))
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetSpeciesParams

	headers := ctx.Request().Header
	// ------------- Required header parameter "X-Device-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Device-Id")]; found {
		var XDeviceId DeviceId
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-Device-Id, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Device-Id", valueList[0], &XDeviceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-Device-Id: %s", err))
		}

		params.XDeviceId = XDeviceId
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter X-Device-Id is required, but not found"))
	}
	// ------------- Required header parameter "X-Session-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Session-Id")]; found {
		var XSessionId SessionId
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-Session-Id, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Session-Id", valueList[0], &XSessionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-Session-Id: %s", err))
		}

		params.XSessionId = XSessionId
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter X-Session-Id is required, but not found"))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetSpecies(ctx, key, params)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlersOptions configures RegisterHandlersWithOptions.
type RegisterHandlersOptions struct {
	// BaseURL is prepended to every registered path so the API can be served
	// under a prefix.
	BaseURL string
	// OperationMiddlewares lets the caller attach per-operation middleware at
	// registration time. The map key is the OpenAPI `operationId` value as it
	// appears in the spec (the raw, un-normalized form). Operations that have
	// no entry are registered with no extra middleware. A nil map disables
	// per-operation middleware entirely.
	OperationMiddlewares map[string][]echo.MiddlewareFunc
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{})
}

// RegisterHandlersWithBaseURL registers handlers and prepends BaseURL to the
// paths so the API can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{BaseURL: baseURL})
}

// RegisterHandlersWithOptions registers handlers using the supplied options,
// including any per-operation middleware.
func RegisterHandlersWithOptions(router EchoRouter, si ServerInterface, options RegisterHandlersOptions) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(options.BaseURL+"/api/pokedex/species", wrapper.SearchSpecies, options.OperationMiddlewares["searchSpecies"]...)
	router.GET(options.BaseURL+"/api/pokedex/species/:key", wrapper.GetSpecies, options.OperationMiddlewares["getSpecies"]...)
	router.GET(options.BaseURL+"/api/pokedex/moves", wrapper.SearchMoves, options.OperationMiddlewares["searchMoves"]...)
	router.GET(options.BaseURL+"/api/pokedex/items", wrapper.SearchItems, options.OperationMiddlewares["searchItems"]...)
	router.GET(options.BaseURL+"/api/pokedex/natures", wrapper.ListNatures, options.OperationMiddlewares["listNatures"]...)
	router.POST(options.BaseURL+"/api/calc", wrapper.CalcDamage, options.OperationMiddlewares["calcDamage"]...)
	router.POST(options.BaseURL+"/api/calc/bulk", wrapper.CalcBulk, options.OperationMiddlewares["calcBulk"]...)
	router.POST(options.BaseURL+"/api/calc/reverse", wrapper.CalcReverse, options.OperationMiddlewares["calcReverse"]...)

}

type ErrorJSONResponse Error

type CalcDamageRequestObject struct {
	Params CalcDamageParams
	Body   *CalcDamageJSONRequestBody
}

type CalcDamageResponseObject interface {
	VisitCalcDamageResponse(w http.ResponseWriter) error
}

type CalcDamage200JSONResponse CalcResult

func (response CalcDamage200JSONResponse) VisitCalcDamageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type CalcDamage400JSONResponse struct{ ErrorJSONResponse }

func (response CalcDamage400JSONResponse) VisitCalcDamageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CalcDamagedefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response CalcDamagedefaultJSONResponse) VisitCalcDamageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type CalcBulkRequestObject struct {
	Params CalcBulkParams
	Body   *CalcBulkJSONRequestBody
}

type CalcBulkResponseObject interface {
	VisitCalcBulkResponse(w http.ResponseWriter) error
}

type CalcBulk200JSONResponse BulkCalcResult

func (response CalcBulk200JSONResponse) VisitCalcBulkResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type CalcBulk400JSONResponse struct{ ErrorJSONResponse }

func (response CalcBulk400JSONResponse) VisitCalcBulkResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CalcBulkdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response CalcBulkdefaultJSONResponse) VisitCalcBulkResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type CalcReverseRequestObject struct {
	Params CalcReverseParams
	Body   *CalcReverseJSONRequestBody
}

type CalcReverseResponseObject interface {
	VisitCalcReverseResponse(w http.ResponseWriter) error
}

type CalcReverse200JSONResponse ReverseResult

func (response CalcReverse200JSONResponse) VisitCalcReverseResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type CalcReverse400JSONResponse struct{ ErrorJSONResponse }

func (response CalcReverse400JSONResponse) VisitCalcReverseResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CalcReversedefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response CalcReversedefaultJSONResponse) VisitCalcReverseResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type SearchItemsRequestObject struct {
	Params SearchItemsParams
}

type SearchItemsResponseObject interface {
	VisitSearchItemsResponse(w http.ResponseWriter) error
}

type SearchItems200JSONResponse []Item

func (response SearchItems200JSONResponse) VisitSearchItemsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type SearchItemsdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response SearchItemsdefaultJSONResponse) VisitSearchItemsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type SearchMovesRequestObject struct {
	Params SearchMovesParams
}

type SearchMovesResponseObject interface {
	VisitSearchMovesResponse(w http.ResponseWriter) error
}

type SearchMoves200JSONResponse []Move

func (response SearchMoves200JSONResponse) VisitSearchMovesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type SearchMovesdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response SearchMovesdefaultJSONResponse) VisitSearchMovesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type ListNaturesRequestObject struct {
	Params ListNaturesParams
}

type ListNaturesResponseObject interface {
	VisitListNaturesResponse(w http.ResponseWriter) error
}

type ListNatures200JSONResponse []Nature

func (response ListNatures200JSONResponse) VisitListNaturesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListNaturesdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response ListNaturesdefaultJSONResponse) VisitListNaturesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type SearchSpeciesRequestObject struct {
	Params SearchSpeciesParams
}

type SearchSpeciesResponseObject interface {
	VisitSearchSpeciesResponse(w http.ResponseWriter) error
}

type SearchSpecies200JSONResponse []SpeciesSummary

func (response SearchSpecies200JSONResponse) VisitSearchSpeciesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type SearchSpeciesdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response SearchSpeciesdefaultJSONResponse) VisitSearchSpeciesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetSpeciesRequestObject struct {
	Key    SpeciesKey `json:"key"`
	Params GetSpeciesParams
}

type GetSpeciesResponseObject interface {
	VisitGetSpeciesResponse(w http.ResponseWriter) error
}

type GetSpecies200JSONResponse SpeciesDetail

func (response GetSpecies200JSONResponse) VisitGetSpeciesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetSpecies404JSONResponse struct{ ErrorJSONResponse }

func (response GetSpecies404JSONResponse) VisitGetSpeciesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetSpeciesdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response GetSpeciesdefaultJSONResponse) VisitGetSpeciesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// CalcDamage 1 vs 1 のダメージ計算
	// (POST /api/calc)
	CalcDamage(ctx context.Context, request CalcDamageRequestObject) (CalcDamageResponseObject, error)
	// CalcBulk 防御側の代表調整すべてに対する一括計算
	// (POST /api/calc/bulk)
	CalcBulk(ctx context.Context, request CalcBulkRequestObject) (CalcBulkResponseObject, error)
	// CalcReverse 観測ダメージから相手の調整候補を逆算
	// (POST /api/calc/reverse)
	CalcReverse(ctx context.Context, request CalcReverseRequestObject) (CalcReverseResponseObject, error)
	// SearchItems 持ち物を日本語名で前方一致検索
	// (GET /api/pokedex/items)
	SearchItems(ctx context.Context, request SearchItemsRequestObject) (SearchItemsResponseObject, error)
	// SearchMoves 技を日本語名で前方一致検索
	// (GET /api/pokedex/moves)
	SearchMoves(ctx context.Context, request SearchMovesRequestObject) (SearchMovesResponseObject, error)
	// ListNatures 性格の一覧(補正する能力)
	// (GET /api/pokedex/natures)
	ListNatures(ctx context.Context, request ListNaturesRequestObject) (ListNaturesResponseObject, error)
	// SearchSpecies ポケモンを日本語名で前方一致検索
	// (GET /api/pokedex/species)
	SearchSpecies(ctx context.Context, request SearchSpeciesRequestObject) (SearchSpeciesResponseObject, error)
	// GetSpecies 種族の詳細(タイプ・種族値・特性・覚える技)
	// (GET /api/pokedex/species/{key})
	GetSpecies(ctx context.Context, request GetSpeciesRequestObject) (GetSpeciesResponseObject, error)
}

type StrictHandlerFunc func(ctx echo.Context, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// CalcDamage operation middleware
func (sh *strictHandler) CalcDamage(ctx echo.Context, params CalcDamageParams) error {
	var request CalcDamageRequestObject

	request.Params = params

	var body CalcDamageJSONRequestBody
	var err error
	if binder, ok := ctx.Echo().Binder.(*echo.DefaultBinder); ok {
		// Bind only the request body, so that path and query parameters
		// are not also bound into the body struct.
		err = binder.BindBody(ctx, &body)
	} else {
		// A custom binder is installed on the Echo instance; defer to it
		// entirely, since echo.Binder does not expose body-only binding.
		err = ctx.Bind(&body)
	}
	if err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CalcDamage(ctx.Request().Context(), request.(CalcDamageRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CalcDamage")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(CalcDamageResponseObject); ok {
		return validResponse.VisitCalcDamageResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// CalcBulk operation middleware
func (sh *strictHandler) CalcBulk(ctx echo.Context, params CalcBulkParams) error {
	var request CalcBulkRequestObject

	request.Params = params

	var body CalcBulkJSONRequestBody
	var err error
	if binder, ok := ctx.Echo().Binder.(*echo.DefaultBinder); ok {
		// Bind only the request body, so that path and query parameters
		// are not also bound into the body struct.
		err = binder.BindBody(ctx, &body)
	} else {
		// A custom binder is installed on the Echo instance; defer to it
		// entirely, since echo.Binder does not expose body-only binding.
		err = ctx.Bind(&body)
	}
	if err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CalcBulk(ctx.Request().Context(), request.(CalcBulkRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CalcBulk")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(CalcBulkResponseObject); ok {
		return validResponse.VisitCalcBulkResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// CalcReverse operation middleware
func (sh *strictHandler) CalcReverse(ctx echo.Context, params CalcReverseParams) error {
	var request CalcReverseRequestObject

	request.Params = params

	var body CalcReverseJSONRequestBody
	var err error
	if binder, ok := ctx.Echo().Binder.(*echo.DefaultBinder); ok {
		// Bind only the request body, so that path and query parameters
		// are not also bound into the body struct.
		err = binder.BindBody(ctx, &body)
	} else {
		// A custom binder is installed on the Echo instance; defer to it
		// entirely, since echo.Binder does not expose body-only binding.
		err = ctx.Bind(&body)
	}
	if err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CalcReverse(ctx.Request().Context(), request.(CalcReverseRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CalcReverse")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(CalcReverseResponseObject); ok {
		return validResponse.VisitCalcReverseResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// SearchItems operation middleware
func (sh *strictHandler) SearchItems(ctx echo.Context, params SearchItemsParams) error {
	var request SearchItemsRequestObject

	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.SearchItems(ctx.Request().Context(), request.(SearchItemsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SearchItems")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(SearchItemsResponseObject); ok {
		return validResponse.VisitSearchItemsResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// SearchMoves operation middleware
func (sh *strictHandler) SearchMoves(ctx echo.Context, params SearchMovesParams) error {
	var request SearchMovesRequestObject

	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.SearchMoves(ctx.Request().Context(), request.(SearchMovesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SearchMoves")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(SearchMovesResponseObject); ok {
		return validResponse.VisitSearchMovesResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// ListNatures operation middleware
func (sh *strictHandler) ListNatures(ctx echo.Context, params ListNaturesParams) error {
	var request ListNaturesRequestObject

	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListNatures(ctx.Request().Context(), request.(ListNaturesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListNatures")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(ListNaturesResponseObject); ok {
		return validResponse.VisitListNaturesResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// SearchSpecies operation middleware
func (sh *strictHandler) SearchSpecies(ctx echo.Context, params SearchSpeciesParams) error {
	var request SearchSpeciesRequestObject

	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.SearchSpecies(ctx.Request().Context(), request.(SearchSpeciesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SearchSpecies")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(SearchSpeciesResponseObject); ok {
		return validResponse.VisitSearchSpeciesResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetSpecies operation middleware
func (sh *strictHandler) GetSpecies(ctx echo.Context, key SpeciesKey, params GetSpeciesParams) error {
	var request GetSpeciesRequestObject

	request.Key = key
	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetSpecies(ctx.Request().Context(), request.(GetSpeciesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetSpecies")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetSpeciesResponseObject); ok {
		return validResponse.VisitGetSpeciesResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7Fz/UxtHlv9XpuY2VaIikMA2VUtVfohNds3lGxWS3btKuHjQNGgWaUaZGYE5F1XqEWC+OSYOBNs4trGJ",
	"wZBITmxvwDim6u5PaWYk/our190ajUYtJGzHW3t3v+CR1K+73+v3Xn/el/ElOWGkM4aOdNuSey7JGcVU",
	"0shGJv3Ui8a0BOpT4VlFVsLUMrZm6HKPTJwiyT8kzgZx7pH8Y5KfLS3f8WaXCC6UdorerR3ps8/6euWo",
	"rMHoJFJUZMpRWVfSSO6R/62dzdzep8pR2URfZTUTqXKPbWZRVLYSSZRWYE17IgPDLdvU9BF5cjIqDyDL",
	"0gxdvKV9ks8T51eS3yT5x002wCc66Q4mYbCVMXQLUQm9Z5qGCQ8JQ7eRbsOjksmktIQC24r9zYK9XQrM",
	"+AcTDcs98r/EqoKPsV+tGJuNrhLmbQvEnX9OhcCHw2zvDmkpzZ6Ax4xpZJBpa2xjmirYPuP/XxvItiqF",
	"z4HcHzwYrQw2hv6GEjbMczabGj2npBKfoK+yyLLr11dsW0mMIrMZy326qo1palZJyZTrYaSryBzIoISG",
	"rPfRRDP6wMjJqDysoZTajORPMGjAVmxESQwzrdhNadioyais2Sj9F8XUFG4xtQfl/logeNVbOyB4luAH",
	"XnG5/DxP8A3iLHiLmOD10txDqa83UrqFSys/eDccgoulJ3cJLnQe5W4SZ75NZkvQufVsKqUMpVBFL+uO",
	"k3+hmKZC+U8bY9xc64YadItWM0bhUD/mQyejcsZEFhIx6jMQKT18djR9xZ1dJc41d2mHOLk2govefI7g",
	"gjs7c7R+m+Ad9+AWwdcJvuOt3nMLN7mt5mdJzvlCL809LC3NUIqidEY63P97RDd0FJWSmaiUHPpyyDAs",
	"G57op+FsKtVGchjo9rzCfCM61adT6acqnbsx5y5+x+m6aujaSM7xFi/DFvEqwXcI3iL4CsFFgr8nuHB0",
	"d4bgnfL6InGulQ+W4WCBgeCZHSfcXq7e/VSq9QcYMkKumtGqMQktxD/24w3VyqYEdvqqFmca48zftMK/",
	"vxljvCnzQkbpaseyaYwLfKGN0n1qSwbF9P3k58joPlCGUKreVsrrW6WNZ+7SlcjhiwXp/FlvsUiceSkm",
	"nT9bmttzF7+DR/bl22fL9295P91vkwWbM/0zbGbB/LTDMuXc1W7Xn1ck16A7qJNrwtRsLaFwjocVurlh",
	"JWWh8P3l5X7w5nJVnoYMI4UUnW5QuObvdK+cjOoN3CZVh10rsMPfDkrLW/zimM9FKmx3MAKJOLPEmXen",
	"tt3pWaGuvIy7P4H7Od7ptOJwzvcHrilNt9EIMoEWDQ+jhK2NIR1ZlgjlHQDqzK+W1na93GYkHpXiHV1n",
	"4O+ZqNQZlbqi0umARPRseohNPGo0E8b7H59LKnqCHmRaudirpJURJN5lWrnYj8wER3x1a6U1/VhqTT+O",
	"2jRSKQHrnd2SV3h6dPNrgguHez97K49IPkfy6yT/nDi7kaPvb3u7a+6jb2oghHDrfezXzm66lcCnMJ6w",
	"bGXomDM43M2VLz8Rm3VQkxhDQbEEBVwjjxrRRoPaElYNvjt6sCIlDDnpOi6Orv/ivlh38RMQ5/798vpW",
	"efvAW3kSKeeWDvemCV483J0neJE4C0d3ZwAYDPRLBBfL+d/c+TWS/57KAEKfyAdjZ+Ikv+/mFg5/+9bN",
	"bZzqdNeeuYWbbRQdeLlN7+5zggskt1iaWmcOnuQAVRzuznvXL5P8/uHuwtGNKwRvA+zIYZJbfPtsrP1d",
	"Nort1B/rLe971/IVigLB3wJKgZWQPqLpSCK4IDGu30cTEsFb7tLi4W7O++6y+9OqO7saUY2EFVNUMxaP",
	"x//YPpRNjbYnlFSinaO9jrQq/ddmJ9t9u3QBwNGFHqk0tc4uqQgVBN1qft/nCIa701sM8lG6ZOZCT+Vi",
	"i5zvl051NRnPod6FnvB16FMHRSFREcE0DEDyOS70+FdsiEywgRpKChEv9PjXspC8+Q7UOi56Q1yU5vaO",
	"rv9SmaPXnwPgLJ8DqHvDoqNkQi4ClD4XvSEuasiP3YEclZGeTYPpwtnLUTmZgT/8fOgj+wxrwZNa/UVl",
	"n+kvg4KbyQ+ZQ2DCUKm3RBeVdCbFfNaYktLUL02OBQRzpZFl1XrZBvEsnb06XuQvAhd5Q9QxkDARan6r",
	"VoYFI9oTU9rINBVNb0bxKR82GZXHkWInm4Ocv/JhQvD1Jx/A+IhOtjR9JIUCSuF/oRrZoVRQnNWjCUCp",
	"ekC8NVsqrBK8c/jbAcEzzG9WHOwW85dSX69E8AJx5tzCHW/lkZvbgADz0dfu5WcMF8nR8CmxZEiLUP8E",
	"UUEKjaFalHsmTi8qLZ1N8w+aXv0guHQb4Dzmy+kltMmE4c0DTm66JV2xs2ajWN9U9NGmqvaJoo+eTRmJ",
	"UaCwMlSAqdTHw3LP50101FZsTjgYBvr1lyN4+aUpKd7RcaqL5LC7NFvempW+yMbjpxLvSN3dbPWXCz4t",
	"W7GzzW2Kjjpn6KpGd8lsS/mUSq1VpvuNUUQpJgfDpxP2NVYwYvXPicpY5HcAfr3x/J0PdesTO/cAuXgr",
	"j2IMY+qlG8/qLC1BiQMYtnaOkaxiKrqNkCoRvCjRkFCiUIVmU3I4qdmW5K7dJnjTzV0jeI04C6V7z0pf",
	"X468JQTv1RkFNnQr5z66GsTCBG8Sx5FEqwBuceYkOLcIYxUYbBNg2KgM9OLlNjZDy9H5b1AWd9yD6fID",
	"TPA2N+61297KI7neK4SOjK5Ww6no4D40xgT3U0Kx0YhhNjUfoD5XGQs+8IRaFpUzxjgy64XibmF3fi0S",
	"B4Dsp9diDAUHRdUmi7xjxtQMk6exfRcr9KM2N9rWTPUYo+BTRauiq/DWSOrnAjKuXISZ5IRFMyDch7En",
	"5pVEl+JH1Bs0svYq9FFUJa3oYsij6Vmrdb8Fzo96yzpXzQIIjkzbO+NvtcH9enWV4G+Is8Adec7xgWYl",
	"jClKOgN9IS8YVJsqJwRP0cTvfYJ/Js68iKNM6nUxBGiWM/T2qzN0Qpf68ZCFzDGFbSZ8wLphI3FanlIh",
	"taEvJc4vYDr5u+7MNEskgotZmiXOVfBo+I50vl9igb8794u7NCv0oCFewquK+PHNKKDvOqBDENWwZiI5",
	"Ko8rNs0FoRRK2KaWAP9lKjQ41xKIjhtJ2sAqWJdmGTodYWR1EOZwaoL/ZE0kkpR6KDtC07yJURiYZCGF",
	"aiojlFJVzFFqYIjmLYcVzZwQ2lkV29TLE+poj4lTrGh+d0fH290Q/Zyn4T0t09yh4e1UPcK0R8M+ykeB",
	"3QEQ2N4tcl4qGn4FaiujvBK1+krU6KWpRVHGJ2gMmRY6p+iqpgojrhOg87RiJ5IDCcMUoJnyg8fe7o8U",
	"dxRYtsp99iAS7+joJDl8tHOduqd9gh+yH4XYIwi1WywgNCgEuLcXoCi2dMWdq9QCWIwuTvcr+khjjEXT",
	"PgU3d6N8/xbgHVzw8o9Dt627Ny19ntb0qJRWLg4K0oJVJqtZwa5gUrBLkBPMtAK4eYAgLEBU6g5WRq45",
	"vcHGmvJ/r858XCm3etO0XnsLXk+TNXnf+iN+uVqxpalNsRk/zgEY2rDeQCdqueoZksexSiQuSSQqbkiA",
	"9n2nAdVf6i+O7s60Wu+tc3PNip6BnRzDxwAXdNghPCR4HfIlNKXNktnEuXaUm6HJlhs0+lmIVGT5zuHu",
	"18xZMCcpxaSKxN8p39sJ/tQWyP0EKkCV4cIrOJDwClls1jRM5S9IE9YN66OwFEAINltrBCYaBjjSymDR",
	"3cR1rBfZipY6AS5lZAPZdFqhwdUlYXYqcL01VZ9Kc4+g0WNIsRC4FusEvjgqp5Bi6sJiSPnBTehYocVG",
	"KB/09Uqg+Q82BZdGo/aTkC5XtxgN8F6v1oNVmXM/XLu1S+7a46NvvimtbLtXfz3trePJ9kskv0KchyS/",
	"Q/J3T8FXcjQQc8RPnz7THo/H5aicUWwbmTDNf3web//j4KXTk+3s4dTkH0SXbugYBeXLix8Z4sIa+C8R",
	"3qxulfEgDIFHT3oFHROjwxeta1k1XG6IAjqbHPUo9cdMNFwOoUBb7M+qylkntm7i7JH8DMUxB/AMWGcj",
	"UtoqeKtXIRec36/mhfP7A/0UsT+E2Gj659LyVlsj7N4Qltf/kMyIv+dIvCHIboifm2WAMtSpjrILT2YL",
	"sVnZFI1kyO2m4qJPME9A8UNZ0poKAK8ChYpCQ1lTpzZmKqkJS7OCQd6QoqYmvvQ/WimEYFfDJkL/Kd7A",
	"p9V6R7OFw+EmRQOaZU8EYknREn+tFkiaLWFlYdt0Q1HZUmi8aunGuGBeOEZNHzZEtv89cX4medYii0n+",
	"Pn1YJs42PDjP3OIL2hlXCKJ2Xh3J73ubC6XiHMl/S71HjuSfS+/299Gq7OH+ird53Z2eLa8vRlgoIP37",
	"ux9+APlWd7l4uAtenFcH/2xE3kskjbaYBGY+QPcnxaSBcW3YpllZ5zHNMMwR51qli5eCBVjoCx1+yK+z",
	"fH75wdXSk6nIuQ/e/az3vY602tYDRUcof0s815fDfhVcOtXpf+vUFwYkVk6XOkOWzvKrrEzJqwXd3bwU",
	"HRpKnJ/gGRelgaQxrhrjusR2GEyRSMlMTLFHYyoajlkZJWZl1JiVQXzG8vaV8tbzSuEdCtIkvw3dzc4W",
	"XWyW4B3W0dzXGwn0LbdBTFnbcUwHVPuKIft0uH8dUFZVnHJUtjWb3lIZYxRB1R3OVI7KgOyY1sQ7Ojvi",
	"DIYjXcloco98qiPecYpdZ0nqzGJKRosBNXzIGCwyAm9HUTDEDbQJx++wCPZ1NwAy1SExv+97Mtp0bLUj",
	"e3KQuTNk2WcNdeK1dUUH+8Ema30mTzzWtGR3xeOveWneS1fXlc0MtfR0ybt9C87rdDzeaEJ/h5Ue72jV",
	"A7VIAddIBZXIndKYJXVKQs8BOqaMWCyeSCXkQSD1FSYG7R5BrWlYkCx2ErwBlsRsmDamBJtm2F0MA4ov",
	"4Ff8gLXRlG5OEbzNm2l4vy8ukhwO9PnSIozfUBI7X/tvpe0jVmnkiPmdkgQXzhzu/z3c/0vn65VKj/er",
	"AwJtvuLlYLIuOta5wFtfLkgEbx7hXYL3iLPQRms6ewRD9MfOGYx6N0fjwR2/A5iuscjY44udpXvJYbbH",
	"0AZJfpV6mUoTNN4pX952F1agkFSc4oUq2jpU6RkH+BNoLWdpn0iwFx3cjbe7TnfMO5n+ezVIX3o6BT4R",
	"r9X1Ltf7DWin/Sf3GuE3FN6w5wj1XYu8BwvQ8TLLTv5D3EijHriA3jPrhgsMWsgWfmzJx5gsUdHYzdBb",
	"cZbgOzFeoMF3apoZz/e/1QZJDJ6+hTaQWu/zAihwMeCueMaDm8ZAP30pYQZgFKvz5Pd9awBb+UIXpnZq",
	"zPqn+6V7zwhe4d22PNda8K4uQRnGucb6bwHdbFz2Vh5VdrtZenqbOPPlF8+Jk2tsZDyb809uZ6EE7Rs2",
	"s9rMXkMrY0f3ho2Lq0NNowAoMnQuzy2EFNZP1DW2LACMKroY86P6ESSAfQNIMRNJFri/Ic2KXmJv2X2V",
	"ReZE9SW7r+Rj3+UTE6W0tGbXEIp7rrriwaarTkHZafAV1a6l5AnIWZAJq1PD4EXME2uvql7VKZ1r3uoP",
	"3q0fy9u33aUrACLmrnjf7TH/5m3cKj25F9AqrkYCxYKEejPF+pCO+X/F+r0VC+TckmLRfO3rUqn53GtT",
	"JlY1baxOH2iW/REf8yZvwN/74BhPLR0dxSWv6+gqLxmw+SL8LQMK3Fjupa2lY+PNi028AE9Fv0E/EBJd",
	"jYoWgioK76OycMud3oLgLr9PTV+imHGzTY4K3cNL+ZRqxbIlsFIp7v4vcVF1Fa+mGs9OiL1ZW8kevC7f",
	"VZNrfV1OjFtD7NIomphsaBN/RvY/2iBaKpJJ0HISKI5RHYSUYlUFWSWn8f+H0Gp96pU1sIWFeIVWoGdM",
	"t8oPH5eePGKg//SbAv2+WrPVI/67cvDSTaB4BXmh3CbJ7wcrrw1cNCwA7XpcpUK91oqNxpUJqfR0sbT8",
	"sxyVs2ZK7pFj9Lrjk9XXJW7T7PmBe9UpTW/yqhpEyPO5YJwc3Ce7YNqqqlLZYL0yCosZwewBvEZVCXb4",
	"bDTWmRyc/J8BAA==",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
