// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
)

// Defines values for DefenderPreset.
const (
	DefenderPresetHb      DefenderPreset = "hb"
	DefenderPresetHbBoost DefenderPreset = "hb_boost"
	DefenderPresetHd      DefenderPreset = "hd"
	DefenderPresetHdBoost DefenderPreset = "hd_boost"
	DefenderPresetHp      DefenderPreset = "hp"
	DefenderPresetNone    DefenderPreset = "none"
)

// Valid indicates whether the value is a known member of the DefenderPreset enum.
func (e DefenderPreset) Valid() bool {
	switch e {
	case DefenderPresetHb:
		return true
	case DefenderPresetHbBoost:
		return true
	case DefenderPresetHd:
		return true
	case DefenderPresetHdBoost:
		return true
	case DefenderPresetHp:
		return true
	case DefenderPresetNone:
		return true
	default:
		return false
	}
}

// Defines values for Format.
const (
	Double Format = "double"
	Single Format = "single"
)

// Valid indicates whether the value is a known member of the Format enum.
func (e Format) Valid() bool {
	switch e {
	case Double:
		return true
	case Single:
		return true
	default:
		return false
	}
}

// Defines values for MoveCategory.
const (
	Physical MoveCategory = "physical"
	Special  MoveCategory = "special"
	Status   MoveCategory = "status"
)

// Valid indicates whether the value is a known member of the MoveCategory enum.
func (e MoveCategory) Valid() bool {
	switch e {
	case Physical:
		return true
	case Special:
		return true
	case Status:
		return true
	default:
		return false
	}
}

// Defines values for PokeType.
const (
	PokeTypeBug      PokeType = "bug"
	PokeTypeDark     PokeType = "dark"
	PokeTypeDragon   PokeType = "dragon"
	PokeTypeElectric PokeType = "electric"
	PokeTypeFairy    PokeType = "fairy"
	PokeTypeFighting PokeType = "fighting"
	PokeTypeFire     PokeType = "fire"
	PokeTypeFlying   PokeType = "flying"
	PokeTypeGhost    PokeType = "ghost"
	PokeTypeGrass    PokeType = "grass"
	PokeTypeGround   PokeType = "ground"
	PokeTypeIce      PokeType = "ice"
	PokeTypeNormal   PokeType = "normal"
	PokeTypePoison   PokeType = "poison"
	PokeTypePsychic  PokeType = "psychic"
	PokeTypeRock     PokeType = "rock"
	PokeTypeSteel    PokeType = "steel"
	PokeTypeWater    PokeType = "water"
)

// Valid indicates whether the value is a known member of the PokeType enum.
func (e PokeType) Valid() bool {
	switch e {
	case PokeTypeBug:
		return true
	case PokeTypeDark:
		return true
	case PokeTypeDragon:
		return true
	case PokeTypeElectric:
		return true
	case PokeTypeFairy:
		return true
	case PokeTypeFighting:
		return true
	case PokeTypeFire:
		return true
	case PokeTypeFlying:
		return true
	case PokeTypeGhost:
		return true
	case PokeTypeGrass:
		return true
	case PokeTypeGround:
		return true
	case PokeTypeIce:
		return true
	case PokeTypeNormal:
		return true
	case PokeTypePoison:
		return true
	case PokeTypePsychic:
		return true
	case PokeTypeRock:
		return true
	case PokeTypeSteel:
		return true
	case PokeTypeWater:
		return true
	default:
		return false
	}
}

// Defines values for ReverseSide.
const (
	Attacker ReverseSide = "attacker"
	Defender ReverseSide = "defender"
)

// Valid indicates whether the value is a known member of the ReverseSide enum.
func (e ReverseSide) Valid() bool {
	switch e {
	case Attacker:
		return true
	case Defender:
		return true
	default:
		return false
	}
}

// Defines values for StatKey.
const (
	StatKeyAtk StatKey = "atk"
	StatKeyDef StatKey = "def"
	StatKeyHp  StatKey = "hp"
	StatKeySpa StatKey = "spa"
	StatKeySpd StatKey = "spd"
	StatKeySpe StatKey = "spe"
)

// Valid indicates whether the value is a known member of the StatKey enum.
func (e StatKey) Valid() bool {
	switch e {
	case StatKeyAtk:
		return true
	case StatKeyDef:
		return true
	case StatKeyHp:
		return true
	case StatKeySpa:
		return true
	case StatKeySpd:
		return true
	case StatKeySpe:
		return true
	default:
		return false
	}
}

// Defines values for StatusCondition.
const (
	StatusConditionBadlyPoison StatusCondition = "badly_poison"
	StatusConditionBurn        StatusCondition = "burn"
	StatusConditionFreeze      StatusCondition = "freeze"
	StatusConditionNone        StatusCondition = "none"
	StatusConditionParalysis   StatusCondition = "paralysis"
	StatusConditionPoison      StatusCondition = "poison"
	StatusConditionSleep       StatusCondition = "sleep"
)

// Valid indicates whether the value is a known member of the StatusCondition enum.
func (e StatusCondition) Valid() bool {
	switch e {
	case StatusConditionBadlyPoison:
		return true
	case StatusConditionBurn:
		return true
	case StatusConditionFreeze:
		return true
	case StatusConditionNone:
		return true
	case StatusConditionParalysis:
		return true
	case StatusConditionPoison:
		return true
	case StatusConditionSleep:
		return true
	default:
		return false
	}
}

// Defines values for Terrain.
const (
	TerrainElectric Terrain = "electric"
	TerrainGrassy   Terrain = "grassy"
	TerrainMisty    Terrain = "misty"
	TerrainNone     Terrain = "none"
	TerrainPsychic  Terrain = "psychic"
)

// Valid indicates whether the value is a known member of the Terrain enum.
func (e Terrain) Valid() bool {
	switch e {
	case TerrainElectric:
		return true
	case TerrainGrassy:
		return true
	case TerrainMisty:
		return true
	case TerrainNone:
		return true
	case TerrainPsychic:
		return true
	default:
		return false
	}
}

// Defines values for Weather.
const (
	WeatherNone Weather = "none"
	WeatherRain Weather = "rain"
	WeatherSand Weather = "sand"
	WeatherSnow Weather = "snow"
	WeatherSun  Weather = "sun"
)

// Valid indicates whether the value is a known member of the Weather enum.
func (e Weather) Valid() bool {
	switch e {
	case WeatherNone:
		return true
	case WeatherRain:
		return true
	case WeatherSand:
		return true
	case WeatherSnow:
		return true
	case WeatherSun:
		return true
	default:
		return false
	}
}

// Ability defines model for Ability.
type Ability struct {
	Id     string `json:"id"`
	NameJa string `json:"nameJa"`
}

// BulkCalcRequest defines model for BulkCalcRequest.
type BulkCalcRequest struct {
	// Attacker 計算に使う個体。SP と性格 ID から実数値を導出する
	Attacker Individual `json:"attacker"`

	// DefenderSpeciesKey {図鑑番号4桁}-{フォルム3桁}
	//
	// Example: 0445-000
	DefenderSpeciesKey SpeciesKey  `json:"defenderSpeciesKey"`
	Field              *FieldState `json:"field,omitempty"`
	Format             Format      `json:"format"`

	// ItemVariants 差し替えて比較する持ち物 ID(省略時は素の1通り)
	ItemVariants *[]*string   `json:"itemVariants,omitempty"`
	MoveId       string       `json:"moveId"`
	Options      *CalcOptions `json:"options,omitempty"`

	// Presets 省略時は技の分類に応じた既定セット
	Presets *[]DefenderPreset `json:"presets,omitempty"`
}

// BulkCalcResult defines model for BulkCalcResult.
type BulkCalcResult struct {
	// DefenderSpeciesKey {図鑑番号4桁}-{フォルム3桁}
	//
	// Example: 0445-000
	DefenderSpeciesKey SpeciesKey    `json:"defenderSpeciesKey"`
	Rows               []BulkCalcRow `json:"rows"`
}

// BulkCalcRow defines model for BulkCalcRow.
type BulkCalcRow struct {
	ItemId *string `json:"itemId,omitempty"`

	// Preset 防御側の代表調整
	Preset DefenderPreset `json:"preset"`

	// PresetLabel 表示名(例 HB特化)
	PresetLabel string     `json:"presetLabel"`
	Result      CalcResult `json:"result"`
}

// CalcOptions defines model for CalcOptions.
type CalcOptions struct {
	// Critical 急所
	Critical *bool `json:"critical,omitempty"`
}

// CalcRequest defines model for CalcRequest.
type CalcRequest struct {
	// Attacker 計算に使う個体。SP と性格 ID から実数値を導出する
	Attacker Individual `json:"attacker"`

	// Defender 計算に使う個体。SP と性格 ID から実数値を導出する
	Defender Individual  `json:"defender"`
	Field    *FieldState `json:"field,omitempty"`
	Format   Format      `json:"format"`

	// MoveId 使用する技(attacker.moveId より優先)
	MoveId  string       `json:"moveId"`
	Options *CalcOptions `json:"options,omitempty"`
}

// CalcResult defines model for CalcResult.
type CalcResult struct {
	DefenderHP int `json:"defenderHP"`

	// Effectiveness タイプ相性(0, 0.25, 0.5, 1, 2, 4)
	Effectiveness float32 `json:"effectiveness"`

	// Ko 確定数/乱数n発
	Ko         KOChance `json:"ko"`
	MaxDamage  int      `json:"maxDamage"`
	MaxPercent float32  `json:"maxPercent"`
	MinDamage  int      `json:"minDamage"`
	MinPercent float32  `json:"minPercent"`

	// Rolls 16 段階の乱数ダメージ(非減少)
	Rolls []int `json:"rolls"`

	// Stab タイプ一致
	Stab bool `json:"stab"`
}

// DefenderPreset 防御側の代表調整
type DefenderPreset string

// Error defines model for Error.
type Error struct {
	// Code Example: invalid_request
	Code    string `json:"code"`
	Message string `json:"message"`
}

// FieldState defines model for FieldState.
type FieldState struct {
	AttackerScreens *Screens `json:"attackerScreens,omitempty"`
	DefenderScreens *Screens `json:"defenderScreens,omitempty"`
	Terrain         *Terrain `json:"terrain,omitempty"`
	Weather         *Weather `json:"weather,omitempty"`
}

// Format defines model for Format.
type Format string

// Individual 計算に使う個体。SP と性格 ID から実数値を導出する
type Individual struct {
	AbilityId *string `json:"abilityId,omitempty"`
	ItemId    *string `json:"itemId,omitempty"`
	Level     *int    `json:"level,omitempty"`

	// MoveId 攻撃側で使う技
	MoveId   *string `json:"moveId,omitempty"`
	NatureId string  `json:"natureId"`

	// Ranks ランク補正(-6..+6)。HP は持たない
	Ranks *RankBlock `json:"ranks,omitempty"`

	// Sp 能力ポイント。各 0..32、合計 <= 66
	Sp StatBlock `json:"sp"`

	// SpeciesKey {図鑑番号4桁}-{フォルム3桁}
	//
	// Example: 0445-000
	SpeciesKey SpeciesKey       `json:"speciesKey"`
	Status     *StatusCondition `json:"status,omitempty"`
	TeraType   *PokeType        `json:"teraType,omitempty"`
}

// Item defines model for Item.
type Item struct {
	Id     string `json:"id"`
	NameJa string `json:"nameJa"`
}

// KOChance 確定数/乱数n発
type KOChance struct {
	// ChancePercent guaranteed が false のとき、hits 回で倒せる確率(%)
	ChancePercent *float32 `json:"chancePercent,omitempty"`

	// Guaranteed 最小ダメージでも hits 回で倒せるなら true(確定n発)
	Guaranteed bool `json:"guaranteed"`

	// Hits 最大ダメージで倒すのに必要な攻撃回数
	Hits int `json:"hits"`
}

// Move defines model for Move.
type Move struct {
	Category MoveCategory `json:"category"`
	Id       string       `json:"id"`
	NameJa   string       `json:"nameJa"`

	// Power 威力(0 は変化技/固定ダメージ)
	Power    int      `json:"power"`
	Priority *int     `json:"priority,omitempty"`
	Type     PokeType `json:"type"`
}

// MoveCategory defines model for MoveCategory.
type MoveCategory string

// Nature defines model for Nature.
type Nature struct {
	// Id Example: adamant
	Id string `json:"id"`

	// Minus 下降補正(-10%)を受ける能力。無補正性格は null
	Minus *StatKey `json:"minus,omitempty"`

	// NameJa Example: いじっぱり
	NameJa string `json:"nameJa"`

	// Plus 上昇補正(+10%)を受ける能力。無補正性格は null
	Plus *StatKey `json:"plus,omitempty"`
}

// Observation defines model for Observation.
type Observation struct {
	Note *string `json:"note,omitempty"`

	// ObservedPercent ゲーム内表示に合わせた HP 減少割合(%)
	ObservedPercent float32 `json:"observedPercent"`
}

// PokeType defines model for PokeType.
type PokeType string

// RankBlock ランク補正(-6..+6)。HP は持たない
type RankBlock struct {
	Atk *int `json:"atk,omitempty"`
	Def *int `json:"def,omitempty"`
	Spa *int `json:"spa,omitempty"`
	Spd *int `json:"spd,omitempty"`
	Spe *int `json:"spe,omitempty"`
}

// ReverseCandidate defines model for ReverseCandidate.
type ReverseCandidate struct {
	ItemId *string `json:"itemId,omitempty"`

	// MatchScore 観測との一致度(0..1、高いほど一致)
	MatchScore float32 `json:"matchScore"`
	NatureId   *string `json:"natureId,omitempty"`

	// PresetLabel 型の名前(例 HB特化)
	PresetLabel string `json:"presetLabel"`

	// RangePercent この候補での想定ダメージ幅 [min, max]
	RangePercent *[]float32 `json:"rangePercent,omitempty"`

	// Sp 6ステータスの値(種族値・実数値・SPなどに共用)
	Sp StatBlock `json:"sp"`
}

// ReverseRequest defines model for ReverseRequest.
type ReverseRequest struct {
	// Attacker 計算に使う個体。SP と性格 ID から実数値を導出する
	Attacker Individual `json:"attacker"`

	// DefenderSpeciesKey {図鑑番号4桁}-{フォルム3桁}
	//
	// Example: 0445-000
	DefenderSpeciesKey SpeciesKey    `json:"defenderSpeciesKey"`
	Field              *FieldState   `json:"field,omitempty"`
	Format             Format        `json:"format"`
	MoveId             string        `json:"moveId"`
	Observations       []Observation `json:"observations"`
	Options            *CalcOptions  `json:"options,omitempty"`

	// Side どちら側の調整を逆算するか(defender=与ダメ観測 / attacker=被ダメ観測)
	Side ReverseSide `json:"side"`
}

// ReverseResult defines model for ReverseResult.
type ReverseResult struct {
	// Candidates 一致度の高い順
	Candidates []ReverseCandidate `json:"candidates"`
}

// ReverseSide どちら側の調整を逆算するか(defender=与ダメ観測 / attacker=被ダメ観測)
type ReverseSide string

// Screens defines model for Screens.
type Screens struct {
	AuroraVeil  *bool `json:"auroraVeil,omitempty"`
	LightScreen *bool `json:"lightScreen,omitempty"`
	Reflect     *bool `json:"reflect,omitempty"`
}

// SpeciesDetail defines model for SpeciesDetail.
type SpeciesDetail struct {
	Abilities []Ability `json:"abilities"`

	// BaseStats 6ステータスの値(種族値・実数値・SPなどに共用)
	BaseStats StatBlock `json:"baseStats"`
	DexNo     int       `json:"dexNo"`

	// Form フォルム番号
	Form int `json:"form"`

	// Key {図鑑番号4桁}-{フォルム3桁}
	//
	// Example: 0445-000
	Key SpeciesKey `json:"key"`

	// Learnset 覚える技の ID 一覧
	Learnset *[]string  `json:"learnset,omitempty"`
	NameJa   string     `json:"nameJa"`
	Types    []PokeType `json:"types"`
}

// SpeciesKey {図鑑番号4桁}-{フォルム3桁}
//
// Example: 0445-000
type SpeciesKey = string

// SpeciesSummary defines model for SpeciesSummary.
type SpeciesSummary struct {
	DexNo int `json:"dexNo"`

	// Form フォルム番号
	Form int `json:"form"`

	// Key {図鑑番号4桁}-{フォルム3桁}
	//
	// Example: 0445-000
	Key    SpeciesKey `json:"key"`
	NameJa string     `json:"nameJa"`
	Types  []PokeType `json:"types"`
}

// StatBlock 6ステータスの値(種族値・実数値・SPなどに共用)
type StatBlock struct {
	Atk int `json:"atk"`
	Def int `json:"def"`
	Hp  int `json:"hp"`
	Spa int `json:"spa"`
	Spd int `json:"spd"`
	Spe int `json:"spe"`
}

// StatKey defines model for StatKey.
type StatKey string

// StatusCondition defines model for StatusCondition.
type StatusCondition string

// Terrain defines model for Terrain.
type Terrain string

// Weather defines model for Weather.
type Weather string

// DeviceId defines model for DeviceId.
type DeviceId = string

// SessionId defines model for SessionId.
type SessionId = string

// CalcDamageParams defines parameters for CalcDamage.
type CalcDamageParams struct {
	// XDeviceId クライアント生成の端末 UUID
	XDeviceId DeviceId `json:"X-Device-Id"`

	// XSessionId セッション UUID
	XSessionId SessionId `json:"X-Session-Id"`
}

// CalcBulkParams defines parameters for CalcBulk.
type CalcBulkParams struct {
	// XDeviceId クライアント生成の端末 UUID
	XDeviceId DeviceId `json:"X-Device-Id"`

	// XSessionId セッション UUID
	XSessionId SessionId `json:"X-Session-Id"`
}

// CalcReverseParams defines parameters for CalcReverse.
type CalcReverseParams struct {
	// XDeviceId クライアント生成の端末 UUID
	XDeviceId DeviceId `json:"X-Device-Id"`

	// XSessionId セッション UUID
	XSessionId SessionId `json:"X-Session-Id"`
}

// SearchItemsParams defines parameters for SearchItems.
type SearchItemsParams struct {
	Q     *string `form:"q,omitempty" json:"q,omitempty"`
	Limit *int    `form:"limit,omitempty" json:"limit,omitempty"`

	// XDeviceId クライアント生成の端末 UUID
	XDeviceId DeviceId `json:"X-Device-Id"`

	// XSessionId セッション UUID
	XSessionId SessionId `json:"X-Session-Id"`
}

// SearchMovesParams defines parameters for SearchMoves.
type SearchMovesParams struct {
	Q     *string `form:"q,omitempty" json:"q,omitempty"`
	Limit *int    `form:"limit,omitempty" json:"limit,omitempty"`

	// XDeviceId クライアント生成の端末 UUID
	XDeviceId DeviceId `json:"X-Device-Id"`

	// XSessionId セッション UUID
	XSessionId SessionId `json:"X-Session-Id"`
}

// ListNaturesParams defines parameters for ListNatures.
type ListNaturesParams struct {
	// XDeviceId クライアント生成の端末 UUID
	XDeviceId DeviceId `json:"X-Device-Id"`

	// XSessionId セッション UUID
	XSessionId SessionId `json:"X-Session-Id"`
}

// SearchSpeciesParams defines parameters for SearchSpecies.
type SearchSpeciesParams struct {
	// Q 日本語名の前方一致(空なら全件・limit まで)
	Q      *string `form:"q,omitempty" json:"q,omitempty"`
	Format *Format `form:"format,omitempty" json:"format,omitempty"`
	Limit  *int    `form:"limit,omitempty" json:"limit,omitempty"`

	// XDeviceId クライアント生成の端末 UUID
	XDeviceId DeviceId `json:"X-Device-Id"`

	// XSessionId セッション UUID
	XSessionId SessionId `json:"X-Session-Id"`
}

// GetSpeciesParams defines parameters for GetSpecies.
type GetSpeciesParams struct {
	// XDeviceId クライアント生成の端末 UUID
	XDeviceId DeviceId `json:"X-Device-Id"`

	// XSessionId セッション UUID
	XSessionId SessionId `json:"X-Session-Id"`
}

// CalcDamageJSONRequestBody defines body for CalcDamage for application/json ContentType.
type CalcDamageJSONRequestBody = CalcRequest

// CalcBulkJSONRequestBody defines body for CalcBulk for application/json ContentType.
type CalcBulkJSONRequestBody = BulkCalcRequest

// CalcReverseJSONRequestBody defines body for CalcReverse for application/json ContentType.
type CalcReverseJSONRequestBody = ReverseRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// CalcDamage 1 vs 1 のダメージ計算
	// (POST /api/calc)
	CalcDamage(ctx echo.Context, params CalcDamageParams) error
	// CalcBulk 防御側の代表調整すべてに対する一括計算
	// (POST /api/calc/bulk)
	CalcBulk(ctx echo.Context, params CalcBulkParams) error
	// CalcReverse 観測ダメージから相手の調整候補を逆算
	// (POST /api/calc/reverse)
	CalcReverse(ctx echo.Context, params CalcReverseParams) error
	// SearchItems 持ち物を日本語名で前方一致検索
	// (GET /api/pokedex/items)
	SearchItems(ctx echo.Context, params SearchItemsParams) error
	// SearchMoves 技を日本語名で前方一致検索
	// (GET /api/pokedex/moves)
	SearchMoves(ctx echo.Context, params SearchMovesParams) error
	// ListNatures 性格の一覧(補正する能力)
	// (GET /api/pokedex/natures)
	ListNatures(ctx echo.Context, params ListNaturesParams) error
	// SearchSpecies ポケモンを日本語名で前方一致検索
	// (GET /api/pokedex/species)
	SearchSpecies(ctx echo.Context, params SearchSpeciesParams) error
	// GetSpecies 種族の詳細(タイプ・種族値・特性・覚える技)
	// (GET /api/pokedex/species/{key})
	GetSpecies(ctx echo.Context, key SpeciesKey, params GetSpeciesParams) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// CalcDamage converts echo context to params.
func (w *ServerInterfaceWrapper) CalcDamage(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params CalcDamageParams

	headers := ctx.Request().Header
	// ------------- Required header parameter "X-Device-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Device-Id")]; found {
		var XDeviceId DeviceId
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-Device-Id, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Device-Id", valueList[0], &XDeviceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-Device-Id: %s", err))
		}

		params.XDeviceId = XDeviceId
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter X-Device-Id is required, but not found"))
	}
	// ------------- Required header parameter "X-Session-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Session-Id")]; found {
		var XSessionId SessionId
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-Session-Id, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Session-Id", valueList[0], &XSessionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-Session-Id: %s", err))
		}

		params.XSessionId = XSessionId
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter X-Session-Id is required, but not found"))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CalcDamage(ctx, params)
	return err
}

// CalcBulk converts echo context to params.
func (w *ServerInterfaceWrapper) CalcBulk(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params CalcBulkParams

	headers := ctx.Request().Header
	// ------------- Required header parameter "X-Device-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Device-Id")]; found {
		var XDeviceId DeviceId
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-Device-Id, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Device-Id", valueList[0], &XDeviceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-Device-Id: %s", err))
		}

		params.XDeviceId = XDeviceId
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter X-Device-Id is required, but not found"))
	}
	// ------------- Required header parameter "X-Session-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Session-Id")]; found {
		var XSessionId SessionId
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-Session-Id, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Session-Id", valueList[0], &XSessionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-Session-Id: %s", err))
		}

		params.XSessionId = XSessionId
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter X-Session-Id is required, but not found"))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CalcBulk(ctx, params)
	return err
}

// CalcReverse converts echo context to params.
func (w *ServerInterfaceWrapper) CalcReverse(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params CalcReverseParams

	headers := ctx.Request().Header
	// ------------- Required header parameter "X-Device-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Device-Id")]; found {
		var XDeviceId DeviceId
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-Device-Id, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Device-Id", valueList[0], &XDeviceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-Device-Id: %s", err))
		}

		params.XDeviceId = XDeviceId
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter X-Device-Id is required, but not found"))
	}
	// ------------- Required header parameter "X-Session-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Session-Id")]; found {
		var XSessionId SessionId
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-Session-Id, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Session-Id", valueList[0], &XSessionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-Session-Id: %s", err))
		}

		params.XSessionId = XSessionId
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter X-Session-Id is required, but not found"))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CalcReverse(ctx, params)
	return err
}

// SearchItems converts echo context to params.
func (w *ServerInterfaceWrapper) SearchItems(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params SearchItemsParams
	// ------------- Optional query parameter "q" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "q", ctx.QueryParams(), &params.Q, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter q: %s", err))
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", ctx.QueryParams(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	headers := ctx.Request().Header
	// ------------- Required header parameter "X-Device-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Device-Id")]; found {
		var XDeviceId DeviceId
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-Device-Id, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Device-Id", valueList[0], &XDeviceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-Device-Id: %s", err))
		}

		params.XDeviceId = XDeviceId
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter X-Device-Id is required, but not found"))
	}
	// ------------- Required header parameter "X-Session-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Session-Id")]; found {
		var XSessionId SessionId
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-Session-Id, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Session-Id", valueList[0], &XSessionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-Session-Id: %s", err))
		}

		params.XSessionId = XSessionId
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter X-Session-Id is required, but not found"))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.SearchItems(ctx, params)
	return err
}

// SearchMoves converts echo context to params.
func (w *ServerInterfaceWrapper) SearchMoves(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params SearchMovesParams
	// ------------- Optional query parameter "q" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "q", ctx.QueryParams(), &params.Q, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter q: %s", err))
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", ctx.QueryParams(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	headers := ctx.Request().Header
	// ------------- Required header parameter "X-Device-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Device-Id")]; found {
		var XDeviceId DeviceId
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-Device-Id, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Device-Id", valueList[0], &XDeviceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-Device-Id: %s", err))
		}

		params.XDeviceId = XDeviceId
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter X-Device-Id is required, but not found"))
	}
	// ------------- Required header parameter "X-Session-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Session-Id")]; found {
		var XSessionId SessionId
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-Session-Id, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Session-Id", valueList[0], &XSessionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-Session-Id: %s", err))
		}

		params.XSessionId = XSessionId
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter X-Session-Id is required, but not found"))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.SearchMoves(ctx, params)
	return err
}

// ListNatures converts echo context to params.
func (w *ServerInterfaceWrapper) ListNatures(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListNaturesParams

	headers := ctx.Request().Header
	// ------------- Required header parameter "X-Device-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Device-Id")]; found {
		var XDeviceId DeviceId
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-Device-Id, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Device-Id", valueList[0], &XDeviceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-Device-Id: %s", err))
		}

		params.XDeviceId = XDeviceId
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter X-Device-Id is required, but not found"))
	}
	// ------------- Required header parameter "X-Session-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Session-Id")]; found {
		var XSessionId SessionId
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-Session-Id, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Session-Id", valueList[0], &XSessionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-Session-Id: %s", err))
		}

		params.XSessionId = XSessionId
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter X-Session-Id is required, but not found"))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListNatures(ctx, params)
	return err
}

// SearchSpecies converts echo context to params.
func (w *ServerInterfaceWrapper) SearchSpecies(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params SearchSpeciesParams
	// ------------- Optional query parameter "q" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "q", ctx.QueryParams(), &params.Q, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter q: %s", err))
	}

	// ------------- Optional query parameter "format" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "format", ctx.QueryParams(), &params.Format, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter format: %s", err))
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", ctx.QueryParams(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	headers := ctx.Request().Header
	// ------------- Required header parameter "X-Device-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Device-Id")]; found {
		var XDeviceId DeviceId
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-Device-Id, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Device-Id", valueList[0], &XDeviceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-Device-Id: %s", err))
		}

		params.XDeviceId = XDeviceId
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter X-Device-Id is required, but not found"))
	}
	// ------------- Required header parameter "X-Session-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Session-Id")]; found {
		var XSessionId SessionId
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-Session-Id, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Session-Id", valueList[0], &XSessionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-Session-Id: %s", err))
		}

		params.XSessionId = XSessionId
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter X-Session-Id is required, but not found"))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.SearchSpecies(ctx, params)
	return err
}

// GetSpecies converts echo context to params.
func (w *ServerInterfaceWrapper) GetSpecies(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "key" -------------
	var key SpeciesKey

	err = runtime.BindStyledParameterWithOptions("simple", "key", ctx.Param("key"), &key, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter key: %s", err))
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetSpeciesParams

	headers := ctx.Request().Header
	// ------------- Required header parameter "X-Device-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Device-Id")]; found {
		var XDeviceId DeviceId
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-Device-Id, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Device-Id", valueList[0], &XDeviceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-Device-Id: %s", err))
		}

		params.XDeviceId = XDeviceId
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter X-Device-Id is required, but not found"))
	}
	// ------------- Required header parameter "X-Session-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Session-Id")]; found {
		var XSessionId SessionId
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-Session-Id, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Session-Id", valueList[0], &XSessionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-Session-Id: %s", err))
		}

		params.XSessionId = XSessionId
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter X-Session-Id is required, but not found"))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetSpecies(ctx, key, params)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlersOptions configures RegisterHandlersWithOptions.
type RegisterHandlersOptions struct {
	// BaseURL is prepended to every registered path so the API can be served
	// under a prefix.
	BaseURL string
	// OperationMiddlewares lets the caller attach per-operation middleware at
	// registration time. The map key is the OpenAPI `operationId` value as it
	// appears in the spec (the raw, un-normalized form). Operations that have
	// no entry are registered with no extra middleware. A nil map disables
	// per-operation middleware entirely.
	OperationMiddlewares map[string][]echo.MiddlewareFunc
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{})
}

// RegisterHandlersWithBaseURL registers handlers and prepends BaseURL to the
// paths so the API can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{BaseURL: baseURL})
}

// RegisterHandlersWithOptions registers handlers using the supplied options,
// including any per-operation middleware.
func RegisterHandlersWithOptions(router EchoRouter, si ServerInterface, options RegisterHandlersOptions) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(options.BaseURL+"/api/pokedex/species", wrapper.SearchSpecies, options.OperationMiddlewares["searchSpecies"]...)
	router.GET(options.BaseURL+"/api/pokedex/species/:key", wrapper.GetSpecies, options.OperationMiddlewares["getSpecies"]...)
	router.GET(options.BaseURL+"/api/pokedex/moves", wrapper.SearchMoves, options.OperationMiddlewares["searchMoves"]...)
	router.GET(options.BaseURL+"/api/pokedex/items", wrapper.SearchItems, options.OperationMiddlewares["searchItems"]...)
	router.GET(options.BaseURL+"/api/pokedex/natures", wrapper.ListNatures, options.OperationMiddlewares["listNatures"]...)
	router.POST(options.BaseURL+"/api/calc", wrapper.CalcDamage, options.OperationMiddlewares["calcDamage"]...)
	router.POST(options.BaseURL+"/api/calc/bulk", wrapper.CalcBulk, options.OperationMiddlewares["calcBulk"]...)
	router.POST(options.BaseURL+"/api/calc/reverse", wrapper.CalcReverse, options.OperationMiddlewares["calcReverse"]...)

}

type ErrorJSONResponse Error

type CalcDamageRequestObject struct {
	Params CalcDamageParams
	Body   *CalcDamageJSONRequestBody
}

type CalcDamageResponseObject interface {
	VisitCalcDamageResponse(w http.ResponseWriter) error
}

type CalcDamage200JSONResponse CalcResult

func (response CalcDamage200JSONResponse) VisitCalcDamageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type CalcDamage400JSONResponse struct{ ErrorJSONResponse }

func (response CalcDamage400JSONResponse) VisitCalcDamageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CalcDamagedefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response CalcDamagedefaultJSONResponse) VisitCalcDamageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type CalcBulkRequestObject struct {
	Params CalcBulkParams
	Body   *CalcBulkJSONRequestBody
}

type CalcBulkResponseObject interface {
	VisitCalcBulkResponse(w http.ResponseWriter) error
}

type CalcBulk200JSONResponse BulkCalcResult

func (response CalcBulk200JSONResponse) VisitCalcBulkResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type CalcBulk400JSONResponse struct{ ErrorJSONResponse }

func (response CalcBulk400JSONResponse) VisitCalcBulkResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CalcBulkdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response CalcBulkdefaultJSONResponse) VisitCalcBulkResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type CalcReverseRequestObject struct {
	Params CalcReverseParams
	Body   *CalcReverseJSONRequestBody
}

type CalcReverseResponseObject interface {
	VisitCalcReverseResponse(w http.ResponseWriter) error
}

type CalcReverse200JSONResponse ReverseResult

func (response CalcReverse200JSONResponse) VisitCalcReverseResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type CalcReverse400JSONResponse struct{ ErrorJSONResponse }

func (response CalcReverse400JSONResponse) VisitCalcReverseResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CalcReversedefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response CalcReversedefaultJSONResponse) VisitCalcReverseResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type SearchItemsRequestObject struct {
	Params SearchItemsParams
}

type SearchItemsResponseObject interface {
	VisitSearchItemsResponse(w http.ResponseWriter) error
}

type SearchItems200JSONResponse []Item

func (response SearchItems200JSONResponse) VisitSearchItemsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type SearchItemsdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response SearchItemsdefaultJSONResponse) VisitSearchItemsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type SearchMovesRequestObject struct {
	Params SearchMovesParams
}

type SearchMovesResponseObject interface {
	VisitSearchMovesResponse(w http.ResponseWriter) error
}

type SearchMoves200JSONResponse []Move

func (response SearchMoves200JSONResponse) VisitSearchMovesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type SearchMovesdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response SearchMovesdefaultJSONResponse) VisitSearchMovesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type ListNaturesRequestObject struct {
	Params ListNaturesParams
}

type ListNaturesResponseObject interface {
	VisitListNaturesResponse(w http.ResponseWriter) error
}

type ListNatures200JSONResponse []Nature

func (response ListNatures200JSONResponse) VisitListNaturesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListNaturesdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response ListNaturesdefaultJSONResponse) VisitListNaturesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type SearchSpeciesRequestObject struct {
	Params SearchSpeciesParams
}

type SearchSpeciesResponseObject interface {
	VisitSearchSpeciesResponse(w http.ResponseWriter) error
}

type SearchSpecies200JSONResponse []SpeciesSummary

func (response SearchSpecies200JSONResponse) VisitSearchSpeciesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type SearchSpeciesdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response SearchSpeciesdefaultJSONResponse) VisitSearchSpeciesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetSpeciesRequestObject struct {
	Key    SpeciesKey `json:"key"`
	Params GetSpeciesParams
}

type GetSpeciesResponseObject interface {
	VisitGetSpeciesResponse(w http.ResponseWriter) error
}

type GetSpecies200JSONResponse SpeciesDetail

func (response GetSpecies200JSONResponse) VisitGetSpeciesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetSpecies404JSONResponse struct{ ErrorJSONResponse }

func (response GetSpecies404JSONResponse) VisitGetSpeciesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetSpeciesdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response GetSpeciesdefaultJSONResponse) VisitGetSpeciesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// CalcDamage 1 vs 1 のダメージ計算
	// (POST /api/calc)
	CalcDamage(ctx context.Context, request CalcDamageRequestObject) (CalcDamageResponseObject, error)
	// CalcBulk 防御側の代表調整すべてに対する一括計算
	// (POST /api/calc/bulk)
	CalcBulk(ctx context.Context, request CalcBulkRequestObject) (CalcBulkResponseObject, error)
	// CalcReverse 観測ダメージから相手の調整候補を逆算
	// (POST /api/calc/reverse)
	CalcReverse(ctx context.Context, request CalcReverseRequestObject) (CalcReverseResponseObject, error)
	// SearchItems 持ち物を日本語名で前方一致検索
	// (GET /api/pokedex/items)
	SearchItems(ctx context.Context, request SearchItemsRequestObject) (SearchItemsResponseObject, error)
	// SearchMoves 技を日本語名で前方一致検索
	// (GET /api/pokedex/moves)
	SearchMoves(ctx context.Context, request SearchMovesRequestObject) (SearchMovesResponseObject, error)
	// ListNatures 性格の一覧(補正する能力)
	// (GET /api/pokedex/natures)
	ListNatures(ctx context.Context, request ListNaturesRequestObject) (ListNaturesResponseObject, error)
	// SearchSpecies ポケモンを日本語名で前方一致検索
	// (GET /api/pokedex/species)
	SearchSpecies(ctx context.Context, request SearchSpeciesRequestObject) (SearchSpeciesResponseObject, error)
	// GetSpecies 種族の詳細(タイプ・種族値・特性・覚える技)
	// (GET /api/pokedex/species/{key})
	GetSpecies(ctx context.Context, request GetSpeciesRequestObject) (GetSpeciesResponseObject, error)
}

type StrictHandlerFunc func(ctx echo.Context, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// CalcDamage operation middleware
func (sh *strictHandler) CalcDamage(ctx echo.Context, params CalcDamageParams) error {
	var request CalcDamageRequestObject

	request.Params = params

	var body CalcDamageJSONRequestBody
	var err error
	if binder, ok := ctx.Echo().Binder.(*echo.DefaultBinder); ok {
		// Bind only the request body, so that path and query parameters
		// are not also bound into the body struct.
		err = binder.BindBody(ctx, &body)
	} else {
		// A custom binder is installed on the Echo instance; defer to it
		// entirely, since echo.Binder does not expose body-only binding.
		err = ctx.Bind(&body)
	}
	if err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CalcDamage(ctx.Request().Context(), request.(CalcDamageRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CalcDamage")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(CalcDamageResponseObject); ok {
		return validResponse.VisitCalcDamageResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// CalcBulk operation middleware
func (sh *strictHandler) CalcBulk(ctx echo.Context, params CalcBulkParams) error {
	var request CalcBulkRequestObject

	request.Params = params

	var body CalcBulkJSONRequestBody
	var err error
	if binder, ok := ctx.Echo().Binder.(*echo.DefaultBinder); ok {
		// Bind only the request body, so that path and query parameters
		// are not also bound into the body struct.
		err = binder.BindBody(ctx, &body)
	} else {
		// A custom binder is installed on the Echo instance; defer to it
		// entirely, since echo.Binder does not expose body-only binding.
		err = ctx.Bind(&body)
	}
	if err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CalcBulk(ctx.Request().Context(), request.(CalcBulkRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CalcBulk")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(CalcBulkResponseObject); ok {
		return validResponse.VisitCalcBulkResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// CalcReverse operation middleware
func (sh *strictHandler) CalcReverse(ctx echo.Context, params CalcReverseParams) error {
	var request CalcReverseRequestObject

	request.Params = params

	var body CalcReverseJSONRequestBody
	var err error
	if binder, ok := ctx.Echo().Binder.(*echo.DefaultBinder); ok {
		// Bind only the request body, so that path and query parameters
		// are not also bound into the body struct.
		err = binder.BindBody(ctx, &body)
	} else {
		// A custom binder is installed on the Echo instance; defer to it
		// entirely, since echo.Binder does not expose body-only binding.
		err = ctx.Bind(&body)
	}
	if err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CalcReverse(ctx.Request().Context(), request.(CalcReverseRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CalcReverse")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(CalcReverseResponseObject); ok {
		return validResponse.VisitCalcReverseResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// SearchItems operation middleware
func (sh *strictHandler) SearchItems(ctx echo.Context, params SearchItemsParams) error {
	var request SearchItemsRequestObject

	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.SearchItems(ctx.Request().Context(), request.(SearchItemsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SearchItems")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(SearchItemsResponseObject); ok {
		return validResponse.VisitSearchItemsResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// SearchMoves operation middleware
func (sh *strictHandler) SearchMoves(ctx echo.Context, params SearchMovesParams) error {
	var request SearchMovesRequestObject

	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.SearchMoves(ctx.Request().Context(), request.(SearchMovesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SearchMoves")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(SearchMovesResponseObject); ok {
		return validResponse.VisitSearchMovesResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// ListNatures operation middleware
func (sh *strictHandler) ListNatures(ctx echo.Context, params ListNaturesParams) error {
	var request ListNaturesRequestObject

	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListNatures(ctx.Request().Context(), request.(ListNaturesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListNatures")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(ListNaturesResponseObject); ok {
		return validResponse.VisitListNaturesResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// SearchSpecies operation middleware
func (sh *strictHandler) SearchSpecies(ctx echo.Context, params SearchSpeciesParams) error {
	var request SearchSpeciesRequestObject

	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.SearchSpecies(ctx.Request().Context(), request.(SearchSpeciesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SearchSpecies")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(SearchSpeciesResponseObject); ok {
		return validResponse.VisitSearchSpeciesResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetSpecies operation middleware
func (sh *strictHandler) GetSpecies(ctx echo.Context, key SpeciesKey, params GetSpeciesParams) error {
	var request GetSpeciesRequestObject

	request.Key = key
	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetSpecies(ctx.Request().Context(), request.(GetSpeciesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetSpecies")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetSpeciesResponseObject); ok {
		return validResponse.VisitGetSpeciesResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7HtrUxtXmv9X6er/pErUNEj4QtXfVXkRm8yYHSehQjKzWzGbOkgH1EOrW+lugVmXqvoCNhc7Jg4E2xBs",
	"bGJusYSDvcHgmBf7UQ7dLb7F1rlIarWOkLAdpmZ339hN97k9z3me33PVdTGpZbKaClXTEC9cF7NABxlo",
	"Qp381Q1H5CTsSeHnFDSSupw1ZU0VL4jIKSJ3AzmryHmM3B3kTgZzD/3JWWQXgq2iv7QlfPllT7coiTIe",
	"nYYgBXVRElWQgeIF8V/b6crtPSlREnX4TU7WYUq8YOo5KIlGMg0zAO9pjmXxcMPUZXVIzOclsQ8ahqyp",
	"/CPtI9dFzq/IXUPuTpMDsIVOeoI8HmxkNdWAhEMf67qm44ekpppQNfEjyGYVOQnwseJ/N/DZrodW/IMO",
	"B8UL4v+LVxkfp1+NOF2N7BKlbR2z231NmMCG49U+GpAV2RzDj1ldy0LdlOnB5BTn+JT+f2nA2yoXvsLT",
	"K4P7pfJgbeDvMGnidS7mlOFLQEl+Dr/JQcOs3x+YJkgOQ70ZyT1qSh6RUzmgiITqQaimoN6XhUkZGn+B",
	"Y83mh0bmJXFQhkqq2ZQ/4UF9JjAhmaLpGWA2nUNH5SVRNmHmr0CXAdOY2ovyfi0ge8FfPED2JLKf+sW5",
	"0msX2feRM+PfspG9EkxtCD3dsWDJDuZ/8u87yC4GLx4hu9B5ZD1AznSbSLcga6s5RQEDCizLZd11shdA",
	"1wGhP6ONMHWtG6qRIxrNCMWX+hkbmpfErA4NyCM0TIA/bSG74E3eOFpZRvaWd7CE7HvIfugvPPYKD5he",
	"upNhyo47QjcTgl6ydz2ZEVFlFyhVRY4rRxXmHC/ORk7hSPO7yqWujVKtbIX+ymG00abEcwklux1LpjbK",
	"QQwTZnpSLYkdlYqT3yOddwUMQKVeokor68Hqnjd7O3b4Zka4fDGYeuXd+qFN5OyvV66pmSizC42yjRFQ",
	"e6LKujzWhfWijnVJXTblJGBEDQJyuEGgGDAK5L71kz9lVWka0DQFApUckLvn7wSwJ5t1CrBaRa5ahh3+",
	"dhDMrTMEnbZiZbI76AQBOZPImfbGN72JSa6svA3unQBhjseVVjDlcm8Ir2XVhENQx3Ph4CBMmvIIVKFh",
	"8NydA+x+uQvB4q5vrcUSkpDoOHMe/3teEjol4YwknAtxRM1lBujCw1ozZvzls0tpoCbJRWbAtW6QAUOQ",
	"f8oMuNYL9SRzfer2ysjqsbNl9bjZuqYoHNI7uwS/8PLowbfILhy+eu7PbyPXQu4Kcl8jZzd29OOyv7vo",
	"bX9XY0u5R++hXzu7yFFCf0UNq2GCgWPu4HDXKt18wVfrsCRRgsJsCTO4hh81rJXC0hIVDXY6crE8IYzg",
	"cB0VR/d+8d6sePYLzM79J6WV9dLmgT+PyYFqLoPPrWoqPl46i//BW6VT5OnrAU0zTPI3e+znqGDFSY6g",
	"ppYiYgGvgUxWoZczAhQ59bXOQI+zVgYaRq04NfBgyerV8TzGhBCrIbz2JXUIm8NHeVjYhz3xTBPqOpDV",
	"ZjO+YMPykjgKgZlujuZ/Y8O4VuZPFaSumC7RkNUhBYYEoPIipeUGlDA7q1cTshn1xn19MigsIHvr8LcD",
	"ZN/wrJnD375HltPXKyB73bfW/EevhZ5uAdkzyJnyCg/9+W3PWkXOXW/7W+/mHjUAohS9JRr+tOi2nMDD",
	"UeAIrDXn5xMSD0MamC1/bt+/6xKdWqMk+9PY7DfdWAVmTm/kw+tAHW4qUJ8DdfiioiWH8QwjS9ikKJ8N",
	"ihe+aiKJJjDZxP6o31Jyf/OmF5H7I8E7HO8jy/Fmx4VER8fZM8iyvdnJ0vqkcDWXSJxNfih0ddHd385d",
	"Nkxg5pprDhl1SVNTMjkl1SDwBeFaq0T3asOQzMj3R28niihG2Meu3BPhMQ9dsDU59bi8YrnrA7bHe17h",
	"gT+/HacmUw3u79XpU5JMDpnk2jWGckAHqglhSkD2LYF4uAKyC8heR/ZtZNlp2TQEb3EZ2WuedRfZi8iZ",
	"CR7vBd/ejH3A9UWqK3J0aMnytu+ETTuy15DjCLxdkL2JnCkB31uMkooJbOOYZEnE8/nbra5FtiPr3yck",
	"bnkHE6WnNrI3mXIvLvvz22I9KkSujOxWQynv4j7RRjhWKAlMOKTpTdUHz75UHouR7oRSJolZbRTq9Uzx",
	"1m1vejGWEJBd9FanvFs/+NNW3FvEDA6zqk3koWNWlzWdpacqQMrFUZMpbWuqeoxSsKWkKuvKtDXi+qUQ",
	"j8vmLpseM0hAxzCMPlFU4pm+TwkaNNL2qoMDUiADVL5jI6s5o3XcwuBH0LIOqg93Z47u3y49WfKfPYm1",
	"dyY+aMNW9M4Csr9DzgwDcssJxlfoGGp8kV0UMPzV2agasalSguxxkuR5guznyJnmUZRV3hdB0/69m4yg",
	"P747QSeE1M8GDKiPAHqY6AWrmgn56TYyC6YaYilyfsGq4z7ybkzQ1AeGmNlJ5NzBiGY/FC73CjSO8aZ+",
	"8WYnuQgaoSW6K4+eihqF5F3FPiBm1aCsQ1ESR4FJQluowKSpy0mMXzogsYachGTcUNrEpGLtkg1NJSO0",
	"nIqZOaiMsU/GWDJNZg/khkhiKjmMB6Zp0JDSwRCZmQL6MFEwSNIwg0DWx7h6VvVt6vmJ8+M7yCmWJb+r",
	"o+OPXW3Ici5jH7NI0q8PsZmwx+v9SHM4ilEZcE3OYO7Q2JA+t3fxwCsFB99htpEF7zQ79U6z4VvP5sUS",
	"n8MRqBvwElBTcoobV53AB88AM5nuS2o6x5spPd3xd38mfkeBBt/e3tNYoqOjE1n20dY9Ak/7yN6gH7m+",
	"R9jVbjHl2SB16S3P4AT47G1vqpXsJVCHGvtYyP4er2XdLz1Zwv6OXfDdnYi19V5NCF9lZFUSMuBaPyfL",
	"USWymuQ4E85xnOGkOLKtONwsQODmU8tpVCMr1txef2NJ+d9XPzquRFO1NK1XC8LmKV+Txqq/4rerARly",
	"qqlvxq6zDw9tmD4lC7Vcp4nw41gh4mdYk2UY4nj7FdBAdoHixdGjG61WqOpgrlmZJnSSY+joY4yOAsIG",
	"sldwVoRk6GhuDjl3j6wbJKVyn0Q/M7EyLz883P2WggUFSSEulDn+YenxVvhTWyjDE0pol4dzTXAorRXR",
	"2Jyu6eCvUOaWQeqjMAW7EHS11ibocBC7I60M5tkmJmPd0ASycgK/lE7ry2UygARX17k5qJB5ayo+5aI9",
	"p4A7AAyIocU4ARZLogKBrnJzu6WnD3AlmtROkF3AKTYs+U/XOEajUVk5IsvVI0oh2uvFur/Kc4bDtUe7",
	"7i3uHH33XTC/6d359Zy/YufbryN3HjkbyN1C7qOz+JUohWKOxLlz59sTiYQoiVlgmlDHy/z7V4n2/99/",
	"/Vy+nT6czf+BZ3Qj18ipxlz7VOPXCTB+8fzN6lEpDdwQePikJuiYGB2/aF3KquFyQy+gs8lVDxM8pqxh",
	"fIgE2nw8qwpnHdu6kPMKuTeIH3OAn7GvsxoL1gv+wh2c8XX3q9lfd7+vl3jsGzg2mngezK23NfLdG7rl",
	"9R/SWf575ok3dLIb+s/NMkBZAqrD1OCJdCO6Kl2iEQ+Z3pQh+gTrhAQ/kiWtyfOzuk6kzDOQ01WiYzpQ",
	"xgzZCAd5AyCljH1d+dNQIMSnGtQh/A/+Ab6oVjWabRwNN4k3IBvmWCiW5G3xt2oZpNkWRg4fmxxIEg1A",
	"4lVD1UY56+JrlNVBjaf7PyLnOXJp65uN3CfkYQ45m/jB2fOKb0gXTCHstbMaiLvvr80ExSnkfk/Qw0Lu",
	"a+Gj3h5kOVfVw/15f+2eNzFZWrkVo6GA8G8ffXIF51u9ueLhLkZx/9kTHNf+WYt9nExrbXEBq3kfOZ8Q",
	"F/pG5UGTZGWdHZJhmELO3XJ3HnEW8EZXVfzBXaH5/NLTO8GL8dilKx992f1xRybVduGq2i5cGTmfEFiu",
	"z7JpzcazVoWznZW3Tn1hQCA1naLQGdF0ml8Vzp7BKk6rBV1d5CztQmQocp7hZ7so9KW10ZQ2qgr0hOEU",
	"iZDOxoE5HE/BwbiRBXEjm4obWchWLG3eLq2/JuCxgEsVE+vI3cRdi8462WwS2Vu0U7GnOxbqR2zDMWVt",
	"JyEZUO0XxNmnw/172MuqslOURFM2iZXKasMwCZQkvlNRErFnR6Um0dHZkaBuOFRBVhYviGc7Eh1nqTlL",
	"EzCLg6wcx7PxH1mNRkYY7YgXjOMG0lNQKRiH+zUbODLVIfFKP2deajq22mmZ76dwBg3zopYae2/djuH2",
	"lnwtZrLEY02r5ZlE4j1vzVqD6rotqaIGL2f95SV8X+cSiUYLVk5Y7t2UqgjU4gxsRspeidgpjBhCp8BF",
	"DlESTTBk0HhCSYr9eGpFYOIDOWU4LDUNC5LFTmSvYk2iOoz1ww73AFBbjAcU3+Cv9lPaFRA8GEf2Jo0/",
	"YsH4in+riJzp+OXy/yznEb/cTR+E4NlU21WV1E9eIRtHWpSnWIF2LRJ7bZUO5vAAyyEO6q1gaiOYvcGK",
	"OReFYGcfWXYw9covTLOX3eQl5s8C0WjWXIiXurnpzczjok1xnBWFsGpW+i6xqxFqz6Qplli4nxOrtr+7",
	"Qk7MmiD+ayE8P3g5jvEHL363cnKi/fU6ipvt/sk1NNrle8paGunK5GkqDYbtOZoJ/IeobKP2mZDcU03C",
	"xuJw1/Jnfm5Jn3WaFGis0sQCTSL7YZwVQ+yHNX1Ql3s/aMMJA5YqxY0VtZr+Bs+wiyFoYNkFphp9vUcT",
	"t73JG9hloTUVd7+iDVhXrqrcNEqNWj97EjzeQ/Y8a9Rjec2Cf2cWlzycu7R1D3sSqzf9+e3yadeCl8vI",
	"mS69eY0cq7GSsczJP7meRZKhp6xmtVm0hlpGr+6UlYuJQ01RHgsybnqcmokIbCUp1lizsHOWgtfilQh6",
	"CHJcrD4I9GSaBsmnJFnSdfpLlW9yUB+r/lDlG/HY38PwJylyRjZrJtZ0MVUqPGcSiVCNp5NT4ul/R7Fr",
	"KVGB+czJOtWJYdgQsyTWu4pXdUnnrr/wk7/0c2lz2Zu9jZ2Iqdv+D68ovvmrS8GLxyGpYmLEESycvG4m",
	"WJ+QMf8nWL+3YGE+tyRYJDf6vkRq2npvwkQrlI3F6YpsmJ+yMadpAX/vi6M0tXR1xC95X1fHGkeYKMRo",
	"JwF13Gieo62la2ONgk1QgKV9TxEHIqyrEdFCWERjwcYeDbe8ifXD/f9E7j5RfYH4jGttosSFh7fClGp1",
	"sCVnpVxI/R8CUXXVpaYST2+IxOUPy5H6+8Kumrzm+wIxpg3x68NwLN9QJ/4MzX+0QrRUkBJwe0eoEEVk",
	"EKfvqiJIqyaNf1Pcai3onSWwhY1YNZQjZ1S2Shs7wYtt6vSfOy2nvyLWdPdY5Wc2yN0PF4pwXshaQ+5+",
	"uMrZAKLxBrg1jolUpK8ZmHAUjAnBy1vB3HNREnO6Il4Q48TcscXqawDLJFN94N1xgok1VsHCEfK0FY6T",
	"w+ekBqatKirlA9YLI7dwEM4eIHe/Euyw1Uisk+/P//cA",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
