// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"compress/flate"
	"context"
	"encoding/base64"
	"encoding/json"
	"fmt"
	"net/http"
	"net/url"
	"path"
	"strings"

	"github.com/getkin/kin-openapi/openapi3"
	"github.com/labstack/echo/v4"
	"github.com/oapi-codegen/runtime"
)

// Defines values for DefenderPreset.
const (
	DefenderPresetHb      DefenderPreset = "hb"
	DefenderPresetHbBoost DefenderPreset = "hb_boost"
	DefenderPresetHbFull  DefenderPreset = "hb_full"
	DefenderPresetHd      DefenderPreset = "hd"
	DefenderPresetHdBoost DefenderPreset = "hd_boost"
	DefenderPresetHdFull  DefenderPreset = "hd_full"
	DefenderPresetHp      DefenderPreset = "hp"
	DefenderPresetNone    DefenderPreset = "none"
)

// Valid indicates whether the value is a known member of the DefenderPreset enum.
func (e DefenderPreset) Valid() bool {
	switch e {
	case DefenderPresetHb:
		return true
	case DefenderPresetHbBoost:
		return true
	case DefenderPresetHbFull:
		return true
	case DefenderPresetHd:
		return true
	case DefenderPresetHdBoost:
		return true
	case DefenderPresetHdFull:
		return true
	case DefenderPresetHp:
		return true
	case DefenderPresetNone:
		return true
	default:
		return false
	}
}

// Defines values for ErrorCode.
const (
	DuplicatePreset     ErrorCode = "duplicate_preset"
	Internal            ErrorCode = "internal"
	InvalidEnum         ErrorCode = "invalid_enum"
	InvalidInput        ErrorCode = "invalid_input"
	InvalidJson         ErrorCode = "invalid_json"
	InvalidObservation  ErrorCode = "invalid_observation"
	InvalidPreset       ErrorCode = "invalid_preset"
	InvalidReverseSide  ErrorCode = "invalid_reverse_side"
	InvalidTypeChart    ErrorCode = "invalid_type_chart"
	MasterUnavailable   ErrorCode = "master_unavailable"
	MissingHeader       ErrorCode = "missing_header"
	NoObservation       ErrorCode = "no_observation"
	NotFound            ErrorCode = "not_found"
	TypeChartMissing    ErrorCode = "type_chart_missing"
	UnknownAbility      ErrorCode = "unknown_ability"
	UnknownField        ErrorCode = "unknown_field"
	UnknownItem         ErrorCode = "unknown_item"
	UnknownMove         ErrorCode = "unknown_move"
	UnknownNature       ErrorCode = "unknown_nature"
	UnknownPreset       ErrorCode = "unknown_preset"
	UnknownSpecies      ErrorCode = "unknown_species"
	UnknownType         ErrorCode = "unknown_type"
	UpstreamUnavailable ErrorCode = "upstream_unavailable"
)

// Valid indicates whether the value is a known member of the ErrorCode enum.
func (e ErrorCode) Valid() bool {
	switch e {
	case DuplicatePreset:
		return true
	case Internal:
		return true
	case InvalidEnum:
		return true
	case InvalidInput:
		return true
	case InvalidJson:
		return true
	case InvalidObservation:
		return true
	case InvalidPreset:
		return true
	case InvalidReverseSide:
		return true
	case InvalidTypeChart:
		return true
	case MasterUnavailable:
		return true
	case MissingHeader:
		return true
	case NoObservation:
		return true
	case NotFound:
		return true
	case TypeChartMissing:
		return true
	case UnknownAbility:
		return true
	case UnknownField:
		return true
	case UnknownItem:
		return true
	case UnknownMove:
		return true
	case UnknownNature:
		return true
	case UnknownPreset:
		return true
	case UnknownSpecies:
		return true
	case UnknownType:
		return true
	case UpstreamUnavailable:
		return true
	default:
		return false
	}
}

// Defines values for Format.
const (
	Double Format = "double"
	Single Format = "single"
)

// Valid indicates whether the value is a known member of the Format enum.
func (e Format) Valid() bool {
	switch e {
	case Double:
		return true
	case Single:
		return true
	default:
		return false
	}
}

// Defines values for MoveCategory.
const (
	Physical MoveCategory = "physical"
	Special  MoveCategory = "special"
	Status   MoveCategory = "status"
)

// Valid indicates whether the value is a known member of the MoveCategory enum.
func (e MoveCategory) Valid() bool {
	switch e {
	case Physical:
		return true
	case Special:
		return true
	case Status:
		return true
	default:
		return false
	}
}

// Defines values for NatureClass.
const (
	Neutral NatureClass = "neutral"
	Plus    NatureClass = "plus"
)

// Valid indicates whether the value is a known member of the NatureClass enum.
func (e NatureClass) Valid() bool {
	switch e {
	case Neutral:
		return true
	case Plus:
		return true
	default:
		return false
	}
}

// Defines values for PokeType.
const (
	PokeTypeBug      PokeType = "bug"
	PokeTypeDark     PokeType = "dark"
	PokeTypeDragon   PokeType = "dragon"
	PokeTypeElectric PokeType = "electric"
	PokeTypeFairy    PokeType = "fairy"
	PokeTypeFighting PokeType = "fighting"
	PokeTypeFire     PokeType = "fire"
	PokeTypeFlying   PokeType = "flying"
	PokeTypeGhost    PokeType = "ghost"
	PokeTypeGrass    PokeType = "grass"
	PokeTypeGround   PokeType = "ground"
	PokeTypeIce      PokeType = "ice"
	PokeTypeNormal   PokeType = "normal"
	PokeTypePoison   PokeType = "poison"
	PokeTypePsychic  PokeType = "psychic"
	PokeTypeRock     PokeType = "rock"
	PokeTypeSteel    PokeType = "steel"
	PokeTypeWater    PokeType = "water"
)

// Valid indicates whether the value is a known member of the PokeType enum.
func (e PokeType) Valid() bool {
	switch e {
	case PokeTypeBug:
		return true
	case PokeTypeDark:
		return true
	case PokeTypeDragon:
		return true
	case PokeTypeElectric:
		return true
	case PokeTypeFairy:
		return true
	case PokeTypeFighting:
		return true
	case PokeTypeFire:
		return true
	case PokeTypeFlying:
		return true
	case PokeTypeGhost:
		return true
	case PokeTypeGrass:
		return true
	case PokeTypeGround:
		return true
	case PokeTypeIce:
		return true
	case PokeTypeNormal:
		return true
	case PokeTypePoison:
		return true
	case PokeTypePsychic:
		return true
	case PokeTypeRock:
		return true
	case PokeTypeSteel:
		return true
	case PokeTypeWater:
		return true
	default:
		return false
	}
}

// Defines values for ReverseSide.
const (
	Attacker ReverseSide = "attacker"
	Defender ReverseSide = "defender"
)

// Valid indicates whether the value is a known member of the ReverseSide enum.
func (e ReverseSide) Valid() bool {
	switch e {
	case Attacker:
		return true
	case Defender:
		return true
	default:
		return false
	}
}

// Defines values for StatKey.
const (
	StatKeyAtk StatKey = "atk"
	StatKeyDef StatKey = "def"
	StatKeyHp  StatKey = "hp"
	StatKeySpa StatKey = "spa"
	StatKeySpd StatKey = "spd"
	StatKeySpe StatKey = "spe"
)

// Valid indicates whether the value is a known member of the StatKey enum.
func (e StatKey) Valid() bool {
	switch e {
	case StatKeyAtk:
		return true
	case StatKeyDef:
		return true
	case StatKeyHp:
		return true
	case StatKeySpa:
		return true
	case StatKeySpd:
		return true
	case StatKeySpe:
		return true
	default:
		return false
	}
}

// Defines values for StatusCondition.
const (
	StatusConditionBadlyPoison StatusCondition = "badly_poison"
	StatusConditionBurn        StatusCondition = "burn"
	StatusConditionFreeze      StatusCondition = "freeze"
	StatusConditionNone        StatusCondition = "none"
	StatusConditionParalysis   StatusCondition = "paralysis"
	StatusConditionPoison      StatusCondition = "poison"
	StatusConditionSleep       StatusCondition = "sleep"
)

// Valid indicates whether the value is a known member of the StatusCondition enum.
func (e StatusCondition) Valid() bool {
	switch e {
	case StatusConditionBadlyPoison:
		return true
	case StatusConditionBurn:
		return true
	case StatusConditionFreeze:
		return true
	case StatusConditionNone:
		return true
	case StatusConditionParalysis:
		return true
	case StatusConditionPoison:
		return true
	case StatusConditionSleep:
		return true
	default:
		return false
	}
}

// Defines values for Terrain.
const (
	TerrainElectric Terrain = "electric"
	TerrainGrassy   Terrain = "grassy"
	TerrainMisty    Terrain = "misty"
	TerrainNone     Terrain = "none"
	TerrainPsychic  Terrain = "psychic"
)

// Valid indicates whether the value is a known member of the Terrain enum.
func (e Terrain) Valid() bool {
	switch e {
	case TerrainElectric:
		return true
	case TerrainGrassy:
		return true
	case TerrainMisty:
		return true
	case TerrainNone:
		return true
	case TerrainPsychic:
		return true
	default:
		return false
	}
}

// Defines values for Weather.
const (
	WeatherNone Weather = "none"
	WeatherRain Weather = "rain"
	WeatherSand Weather = "sand"
	WeatherSnow Weather = "snow"
	WeatherSun  Weather = "sun"
)

// Valid indicates whether the value is a known member of the Weather enum.
func (e Weather) Valid() bool {
	switch e {
	case WeatherNone:
		return true
	case WeatherRain:
		return true
	case WeatherSand:
		return true
	case WeatherSnow:
		return true
	case WeatherSun:
		return true
	default:
		return false
	}
}

// Ability defines model for Ability.
type Ability struct {
	Id     string `json:"id"`
	NameJa string `json:"nameJa"`
}

// BulkCalcRequest defines model for BulkCalcRequest.
type BulkCalcRequest struct {
	// Attacker 計算に使う個体。SP と性格 ID から実数値を導出する
	Attacker Individual `json:"attacker"`

	// DefenderSpeciesKey {図鑑番号4桁}-{フォルム3桁}
	//
	// Example: 0445-000
	DefenderSpeciesKey SpeciesKey  `json:"defenderSpeciesKey"`
	Field              *FieldState `json:"field,omitempty"`
	Format             Format      `json:"format"`

	// ItemVariants 差し替えて比較する持ち物 ID(省略時は素の1通り)
	ItemVariants *[]*string   `json:"itemVariants,omitempty"`
	MoveId       string       `json:"moveId"`
	Options      *CalcOptions `json:"options,omitempty"`

	// Presets 使う防御側プリセットと行の順序。省略と空配列(`[]`)は同じで、技の分類に応じた既定セットになる。
	// 物理技は 5 件(none, hp, hb_boost, hb, hb_full)、
	// 特殊技は 5 件(none, hp, hd_boost, hd, hd_full)、
	// **変化技は 2 件(none, hp)のみ**。
	// 指定したときはその順に行を返す(分類に合わないプリセットも指定どおり返す)。
	// 同じ preset を2回以上含めると 400 `duplicate_preset`。
	// engine のカスタムプリセット定義(SP・性格を任意に決めたもの)は API に出さない。
	Presets *[]DefenderPreset `json:"presets,omitempty"`
}

// BulkCalcResult defines model for BulkCalcResult.
type BulkCalcResult struct {
	// DefenderSpeciesKey {図鑑番号4桁}-{フォルム3桁}
	//
	// Example: 0445-000
	DefenderSpeciesKey SpeciesKey    `json:"defenderSpeciesKey"`
	Rows               []BulkCalcRow `json:"rows"`
}

// BulkCalcRow defines model for BulkCalcRow.
type BulkCalcRow struct {
	// Defender 一括計算の1行で使った防御側の調整(SP・性格補正・実数値)
	Defender BulkDefender `json:"defender"`

	// ItemId この行の防御側の持ち物(持ち物なしは null)
	ItemId *string `json:"itemId,omitempty"`

	// Preset 防御側の代表調整(耐久が上がる順)。SP は能力ポイント(Lv50・個体値31固定)。
	// 性格の「無補正」は上昇・下降なし、「+B/-A」は防御上昇・攻撃下降のこと。
	// engine の PresetKey と同一文字列(docs/adr/0009-bulk-calc-presets.md §1)。
	// - `none`: 無振り(SP なし・無補正)。全分類
	// - `hp`: H振り(HP 32・無補正)。全分類
	// - `hb_boost`: H振り+B補正(HP 32・防御上昇 +B/-A)。物理
	// - `hb`: HB振り(HP 32・防御 32・無補正)。物理
	// - `hb_full`: HB特化(HP 32・防御 32・防御上昇 +B/-A)。物理
	// - `hd_boost`: H振り+D補正(HP 32・特防上昇 +D/-A)。特殊
	// - `hd`: HD振り(HP 32・特防 32・無補正)。特殊
	// - `hd_full`: HD特化(HP 32・特防 32・特防上昇 +D/-A)。特殊
	Preset DefenderPreset `json:"preset"`

	// PresetLabel 表示名(例 HB振り / HB特化 / H振り+B補正)
	PresetLabel string     `json:"presetLabel"`
	Result      CalcResult `json:"result"`
}

// BulkDefender 一括計算の1行で使った防御側の調整(SP・性格補正・実数値)
type BulkDefender struct {
	// Nature 性格補正の構造値。plus が +10%、minus が -10% を受ける能力。無補正は両方 null。
	// HP を指すことはない。
	Nature NatureModifier `json:"nature"`

	// NatureId nature と (plus, minus) が一致するマスタの性格 ID。無補正は、マスタの無補正性格を
	// ID の昇順で並べた最初のもの。該当する性格がマスタに無ければ null。
	NatureId *string `json:"natureId"`

	// Sp 能力ポイント
	Sp StatBlock `json:"sp"`

	// Stats 実数値(Lv50・個体値31)
	Stats StatBlock `json:"stats"`
}

// CalcOptions defines model for CalcOptions.
type CalcOptions struct {
	// Critical 急所
	Critical *bool `json:"critical,omitempty"`
}

// CalcRequest defines model for CalcRequest.
type CalcRequest struct {
	// Attacker 計算に使う個体。SP と性格 ID から実数値を導出する
	Attacker Individual `json:"attacker"`

	// Defender 計算に使う個体。SP と性格 ID から実数値を導出する
	Defender Individual  `json:"defender"`
	Field    *FieldState `json:"field,omitempty"`
	Format   Format      `json:"format"`

	// MoveId 使用する技(attacker.moveId より優先)
	MoveId  string       `json:"moveId"`
	Options *CalcOptions `json:"options,omitempty"`
}

// CalcResult defines model for CalcResult.
type CalcResult struct {
	// Category 使った技の分類(WASM 境界の CalcResult と同じ。Web が型を共有するため)
	Category   MoveCategory `json:"category"`
	DefenderHP int          `json:"defenderHP"`

	// Effectiveness タイプ相性(0, 0.25, 0.5, 1, 2, 4)
	Effectiveness float64 `json:"effectiveness"`

	// Ko 確定数/乱数n発
	Ko        KOChance `json:"ko"`
	MaxDamage int      `json:"maxDamage"`

	// MaxPercent 最大ダメージの表示%(防御側 HP に対する割合)。小数第1位(0.1%刻み)で、
	// **四捨五入**する(ADR-0010 §3)。
	// 100 を超える場合は上限で切らず、そのまま返す(例 137.0)。
	// 逆算の入力の観測%(`Observation.percent` / `percentTenths`)とは別概念。
	MaxPercent float64 `json:"maxPercent"`
	MinDamage  int     `json:"minDamage"`

	// MinPercent 最小ダメージの表示%(防御側 HP に対する割合)。小数第1位(0.1%刻み)で、
	// **切り捨て**る(「最低これくらい入る」を保守的に示すため。ADR-0010 §3)。
	// 整数%に丸めてから小数にした値ではない。HP 比率から直接求める。
	// engine の 0.1% 単位の整数(tenths)を 10 で割っただけの値で、float で近似しない。
	MinPercent float64 `json:"minPercent"`

	// Rolls 16 段階の乱数ダメージ(非減少)
	Rolls []int `json:"rolls"`

	// Stab タイプ一致
	Stab bool `json:"stab"`
}

// DefenderPreset 防御側の代表調整(耐久が上がる順)。SP は能力ポイント(Lv50・個体値31固定)。
// 性格の「無補正」は上昇・下降なし、「+B/-A」は防御上昇・攻撃下降のこと。
// engine の PresetKey と同一文字列(docs/adr/0009-bulk-calc-presets.md §1)。
// - `none`: 無振り(SP なし・無補正)。全分類
// - `hp`: H振り(HP 32・無補正)。全分類
// - `hb_boost`: H振り+B補正(HP 32・防御上昇 +B/-A)。物理
// - `hb`: HB振り(HP 32・防御 32・無補正)。物理
// - `hb_full`: HB特化(HP 32・防御 32・防御上昇 +B/-A)。物理
// - `hd_boost`: H振り+D補正(HP 32・特防上昇 +D/-A)。特殊
// - `hd`: HD振り(HP 32・特防 32・無補正)。特殊
// - `hd_full`: HD特化(HP 32・特防 32・特防上昇 +D/-A)。特殊
type DefenderPreset string

// Error エラーの本文。HTTP ステータスは `code` から決まる(ErrorCode の対応表)。
// `message` は日本語の説明で、Go の内部情報(スタック・型名)を含めない。
type Error struct {
	// Code 安定したエラーコード。WASM 境界(engine/wasmapi の Code* 定数。ADR-0011 §5・§13)と語彙を共通にし、
	// **同じ失敗は HTTP と WASM で同じ code** になる(ADR-0016)。
	//
	// WASM 境界と共通:
	// | code | 意味 | HTTP |
	// |---|---|---|
	// | invalid_json | JSON として壊れている / 型が合わない(整数のフィールドに小数を含む) | 400 |
	// | unknown_field | 契約にないフィールド | 400 |
	// | invalid_enum | 列挙(形式・タイプ・天候・フィールド・状態異常)の値が未知 | 400 |
	// | invalid_input | 入力検証(SP の範囲・合計、ランク、レベル、性格が HP など) | 400 |
	// | unknown_preset | 未知の防御側プリセット | 400 |
	// | duplicate_preset | 防御側プリセットの重複 | 400 |
	// | invalid_preset | 防御側プリセットの定義が不正 | 400 |
	// | invalid_reverse_side | 逆算の side が defender / attacker のどちらでもない | 400 |
	// | no_observation | 観測が1件も無い | 400 |
	// | invalid_observation | 観測の指定が不正(percent / percentTenths / damage のちょうど1つでない・範囲外) | 400 |
	// | type_chart_missing | タイプ相性表が無い(HTTP ではマスタ側の失敗なので通常は起きない) | 400 |
	// | invalid_type_chart | タイプ相性表の定義が不正 | 400 |
	// | unknown_type | 相性表に無いタイプ | 400 |
	// | internal | 上記以外の失敗(回復した panic を含む) | 500 |
	//
	// HTTP だけのもの:
	// | code | 意味 | HTTP |
	// |---|---|---|
	// | missing_header | X-Device-Id / X-Session-Id が無い・空(UUID 形式の検証は gateway が行う) | 400 |
	// | unknown_species | speciesKey がマスタに無い | 400 |
	// | unknown_move | moveId がマスタに無い | 400 |
	// | unknown_item | itemId がマスタに無い | 400 |
	// | unknown_ability | abilityId がマスタに無い | 400 |
	// | unknown_nature | natureId がマスタに無い | 400 |
	// | not_found | ルートが無い / このサービスの担当外の操作 | 404 |
	// | master_unavailable | マスタを参照できない | 503 |
	// | upstream_unavailable | gateway から下流のサービスに届かない(P3-2) | 503 |
	Code    ErrorCode `json:"code"`
	Message string    `json:"message"`
}

// ErrorCode 安定したエラーコード。WASM 境界(engine/wasmapi の Code* 定数。ADR-0011 §5・§13)と語彙を共通にし、
// **同じ失敗は HTTP と WASM で同じ code** になる(ADR-0016)。
//
// WASM 境界と共通:
// | code | 意味 | HTTP |
// |---|---|---|
// | invalid_json | JSON として壊れている / 型が合わない(整数のフィールドに小数を含む) | 400 |
// | unknown_field | 契約にないフィールド | 400 |
// | invalid_enum | 列挙(形式・タイプ・天候・フィールド・状態異常)の値が未知 | 400 |
// | invalid_input | 入力検証(SP の範囲・合計、ランク、レベル、性格が HP など) | 400 |
// | unknown_preset | 未知の防御側プリセット | 400 |
// | duplicate_preset | 防御側プリセットの重複 | 400 |
// | invalid_preset | 防御側プリセットの定義が不正 | 400 |
// | invalid_reverse_side | 逆算の side が defender / attacker のどちらでもない | 400 |
// | no_observation | 観測が1件も無い | 400 |
// | invalid_observation | 観測の指定が不正(percent / percentTenths / damage のちょうど1つでない・範囲外) | 400 |
// | type_chart_missing | タイプ相性表が無い(HTTP ではマスタ側の失敗なので通常は起きない) | 400 |
// | invalid_type_chart | タイプ相性表の定義が不正 | 400 |
// | unknown_type | 相性表に無いタイプ | 400 |
// | internal | 上記以外の失敗(回復した panic を含む) | 500 |
//
// HTTP だけのもの:
// | code | 意味 | HTTP |
// |---|---|---|
// | missing_header | X-Device-Id / X-Session-Id が無い・空(UUID 形式の検証は gateway が行う) | 400 |
// | unknown_species | speciesKey がマスタに無い | 400 |
// | unknown_move | moveId がマスタに無い | 400 |
// | unknown_item | itemId がマスタに無い | 400 |
// | unknown_ability | abilityId がマスタに無い | 400 |
// | unknown_nature | natureId がマスタに無い | 400 |
// | not_found | ルートが無い / このサービスの担当外の操作 | 404 |
// | master_unavailable | マスタを参照できない | 503 |
// | upstream_unavailable | gateway から下流のサービスに届かない(P3-2) | 503 |
type ErrorCode string

// FieldState defines model for FieldState.
type FieldState struct {
	AttackerScreens *Screens `json:"attackerScreens,omitempty"`
	DefenderScreens *Screens `json:"defenderScreens,omitempty"`
	Terrain         *Terrain `json:"terrain,omitempty"`
	Weather         *Weather `json:"weather,omitempty"`
}

// Format defines model for Format.
type Format string

// Individual 計算に使う個体。SP と性格 ID から実数値を導出する
type Individual struct {
	AbilityId *string `json:"abilityId,omitempty"`
	ItemId    *string `json:"itemId,omitempty"`
	Level     *int    `json:"level,omitempty"`

	// MoveId 攻撃側で使う技
	MoveId   *string `json:"moveId,omitempty"`
	NatureId string  `json:"natureId"`

	// Ranks ランク補正(-6..+6)。HP は持たない
	Ranks *RankBlock `json:"ranks,omitempty"`

	// Sp 能力ポイント。各 0..32、合計 <= 66
	Sp StatBlock `json:"sp"`

	// SpeciesKey {図鑑番号4桁}-{フォルム3桁}
	//
	// Example: 0445-000
	SpeciesKey SpeciesKey       `json:"speciesKey"`
	Status     *StatusCondition `json:"status,omitempty"`
	TeraType   *PokeType        `json:"teraType,omitempty"`
}

// Item defines model for Item.
type Item struct {
	Id     string `json:"id"`
	NameJa string `json:"nameJa"`
}

// KOChance 確定数/乱数n発
type KOChance struct {
	// ChancePercent engine の生値。guaranteed が false のとき、hits 回で倒せる確率(%)を丸めずに返す
	// (ADR-0006)。guaranteed が true のとき、および hits = 0(倒せない)のときは 0。
	// **画面に出す値ではない**(確定なのに 0% と誤表示されるため)。表示には
	// displayChancePercent を使う。
	ChancePercent *float64 `json:"chancePercent,omitempty"`

	// DisplayChancePercent 画面に出す「hits 回で倒せる確率(%)」。常に表示できる値であることを保証する。
	// 小数第1位(0.1%刻み。ADR-0010 §3)。
	// - hits = 0(倒せない): 0
	// - guaranteed = true(確定 n 発): 100.0
	// - それ以外: chancePercent を 0.1% 単位に四捨五入し、[0.1, 99.9] に収める
	//   (確定・不可能と取り違えないため、0.0 と 100.0 はこの2つに予約する)
	DisplayChancePercent float64 `json:"displayChancePercent"`

	// Guaranteed 最小ダメージでも hits 回で倒せるなら true(確定n発)
	Guaranteed bool `json:"guaranteed"`

	// Hits 最大ダメージで倒すのに必要な攻撃回数(0 = 倒せない)
	Hits int `json:"hits"`
}

// Move defines model for Move.
type Move struct {
	Category MoveCategory `json:"category"`
	Id       string       `json:"id"`
	NameJa   string       `json:"nameJa"`

	// Power 威力(0 は変化技/固定ダメージ)
	Power    int      `json:"power"`
	Priority *int     `json:"priority,omitempty"`
	Type     PokeType `json:"type"`
}

// MoveCategory defines model for MoveCategory.
type MoveCategory string

// Nature defines model for Nature.
type Nature struct {
	// Id Example: adamant
	Id string `json:"id"`

	// Minus 下降補正(-10%)を受ける能力。無補正性格は null
	Minus *StatKey `json:"minus,omitempty"`

	// NameJa Example: いじっぱり
	NameJa string `json:"nameJa"`

	// Plus 上昇補正(+10%)を受ける能力。無補正性格は null
	Plus *StatKey `json:"plus,omitempty"`
}

// NatureClass 関連ステータスに対する性格補正のクラス(neutral=無補正 / plus=関連ステータス +10%)。下降補正は探索しない
type NatureClass string

// NatureModifier 性格補正の構造値。plus が +10%、minus が -10% を受ける能力。無補正は両方 null。
// HP を指すことはない。
type NatureModifier struct {
	Minus *StatKey `json:"minus"`
	Plus  *StatKey `json:"plus"`
}

// Observation 1発ぶんの観測。percent / percentTenths / damage の**ちょうど1つ**を指定する(ADR-0010 §R2)。
// 0 個・2 個以上・範囲外は 400 `invalid_observation`。整数でなければ(例 12.5)400 `invalid_json`。
// 表示%(CalcResult.minPercent など)とは別概念で、丸め規則に依存しない区間で照合する。
type Observation struct {
	// Damage HP の実点数の観測(自分の HP の減少量など)
	Damage *int `json:"damage,omitempty"`

	// Note 画面用のメモ。計算には使わない
	Note *string `json:"note,omitempty"`

	// Percent 整数%の観測(精度 1%)
	Percent *int `json:"percent,omitempty"`

	// PercentTenths 小数第1位の観測を 0.1% 単位の整数にしたもの(例 45.3% → 453)
	PercentTenths *int `json:"percentTenths,omitempty"`
}

// PokeType defines model for PokeType.
type PokeType string

// RankBlock ランク補正(-6..+6)。HP は持たない
type RankBlock struct {
	Atk *int `json:"atk,omitempty"`
	Def *int `json:"def,omitempty"`
	Spa *int `json:"spa,omitempty"`
	Spd *int `json:"spd,omitempty"`
	Spe *int `json:"spe,omitempty"`
}

// ReverseCandidate 候補1件(性格クラス × 持ち物。ADR-0010 §R3)
type ReverseCandidate struct {
	// Exact mismatch == 0(全観測を説明できる)
	Exact bool `json:"exact"`

	// ItemId 持ち物(持ち物なしは null)
	ItemId *string `json:"itemId"`

	// MaxPercent ranges 全体での想定ダメージ幅の上限(表示%。小数第1位・四捨五入。CalcResult.maxPercent と同じ意味)
	MaxPercent float64 `json:"maxPercent"`

	// MinPercent ranges 全体での想定ダメージ幅の下限(表示%。小数第1位・切り捨て。CalcResult.minPercent と同じ意味)
	MinPercent float64 `json:"minPercent"`

	// Mismatch 観測とのずれ(0.1% 単位の整数。0 は完全に説明できる)
	Mismatch int `json:"mismatch"`

	// Nature 性格補正の構造値。plus が +10%、minus が -10% を受ける能力。無補正は両方 null。
	// HP を指すことはない。
	Nature NatureModifier `json:"nature"`

	// NatureClass 関連ステータスに対する性格補正のクラス(neutral=無補正 / plus=関連ステータス +10%)。下降補正は探索しない
	NatureClass NatureClass `json:"natureClass"`

	// NatureId nature と (plus, minus) が一致するマスタの性格 ID(BulkDefender.natureId と同じ規則)。
	// 無補正は、マスタの無補正性格を ID の昇順で並べた最初のもの。該当なしは null。
	NatureId *string `json:"natureId"`

	// Ranges 観測を説明できる SP の集合(昇順・互いに素・隣接しない極大連続区間)。説明できなければ距離最小の SP
	Ranges []SPRange `json:"ranges"`

	// SpCount ranges に含まれる SP の数
	SpCount int `json:"spCount"`

	// Support ranges の各 SP で各観測を説明できるロールの延べ数
	Support int `json:"support"`
}

// ReverseRequest defines model for ReverseRequest.
type ReverseRequest struct {
	Field  *FieldState `json:"field,omitempty"`
	Format Format      `json:"format"`

	// ItemCandidates 相手の持ち物の候補(ID)。null 要素は「持ち物なし」。省略・空配列は [null] と同じ
	ItemCandidates *[]*string `json:"itemCandidates,omitempty"`

	// Known 既知の側(自分)の個体。side=defender なら自分=攻撃側、side=attacker なら自分=防御側。
	// known.moveId は使わない(技は moveId で指定する)。
	Known Individual `json:"known"`

	// MaxCandidates 返す候補数の上限。0 は無制限
	MaxCandidates *int `json:"maxCandidates,omitempty"`

	// MoveId 観測したときの技(side=defender なら自分の技、attacker なら相手の技)
	MoveId string `json:"moveId"`

	// Observations 同じ技・同じ場・同じ既知側に対する別々の1発。0 件は 400 `no_observation`
	Observations []Observation `json:"observations"`
	Options      *CalcOptions  `json:"options,omitempty"`

	// Side どちら側の調整を逆算するか(defender=与ダメ観測 / attacker=被ダメ観測)
	Side ReverseSide `json:"side"`

	// UnknownSpeciesKey 逆算する相手の種族。SP・性格・持ち物は探索対象なので渡さない
	UnknownSpeciesKey SpeciesKey `json:"unknownSpeciesKey"`
}

// ReverseResult defines model for ReverseResult.
type ReverseResult struct {
	// AssumedHpSp 仮定した相手の H の SP(defender=32、attacker=0。ADR-0010 §R1)
	AssumedHpSp int `json:"assumedHpSp"`

	// Candidates Mismatch 昇順 → Support 降順 → SPCount 降順 → 定義順(ADR-0010 §R4)
	Candidates []ReverseCandidate `json:"candidates"`

	// ExactCount exact な候補の数(maxCandidates で切る前)
	ExactCount int `json:"exactCount"`

	// Side どちら側の調整を逆算するか(defender=与ダメ観測 / attacker=被ダメ観測)
	Side ReverseSide `json:"side"`

	// Stat 逆算した関連ステータス(技の分類と side から決まる)
	Stat StatKey `json:"stat"`
}

// ReverseSide どちら側の調整を逆算するか(defender=与ダメ観測 / attacker=被ダメ観測)
type ReverseSide string

// SPRange SP の区間(両端を含む)
type SPRange struct {
	Max int `json:"max"`
	Min int `json:"min"`
}

// Screens defines model for Screens.
type Screens struct {
	AuroraVeil  *bool `json:"auroraVeil,omitempty"`
	LightScreen *bool `json:"lightScreen,omitempty"`
	Reflect     *bool `json:"reflect,omitempty"`
}

// SpeciesDetail defines model for SpeciesDetail.
type SpeciesDetail struct {
	Abilities []Ability `json:"abilities"`

	// BaseStats 6ステータスの値(種族値・実数値・SPなどに共用)
	BaseStats StatBlock `json:"baseStats"`
	DexNo     int       `json:"dexNo"`

	// Form フォルム番号
	Form int `json:"form"`

	// Key {図鑑番号4桁}-{フォルム3桁}
	//
	// Example: 0445-000
	Key SpeciesKey `json:"key"`

	// Learnset 覚える技の ID 一覧
	Learnset *[]string  `json:"learnset,omitempty"`
	NameJa   string     `json:"nameJa"`
	Types    []PokeType `json:"types"`
}

// SpeciesKey {図鑑番号4桁}-{フォルム3桁}
//
// Example: 0445-000
type SpeciesKey = string

// SpeciesSummary defines model for SpeciesSummary.
type SpeciesSummary struct {
	DexNo int `json:"dexNo"`

	// Form フォルム番号
	Form int `json:"form"`

	// Key {図鑑番号4桁}-{フォルム3桁}
	//
	// Example: 0445-000
	Key    SpeciesKey `json:"key"`
	NameJa string     `json:"nameJa"`
	Types  []PokeType `json:"types"`
}

// StatBlock 6ステータスの値(種族値・実数値・SPなどに共用)
type StatBlock struct {
	Atk int `json:"atk"`
	Def int `json:"def"`
	Hp  int `json:"hp"`
	Spa int `json:"spa"`
	Spd int `json:"spd"`
	Spe int `json:"spe"`
}

// StatKey defines model for StatKey.
type StatKey string

// StatusCondition defines model for StatusCondition.
type StatusCondition string

// Terrain defines model for Terrain.
type Terrain string

// Weather defines model for Weather.
type Weather string

// DeviceId defines model for DeviceId.
type DeviceId = string

// SessionId defines model for SessionId.
type SessionId = string

// CalcDamageParams defines parameters for CalcDamage.
type CalcDamageParams struct {
	// XDeviceId クライアント生成の端末 UUID
	XDeviceId DeviceId `json:"X-Device-Id"`

	// XSessionId セッション UUID
	XSessionId SessionId `json:"X-Session-Id"`
}

// CalcBulkParams defines parameters for CalcBulk.
type CalcBulkParams struct {
	// XDeviceId クライアント生成の端末 UUID
	XDeviceId DeviceId `json:"X-Device-Id"`

	// XSessionId セッション UUID
	XSessionId SessionId `json:"X-Session-Id"`
}

// CalcReverseParams defines parameters for CalcReverse.
type CalcReverseParams struct {
	// XDeviceId クライアント生成の端末 UUID
	XDeviceId DeviceId `json:"X-Device-Id"`

	// XSessionId セッション UUID
	XSessionId SessionId `json:"X-Session-Id"`
}

// SearchItemsParams defines parameters for SearchItems.
type SearchItemsParams struct {
	Q     *string `form:"q,omitempty" json:"q,omitempty"`
	Limit *int    `form:"limit,omitempty" json:"limit,omitempty"`

	// XDeviceId クライアント生成の端末 UUID
	XDeviceId DeviceId `json:"X-Device-Id"`

	// XSessionId セッション UUID
	XSessionId SessionId `json:"X-Session-Id"`
}

// SearchMovesParams defines parameters for SearchMoves.
type SearchMovesParams struct {
	Q     *string `form:"q,omitempty" json:"q,omitempty"`
	Limit *int    `form:"limit,omitempty" json:"limit,omitempty"`

	// XDeviceId クライアント生成の端末 UUID
	XDeviceId DeviceId `json:"X-Device-Id"`

	// XSessionId セッション UUID
	XSessionId SessionId `json:"X-Session-Id"`
}

// ListNaturesParams defines parameters for ListNatures.
type ListNaturesParams struct {
	// XDeviceId クライアント生成の端末 UUID
	XDeviceId DeviceId `json:"X-Device-Id"`

	// XSessionId セッション UUID
	XSessionId SessionId `json:"X-Session-Id"`
}

// SearchSpeciesParams defines parameters for SearchSpecies.
type SearchSpeciesParams struct {
	// Q 日本語名の前方一致(空なら全件・limit まで)
	Q      *string `form:"q,omitempty" json:"q,omitempty"`
	Format *Format `form:"format,omitempty" json:"format,omitempty"`
	Limit  *int    `form:"limit,omitempty" json:"limit,omitempty"`

	// XDeviceId クライアント生成の端末 UUID
	XDeviceId DeviceId `json:"X-Device-Id"`

	// XSessionId セッション UUID
	XSessionId SessionId `json:"X-Session-Id"`
}

// GetSpeciesParams defines parameters for GetSpecies.
type GetSpeciesParams struct {
	// XDeviceId クライアント生成の端末 UUID
	XDeviceId DeviceId `json:"X-Device-Id"`

	// XSessionId セッション UUID
	XSessionId SessionId `json:"X-Session-Id"`
}

// CalcDamageJSONRequestBody defines body for CalcDamage for application/json ContentType.
type CalcDamageJSONRequestBody = CalcRequest

// CalcBulkJSONRequestBody defines body for CalcBulk for application/json ContentType.
type CalcBulkJSONRequestBody = BulkCalcRequest

// CalcReverseJSONRequestBody defines body for CalcReverse for application/json ContentType.
type CalcReverseJSONRequestBody = ReverseRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// CalcDamage 1 vs 1 のダメージ計算
	// (POST /api/calc)
	CalcDamage(ctx echo.Context, params CalcDamageParams) error
	// CalcBulk 防御側の代表調整すべてに対する一括計算
	// (POST /api/calc/bulk)
	CalcBulk(ctx echo.Context, params CalcBulkParams) error
	// CalcReverse 観測ダメージから相手の調整候補を逆算
	// (POST /api/calc/reverse)
	CalcReverse(ctx echo.Context, params CalcReverseParams) error
	// SearchItems 持ち物を日本語名で前方一致検索
	// (GET /api/pokedex/items)
	SearchItems(ctx echo.Context, params SearchItemsParams) error
	// SearchMoves 技を日本語名で前方一致検索
	// (GET /api/pokedex/moves)
	SearchMoves(ctx echo.Context, params SearchMovesParams) error
	// ListNatures 性格の一覧(補正する能力)
	// (GET /api/pokedex/natures)
	ListNatures(ctx echo.Context, params ListNaturesParams) error
	// SearchSpecies ポケモンを日本語名で前方一致検索
	// (GET /api/pokedex/species)
	SearchSpecies(ctx echo.Context, params SearchSpeciesParams) error
	// GetSpecies 種族の詳細(タイプ・種族値・特性・覚える技)
	// (GET /api/pokedex/species/{key})
	GetSpecies(ctx echo.Context, key SpeciesKey, params GetSpeciesParams) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// CalcDamage converts echo context to params.
func (w *ServerInterfaceWrapper) CalcDamage(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params CalcDamageParams

	headers := ctx.Request().Header
	// ------------- Required header parameter "X-Device-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Device-Id")]; found {
		var XDeviceId DeviceId
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-Device-Id, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Device-Id", valueList[0], &XDeviceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-Device-Id: %s", err))
		}

		params.XDeviceId = XDeviceId
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter X-Device-Id is required, but not found"))
	}
	// ------------- Required header parameter "X-Session-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Session-Id")]; found {
		var XSessionId SessionId
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-Session-Id, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Session-Id", valueList[0], &XSessionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-Session-Id: %s", err))
		}

		params.XSessionId = XSessionId
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter X-Session-Id is required, but not found"))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CalcDamage(ctx, params)
	return err
}

// CalcBulk converts echo context to params.
func (w *ServerInterfaceWrapper) CalcBulk(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params CalcBulkParams

	headers := ctx.Request().Header
	// ------------- Required header parameter "X-Device-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Device-Id")]; found {
		var XDeviceId DeviceId
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-Device-Id, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Device-Id", valueList[0], &XDeviceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-Device-Id: %s", err))
		}

		params.XDeviceId = XDeviceId
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter X-Device-Id is required, but not found"))
	}
	// ------------- Required header parameter "X-Session-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Session-Id")]; found {
		var XSessionId SessionId
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-Session-Id, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Session-Id", valueList[0], &XSessionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-Session-Id: %s", err))
		}

		params.XSessionId = XSessionId
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter X-Session-Id is required, but not found"))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CalcBulk(ctx, params)
	return err
}

// CalcReverse converts echo context to params.
func (w *ServerInterfaceWrapper) CalcReverse(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params CalcReverseParams

	headers := ctx.Request().Header
	// ------------- Required header parameter "X-Device-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Device-Id")]; found {
		var XDeviceId DeviceId
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-Device-Id, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Device-Id", valueList[0], &XDeviceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-Device-Id: %s", err))
		}

		params.XDeviceId = XDeviceId
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter X-Device-Id is required, but not found"))
	}
	// ------------- Required header parameter "X-Session-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Session-Id")]; found {
		var XSessionId SessionId
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-Session-Id, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Session-Id", valueList[0], &XSessionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-Session-Id: %s", err))
		}

		params.XSessionId = XSessionId
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter X-Session-Id is required, but not found"))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CalcReverse(ctx, params)
	return err
}

// SearchItems converts echo context to params.
func (w *ServerInterfaceWrapper) SearchItems(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params SearchItemsParams
	// ------------- Optional query parameter "q" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "q", ctx.QueryParams(), &params.Q, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter q: %s", err))
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", ctx.QueryParams(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	headers := ctx.Request().Header
	// ------------- Required header parameter "X-Device-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Device-Id")]; found {
		var XDeviceId DeviceId
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-Device-Id, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Device-Id", valueList[0], &XDeviceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-Device-Id: %s", err))
		}

		params.XDeviceId = XDeviceId
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter X-Device-Id is required, but not found"))
	}
	// ------------- Required header parameter "X-Session-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Session-Id")]; found {
		var XSessionId SessionId
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-Session-Id, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Session-Id", valueList[0], &XSessionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-Session-Id: %s", err))
		}

		params.XSessionId = XSessionId
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter X-Session-Id is required, but not found"))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.SearchItems(ctx, params)
	return err
}

// SearchMoves converts echo context to params.
func (w *ServerInterfaceWrapper) SearchMoves(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params SearchMovesParams
	// ------------- Optional query parameter "q" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "q", ctx.QueryParams(), &params.Q, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter q: %s", err))
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", ctx.QueryParams(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	headers := ctx.Request().Header
	// ------------- Required header parameter "X-Device-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Device-Id")]; found {
		var XDeviceId DeviceId
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-Device-Id, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Device-Id", valueList[0], &XDeviceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-Device-Id: %s", err))
		}

		params.XDeviceId = XDeviceId
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter X-Device-Id is required, but not found"))
	}
	// ------------- Required header parameter "X-Session-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Session-Id")]; found {
		var XSessionId SessionId
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-Session-Id, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Session-Id", valueList[0], &XSessionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-Session-Id: %s", err))
		}

		params.XSessionId = XSessionId
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter X-Session-Id is required, but not found"))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.SearchMoves(ctx, params)
	return err
}

// ListNatures converts echo context to params.
func (w *ServerInterfaceWrapper) ListNatures(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListNaturesParams

	headers := ctx.Request().Header
	// ------------- Required header parameter "X-Device-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Device-Id")]; found {
		var XDeviceId DeviceId
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-Device-Id, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Device-Id", valueList[0], &XDeviceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-Device-Id: %s", err))
		}

		params.XDeviceId = XDeviceId
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter X-Device-Id is required, but not found"))
	}
	// ------------- Required header parameter "X-Session-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Session-Id")]; found {
		var XSessionId SessionId
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-Session-Id, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Session-Id", valueList[0], &XSessionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-Session-Id: %s", err))
		}

		params.XSessionId = XSessionId
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter X-Session-Id is required, but not found"))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListNatures(ctx, params)
	return err
}

// SearchSpecies converts echo context to params.
func (w *ServerInterfaceWrapper) SearchSpecies(ctx echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params SearchSpeciesParams
	// ------------- Optional query parameter "q" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "q", ctx.QueryParams(), &params.Q, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter q: %s", err))
	}

	// ------------- Optional query parameter "format" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "format", ctx.QueryParams(), &params.Format, runtime.BindQueryParameterOptions{Type: "string", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter format: %s", err))
	}

	// ------------- Optional query parameter "limit" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "limit", ctx.QueryParams(), &params.Limit, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter limit: %s", err))
	}

	headers := ctx.Request().Header
	// ------------- Required header parameter "X-Device-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Device-Id")]; found {
		var XDeviceId DeviceId
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-Device-Id, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Device-Id", valueList[0], &XDeviceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-Device-Id: %s", err))
		}

		params.XDeviceId = XDeviceId
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter X-Device-Id is required, but not found"))
	}
	// ------------- Required header parameter "X-Session-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Session-Id")]; found {
		var XSessionId SessionId
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-Session-Id, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Session-Id", valueList[0], &XSessionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-Session-Id: %s", err))
		}

		params.XSessionId = XSessionId
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter X-Session-Id is required, but not found"))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.SearchSpecies(ctx, params)
	return err
}

// GetSpecies converts echo context to params.
func (w *ServerInterfaceWrapper) GetSpecies(ctx echo.Context) error {
	var err error
	// ------------- Path parameter "key" -------------
	var key SpeciesKey

	err = runtime.BindStyledParameterWithOptions("simple", "key", ctx.Param("key"), &key, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter key: %s", err))
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetSpeciesParams

	headers := ctx.Request().Header
	// ------------- Required header parameter "X-Device-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Device-Id")]; found {
		var XDeviceId DeviceId
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-Device-Id, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Device-Id", valueList[0], &XDeviceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-Device-Id: %s", err))
		}

		params.XDeviceId = XDeviceId
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter X-Device-Id is required, but not found"))
	}
	// ------------- Required header parameter "X-Session-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Session-Id")]; found {
		var XSessionId SessionId
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-Session-Id, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Session-Id", valueList[0], &XSessionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-Session-Id: %s", err))
		}

		params.XSessionId = XSessionId
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter X-Session-Id is required, but not found"))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetSpecies(ctx, key, params)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) *echo.Route
}

// RegisterHandlersOptions configures RegisterHandlersWithOptions.
type RegisterHandlersOptions struct {
	// BaseURL is prepended to every registered path so the API can be served
	// under a prefix.
	BaseURL string
	// OperationMiddlewares lets the caller attach per-operation middleware at
	// registration time. The map key is the OpenAPI `operationId` value as it
	// appears in the spec (the raw, un-normalized form). Operations that have
	// no entry are registered with no extra middleware. A nil map disables
	// per-operation middleware entirely.
	OperationMiddlewares map[string][]echo.MiddlewareFunc
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{})
}

// RegisterHandlersWithBaseURL registers handlers and prepends BaseURL to the
// paths so the API can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{BaseURL: baseURL})
}

// RegisterHandlersWithOptions registers handlers using the supplied options,
// including any per-operation middleware.
func RegisterHandlersWithOptions(router EchoRouter, si ServerInterface, options RegisterHandlersOptions) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(options.BaseURL+"/api/pokedex/species", wrapper.SearchSpecies, options.OperationMiddlewares["searchSpecies"]...)
	router.GET(options.BaseURL+"/api/pokedex/species/:key", wrapper.GetSpecies, options.OperationMiddlewares["getSpecies"]...)
	router.GET(options.BaseURL+"/api/pokedex/moves", wrapper.SearchMoves, options.OperationMiddlewares["searchMoves"]...)
	router.GET(options.BaseURL+"/api/pokedex/items", wrapper.SearchItems, options.OperationMiddlewares["searchItems"]...)
	router.GET(options.BaseURL+"/api/pokedex/natures", wrapper.ListNatures, options.OperationMiddlewares["listNatures"]...)
	router.POST(options.BaseURL+"/api/calc", wrapper.CalcDamage, options.OperationMiddlewares["calcDamage"]...)
	router.POST(options.BaseURL+"/api/calc/bulk", wrapper.CalcBulk, options.OperationMiddlewares["calcBulk"]...)
	router.POST(options.BaseURL+"/api/calc/reverse", wrapper.CalcReverse, options.OperationMiddlewares["calcReverse"]...)

}

type ErrorJSONResponse Error

type CalcDamageRequestObject struct {
	Params CalcDamageParams
	Body   *CalcDamageJSONRequestBody
}

type CalcDamageResponseObject interface {
	VisitCalcDamageResponse(w http.ResponseWriter) error
}

type CalcDamage200JSONResponse CalcResult

func (response CalcDamage200JSONResponse) VisitCalcDamageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type CalcDamage400JSONResponse struct{ ErrorJSONResponse }

func (response CalcDamage400JSONResponse) VisitCalcDamageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CalcDamage500JSONResponse Error

func (response CalcDamage500JSONResponse) VisitCalcDamageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type CalcDamage503JSONResponse Error

func (response CalcDamage503JSONResponse) VisitCalcDamageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type CalcDamagedefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response CalcDamagedefaultJSONResponse) VisitCalcDamageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type CalcBulkRequestObject struct {
	Params CalcBulkParams
	Body   *CalcBulkJSONRequestBody
}

type CalcBulkResponseObject interface {
	VisitCalcBulkResponse(w http.ResponseWriter) error
}

type CalcBulk200JSONResponse BulkCalcResult

func (response CalcBulk200JSONResponse) VisitCalcBulkResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type CalcBulk400JSONResponse struct{ ErrorJSONResponse }

func (response CalcBulk400JSONResponse) VisitCalcBulkResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CalcBulk500JSONResponse Error

func (response CalcBulk500JSONResponse) VisitCalcBulkResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type CalcBulk503JSONResponse Error

func (response CalcBulk503JSONResponse) VisitCalcBulkResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type CalcBulkdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response CalcBulkdefaultJSONResponse) VisitCalcBulkResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type CalcReverseRequestObject struct {
	Params CalcReverseParams
	Body   *CalcReverseJSONRequestBody
}

type CalcReverseResponseObject interface {
	VisitCalcReverseResponse(w http.ResponseWriter) error
}

type CalcReverse200JSONResponse ReverseResult

func (response CalcReverse200JSONResponse) VisitCalcReverseResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type CalcReverse400JSONResponse struct{ ErrorJSONResponse }

func (response CalcReverse400JSONResponse) VisitCalcReverseResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CalcReverse500JSONResponse Error

func (response CalcReverse500JSONResponse) VisitCalcReverseResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type CalcReverse503JSONResponse Error

func (response CalcReverse503JSONResponse) VisitCalcReverseResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(503)
	_, err := buf.WriteTo(w)
	return err
}

type CalcReversedefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response CalcReversedefaultJSONResponse) VisitCalcReverseResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type SearchItemsRequestObject struct {
	Params SearchItemsParams
}

type SearchItemsResponseObject interface {
	VisitSearchItemsResponse(w http.ResponseWriter) error
}

type SearchItems200JSONResponse []Item

func (response SearchItems200JSONResponse) VisitSearchItemsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type SearchItemsdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response SearchItemsdefaultJSONResponse) VisitSearchItemsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type SearchMovesRequestObject struct {
	Params SearchMovesParams
}

type SearchMovesResponseObject interface {
	VisitSearchMovesResponse(w http.ResponseWriter) error
}

type SearchMoves200JSONResponse []Move

func (response SearchMoves200JSONResponse) VisitSearchMovesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type SearchMovesdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response SearchMovesdefaultJSONResponse) VisitSearchMovesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type ListNaturesRequestObject struct {
	Params ListNaturesParams
}

type ListNaturesResponseObject interface {
	VisitListNaturesResponse(w http.ResponseWriter) error
}

type ListNatures200JSONResponse []Nature

func (response ListNatures200JSONResponse) VisitListNaturesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListNaturesdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response ListNaturesdefaultJSONResponse) VisitListNaturesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type SearchSpeciesRequestObject struct {
	Params SearchSpeciesParams
}

type SearchSpeciesResponseObject interface {
	VisitSearchSpeciesResponse(w http.ResponseWriter) error
}

type SearchSpecies200JSONResponse []SpeciesSummary

func (response SearchSpecies200JSONResponse) VisitSearchSpeciesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type SearchSpeciesdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response SearchSpeciesdefaultJSONResponse) VisitSearchSpeciesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

type GetSpeciesRequestObject struct {
	Key    SpeciesKey `json:"key"`
	Params GetSpeciesParams
}

type GetSpeciesResponseObject interface {
	VisitGetSpeciesResponse(w http.ResponseWriter) error
}

type GetSpecies200JSONResponse SpeciesDetail

func (response GetSpecies200JSONResponse) VisitGetSpeciesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetSpecies404JSONResponse struct{ ErrorJSONResponse }

func (response GetSpecies404JSONResponse) VisitGetSpeciesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetSpeciesdefaultJSONResponse struct {
	Body       Error
	StatusCode int
}

func (response GetSpeciesdefaultJSONResponse) VisitGetSpeciesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response.Body); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(response.StatusCode)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {
	// CalcDamage 1 vs 1 のダメージ計算
	// (POST /api/calc)
	CalcDamage(ctx context.Context, request CalcDamageRequestObject) (CalcDamageResponseObject, error)
	// CalcBulk 防御側の代表調整すべてに対する一括計算
	// (POST /api/calc/bulk)
	CalcBulk(ctx context.Context, request CalcBulkRequestObject) (CalcBulkResponseObject, error)
	// CalcReverse 観測ダメージから相手の調整候補を逆算
	// (POST /api/calc/reverse)
	CalcReverse(ctx context.Context, request CalcReverseRequestObject) (CalcReverseResponseObject, error)
	// SearchItems 持ち物を日本語名で前方一致検索
	// (GET /api/pokedex/items)
	SearchItems(ctx context.Context, request SearchItemsRequestObject) (SearchItemsResponseObject, error)
	// SearchMoves 技を日本語名で前方一致検索
	// (GET /api/pokedex/moves)
	SearchMoves(ctx context.Context, request SearchMovesRequestObject) (SearchMovesResponseObject, error)
	// ListNatures 性格の一覧(補正する能力)
	// (GET /api/pokedex/natures)
	ListNatures(ctx context.Context, request ListNaturesRequestObject) (ListNaturesResponseObject, error)
	// SearchSpecies ポケモンを日本語名で前方一致検索
	// (GET /api/pokedex/species)
	SearchSpecies(ctx context.Context, request SearchSpeciesRequestObject) (SearchSpeciesResponseObject, error)
	// GetSpecies 種族の詳細(タイプ・種族値・特性・覚える技)
	// (GET /api/pokedex/species/{key})
	GetSpecies(ctx context.Context, request GetSpeciesRequestObject) (GetSpeciesResponseObject, error)
}

type StrictHandlerFunc func(ctx echo.Context, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// CalcDamage operation middleware
func (sh *strictHandler) CalcDamage(ctx echo.Context, params CalcDamageParams) error {
	var request CalcDamageRequestObject

	request.Params = params

	var body CalcDamageJSONRequestBody
	var err error
	if binder, ok := ctx.Echo().Binder.(*echo.DefaultBinder); ok {
		// Bind only the request body, so that path and query parameters
		// are not also bound into the body struct.
		err = binder.BindBody(ctx, &body)
	} else {
		// A custom binder is installed on the Echo instance; defer to it
		// entirely, since echo.Binder does not expose body-only binding.
		err = ctx.Bind(&body)
	}
	if err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CalcDamage(ctx.Request().Context(), request.(CalcDamageRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CalcDamage")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(CalcDamageResponseObject); ok {
		return validResponse.VisitCalcDamageResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// CalcBulk operation middleware
func (sh *strictHandler) CalcBulk(ctx echo.Context, params CalcBulkParams) error {
	var request CalcBulkRequestObject

	request.Params = params

	var body CalcBulkJSONRequestBody
	var err error
	if binder, ok := ctx.Echo().Binder.(*echo.DefaultBinder); ok {
		// Bind only the request body, so that path and query parameters
		// are not also bound into the body struct.
		err = binder.BindBody(ctx, &body)
	} else {
		// A custom binder is installed on the Echo instance; defer to it
		// entirely, since echo.Binder does not expose body-only binding.
		err = ctx.Bind(&body)
	}
	if err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CalcBulk(ctx.Request().Context(), request.(CalcBulkRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CalcBulk")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(CalcBulkResponseObject); ok {
		return validResponse.VisitCalcBulkResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// CalcReverse operation middleware
func (sh *strictHandler) CalcReverse(ctx echo.Context, params CalcReverseParams) error {
	var request CalcReverseRequestObject

	request.Params = params

	var body CalcReverseJSONRequestBody
	var err error
	if binder, ok := ctx.Echo().Binder.(*echo.DefaultBinder); ok {
		// Bind only the request body, so that path and query parameters
		// are not also bound into the body struct.
		err = binder.BindBody(ctx, &body)
	} else {
		// A custom binder is installed on the Echo instance; defer to it
		// entirely, since echo.Binder does not expose body-only binding.
		err = ctx.Bind(&body)
	}
	if err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CalcReverse(ctx.Request().Context(), request.(CalcReverseRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CalcReverse")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(CalcReverseResponseObject); ok {
		return validResponse.VisitCalcReverseResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// SearchItems operation middleware
func (sh *strictHandler) SearchItems(ctx echo.Context, params SearchItemsParams) error {
	var request SearchItemsRequestObject

	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.SearchItems(ctx.Request().Context(), request.(SearchItemsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SearchItems")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(SearchItemsResponseObject); ok {
		return validResponse.VisitSearchItemsResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// SearchMoves operation middleware
func (sh *strictHandler) SearchMoves(ctx echo.Context, params SearchMovesParams) error {
	var request SearchMovesRequestObject

	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.SearchMoves(ctx.Request().Context(), request.(SearchMovesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SearchMoves")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(SearchMovesResponseObject); ok {
		return validResponse.VisitSearchMovesResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// ListNatures operation middleware
func (sh *strictHandler) ListNatures(ctx echo.Context, params ListNaturesParams) error {
	var request ListNaturesRequestObject

	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListNatures(ctx.Request().Context(), request.(ListNaturesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListNatures")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(ListNaturesResponseObject); ok {
		return validResponse.VisitListNaturesResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// SearchSpecies operation middleware
func (sh *strictHandler) SearchSpecies(ctx echo.Context, params SearchSpeciesParams) error {
	var request SearchSpeciesRequestObject

	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.SearchSpecies(ctx.Request().Context(), request.(SearchSpeciesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "SearchSpecies")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(SearchSpeciesResponseObject); ok {
		return validResponse.VisitSearchSpeciesResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetSpecies operation middleware
func (sh *strictHandler) GetSpecies(ctx echo.Context, key SpeciesKey, params GetSpeciesParams) error {
	var request GetSpeciesRequestObject

	request.Key = key
	request.Params = params

	handler := func(ctx echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetSpecies(ctx.Request().Context(), request.(GetSpeciesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetSpecies")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetSpeciesResponseObject); ok {
		return validResponse.VisitGetSpeciesResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// Base64 encoded, compressed with deflate, json marshaled OpenAPI spec.
// Stored as a slice of fixed-width chunks rather than one concatenated
// const string: with thousands of chunks the chained `+` fold is several
// times slower for the Go compiler than parsing a slice literal.
var swaggerSpec = []string{
	"7H15UxtJtu9XydC7HSExAgmw/aKJ8B/dZu7Yd3pxND133ou2nymkwmgQJY0Wu3mGiKoSmN3QeMEYvICx",
	"AeMWdntpjGwTMfeb3KRK4lu8OCezqrJKJSTabr+4E/ePmRZSLiczT57ld85JXwnEUgPplCIruWyg40og",
	"LWWkATknZ/CvTvlSIiaficPnuJyNZRLpXCKlBDoCVN+mhU2qr1F9lRZe0MJ4+cZ9c3yOasXy1ra5vEX+",
	"8pcznYFwIAGt+2QpLmcC4YAiDciBjsD/amYjN5+JB8KBjPz3fCIjxwMduUxeDgeysT55QII5c4NpaJ7N",
	"ZRLKxcDwcDjQJWeziZTiT1KJFgpU/5UW1mnhRR0C+EBHpWAYGmfTKSUr4w79MZNJZeBDLKXkZCUHH6V0",
	"OpmISUBW5G9ZoO2KMOK/ZOTeQEfgf0ScjY+wX7MRNhrO4l3bBmx34S1uAm8Oo33Rk0gmcoN4dJlUWs7k",
	"EoywRNyHfLb+f6uxt84u/ADd7cbnw1bjVM/f5FgOxvkyn+w/JSVj38l/z8vZXPX8Ui4nxfrlTL0ln1Hi",
	"iUuJeF5KBnDVvbISlzNdaTmWkLN/lgfr9RdaDocDvQk5Ga/X5V+hUVdOysnYJZUZkHJ1+7BWw+FAIicP",
	"/LuUSUj8xrgPyvi1SLUFc2mPauNUe2xu36i8LVBtkepT5rRGtZXyxCY50xksL2vlm4/MRZ1q2+WXD6hW",
	"bD1Q71B9MhRgU+DYSj6ZlHqSssWXVcfJv5AyGQnXP5C6xK9rVdMUkpitt1A41G950+FwIJ2Rs7LfQvff",
	"7VHt6sHtX4z3K4b2khYWaOEJv4KFcaptVFamqVY8eHDV2J2lqs4WTLWN8ubuweiMMb4Q7P7hfHeIatvG",
	"3DTVblNtnaqaOalSrWiMXz1YuUe1LWNvGX+6by6sGsU7wvhbVHtC9Smq6ueU8sRmee4qdt0mx8l+6XVQ",
	"SSlymPSlw6Sv50JPKpXNwSf8qzefTIaoqkG/N2Zxsla/uN0vjn85/ZqajLUJY/oW79nm6hmiWpFqe01N",
	"SJo5PQZ0awtUu0+1DarNUG2banfZ1lBtC7ZJn6/s3aDaYtBZ99w41WdhidqId2t13Rp0k2qTVJ9knUM4",
	"H9tLwo6NUH2+zVi6t196tL8zacxtUV2DPdM2yLFolHTH80xQyRdY+24cQlYuJhSZwDL0Laq/ofoeLTzw",
	"UGEU75Tfbwa7ztJCyVTXzQdvqT6/XyqZI7NU2zKf78JU2n2q61QrwiGTL86eIbCysV2q3eQrg+lEfj+M",
	"MTu5aDiLpFYzv0eA8WsddgSRr3Sxr8zhQi6bT/rIuA+VVpnUZSarG1m/TUzqct3F+y4UZzt0manLtdfY",
	"CHnWEVli0ldLa9epVuTCwZYeWtGWjkH7EzLJAvAOyEEQjHXlIePjo7MS6/eV1CMnq0murGyU13aNuZng",
	"/vspcvpLc3qb6pMkQk5/WZ54Y0zfgo/syz98WXm4bP78MBTwIS5js1E9AcwZznusfHVuch22DthT1Drl",
	"TuEwPeJ8RzWnnlY2xsvFBVBGeEDrKOQfUu2+eFKVJ3vmzZfi1WdrpoWSUbxv3nxmqGuhQNjDR4qUy2fk",
	"eov/Blt9nYonehOMj1g/P05ivxCQZsF0Mp8Nk4GEks+GCNWm93fUythLpndp4R6XYlqR0UvOdIJGGlnh",
	"hGvbVNXEZvZPtmg7p5zpBJFo3h5Dub2+v/OYam9AMy2rxvhdlJYg66iqVzZ/Md5d50qfDaBNC8NvlUdW",
	"qPYT1aep9gx52xKEdfk7m0bbKpn8tjfQ8UMdWZOTcl8mU7H+wPB5rz1ZKbwzJpdo4S5Y8Gi+4+g5KZf9",
	"OBPYnBD86tLxKLCGOrX/7rqhrrW3hqoYO5sOWCcdEI7cosiPnUU7pUpoxTKJXCIm8bvcK+G165WSWdlL",
	"p6k+MidU57b2pFJJWVKQQt85fyeD92i9PoGZ61iSVXZf+cYGZ+5JNWgtu4V1IFQfp/qkMfLEGB33lYK/",
	"xQ49gm4/XKMfps3BELqYygw2fgG+Tl2ST1m9qu+ALT1Fozb41y+6vibGaqF8E1QgcSgCScZNYVX/q9wD",
	"csy4N0X1eWP0ubk8waUZGFVaSOSd02cFgz+h5OSLTHTKvb1yLJe4JCtyNuvnL+/h7V8oL+2Y6nowGibR",
	"lrbj8P/Hw6Q1TNrC5BgcocU6gXgqD8LJ3lclP9DDpupP1TvPP397qk9SYsiLA9KPndKAdFH2p3tA+vGs",
	"nIlxb9pzX5dVY22dFlRaWKGFt1TfQWsCFPRnQVtLkdNn0dbcfs82zZj4xZgbBwvZeDZr3nxWfvq0df/d",
	"TDDa0vqZMV6i2l6IuR9o2y8tmTMb+7s3jNFHTU1sgOAXnd81R6OtUfKP9XZmabdGo2BfV16PgqunTxkP",
	"XoLVrm3v70weLM5Rbd0YH6P6BNXugHZBk59q76n2nhv7YEy0tv/Pligb70C9ynSvMfoIZLNWrDx+Ye48",
	"/SzY/W1PVs5cQkChJc12pptESDf//L2s5Pqy4EptgDc1/sh8rBt7ryyl0sDxDSSUQw8koRx6IM9mf98D",
	"gX2cNGc2qPa4qQlOg6rT5rK6/+4aWJOgRmdxo0eM0UfoE86AM7J31yiOl++MgMJd24V58epQVa8+TPPm",
	"S/Pms8+otrW/swONtMdUm6L6BCMP3U1w4Qx1DejStm0H5vRZYm7fKF8bY+3LSy/Na4/M5zp3tdwOFYH1",
	"EWPm9v67GTAmcNZgDs8vRPV50holwDgTvzDBQbUHYChoRT6vqvUmUxJIivXK3k/7b98iVaIr1cBhZ1LJ",
	"pI84aD1BzOKrgzvXqFbcf/McVi0cavDg7j1zZ8l49pMLoPC9vGfYr60nkHOEv7xoRTYn9Rwil5gR56+b",
	"RXXAFiRysShiXOzrEi4uCeoVl5y6sKMWUMr5KRWPO1G1INF43i89rKxscBO6os7tvxlFc3USTER96uDB",
	"VWDILrgt29VGmo8xZSztGsU7nIu5sVmk6rRj3aozTCiZt8doobS/M3WwOMNdK1Wj6vQfvow0f8FaMUrt",
	"tuaNkjlfsHoU0XXb8LI0W/Wf5UGuv8CTuDVm/LwAEE88FctGpHgmEo1GP2/uySf7m2NSMtbMYaWWgTj5",
	"x3oro76ZdAOG0t1ByiMrzJ0K4kYgqYWSvSIUG6MbTJ9iv750d4flggVPnyXtbXXac0you8PruNm9xa0g",
	"uEUwDEOa+BjdHbYz6OnmQ4CrJ2JJ3R22A+nbvT4F8apVdHpWUZ54c3D7F2uMTnsMwL34GNC707t12M13",
	"FUJPexWdnlW4uh9KAVw7JT8AtxjOPhAO9IErYJ0PfmR/w1zwKe78Emd/4y/nfSxNG5uvgaWDBF5+at4a",
	"AzH+/fdnCThohavwC4igN4A8dMdScbmbMOEOsJb2HhQQDn0qFccrYGy/N/aWKysbjI+7B+RsVrqIvbbN",
	"hUfm8tPKk3voOD81b19jcvxPKex5dfSgsGEWRo0Hz4MW1FbA2ErJuDdlzM2AVuDAnUvOe0zXVFxuKLYA",
	"JKOUZiTWjwPgyE57P/HnDFyNhhcnHPTT3nb9Bfx/YQLMXMcYDjKZErksZQekdAJlC4zaRIziHdBGtt5u",
	"Jf9YP04LpX+st7aD0VN5cs94t8jsZADRmbLmtgMa1Mbac/MmIknsnLUNgjODrsUGBNbZ1ERsXNky+E6w",
	"Mz2nuMz2DTZTxzllCHuSIWKOzBo/vSBDbIahc8pQc3Oz/T9omFAuSclE/AKEhMgQ+beub78haLItUO2x",
	"8XASDZnHcMb6FIkQMP21aREIDjJ7ASRx4SbVH+IubsFGalvcTuHMoobIEEK8OHFe6VdSl5UL6DWSIWI8",
	"+qn8coQvVRvxDCb2tEiGOwodxxfM6cWg8W7VeDtLCyVbUwO7rm0a6iJ86aGtUCpPvjZHp8o3nxk7OyHL",
	"mJk2l5+U7z/ymy2hpPM5mA4NYXNtubLxlmmCYnl7xFj6BaabG69sjCNsswm6UWcQzlNaWIR5Vc0GXpjp",
	"+YRqm76bwpHyIcLocaGSbshb7O1FzskQqR0KKR6MzVTWxvyW2khvBrWjlTBj/vzQb5iMfEnOZOUL2QTy",
	"ou1KEPwCNsGydEiEWE4zQZW+SbUVNJ7XEb8ChhBnUFIXUo73QYYIc0qoNt26X3pNdR2xrBE/ovz7Fa3g",
	"BV9OkDsxJEJc7gyJkDgacIzMFaqPUe0q1TZbqcZscMa7JcYSxtot1/GClLoQ65MyuQsDiWw2oVwkQ8Tj",
	"8VZWNqg2zRYQ5IIBbXsLqmMmmyU8niAh6wfqHWNnB8yzV79iOAfoCPltgENDjbkPO1qLP2EQMkSEXgw+",
	"HLEHdE+dkzOKlCRDZH9nsrJxe7/0yFi7Za8iaCzdM95vMolM0pKSiBGX0DjORjqn8P3g/gfDNo8m7/i+",
	"X2CxdzJEhKg/iRAxBE/sc4AD3dwNQuyecDmjFZkIAPF9UcrJlyUwNacRob7qe6ezLOxBhkjWDoAQPwx2",
	"xK83wEdkiFh4VqPdwCciQ4TFPRrvJrEAPhki/NNROnMIfIhYkGn9rkoqd6E3lVdAEaCEfotShm8/iRAW",
	"oKH6K/zpOgylFc2pUePddcZJ5vWZ/XfLOOYxNuaAlM3JmQt5RbokJRDAxsEtMvR5Y1Yvj67j7ZqxZczx",
	"aDtfTTqby8jSgGcA56zB9trfmTJfaVWUbRnPJ6EBU5Bn25vbQs7QgnUpKt9AOOBSiYGw/TM2Dwdcmkho",
	"bgdgvPJf6FP1hSicA+GAW6IK7dzfVgswoanzo0AcfIltmAhAx1e8gUJTfi2Eb4DbhT+Bi4U/OWsK3zhg",
	"vcVPMF8VH0APn9P1NdcFvLomuN4Vy8hyffDYaiZmlBy5Z07OZKSEUq/H97zZcDhwWZZyffWx/L/yZr4x",
	"hn+1cXo7cBGAQ8S9tLjZ/oKjPH7bKUQMqiOaPM63xbI4GJxg4Q4bdpCMXz07lgM3+dk1jOADiFflhtgS",
	"rKHcFSdCXLdpUr4ku4M5x6MI5SQG8gP8j4Ti/OEDS9UIZzCIAxU9i3ZCGkkjkTgxLln1Y0ZS+uuy2neS",
	"0s/DZ79nYA/Aj7kREm1paW+jqsYMZ3IuH422x06SEyfY7L8tgQHCc/n6dwpbnUop8QRSye6W9D3uWqOL",
	"Ppvql7HH8Hnv6VRHE4WsBzGYmPb1XwGg/OT5c3Y4pIojy6u7zOGNMBRWKS/uVjv82LkmKO/Ac+UbiFmr",
	"+sW8lJGUnCyjjUAwGMpMa0xKUrW+RC5LjKV74BOr81RbovpUeXW3fG0s+BmgEBYwDv41i2CcU7iXHD0R",
	"qp4BTsY1ASYrjVPtBcGpTpJokE/ETGinrbZNouh2NzWVb5QO7q5aeUOLHvy9qSnItsuyzrdI9DOCkMAa",
	"i0FArpE+7cTNIDzPf9ii2vY5JZ7IppPS4ClxQ8EkZsLgCLC630A+p+teD1WnD993dQbuL/gbWxbdaETp",
	"U9ZW6Lg4RGYx6IGW8qIVe6gVXvGNgjTXOJkOEoUfhQM+icfLN58opLy4G+ogrdFoC7aEaJc+zXyPDhLz",
	"7q07DLIlBtwYcvNDtKU1TD7/vOXz8xg2mr3GwinnFEKsEwcoe8aYBZQcAJnZW1SfPIDMsnFGtRXt0aIt",
	"UUR8kDqCvAMWbhv6kVv7u+MIhsCOhRo9a2cnGguIgW9N/A4awaYJcTPhuod8Yh7hAPRvLCDKxl9kN8LY",
	"G608BvSQq7qlexBzipKTxHXGgWqt6RFpOL9r7TWY3k/eQaj88JB744H28JGFcziQTl32S3syNjRjcimI",
	"bGHndEZYTEXcU7/tAZmcSGV49rVtmfiaHzmu6xrTcIfoEj6UKyzF1lZr108Je2zZj+m+wSzmx3DVzz4x",
	"Ze5nS35jJ2/5KUn5R2kgDco4IAFkg5G1qiEwN+toNg4aGdVZFRiO4nGO5tYoKidjdgEzqqa4/SNkd1lA",
	"IMsirDLtXGzjrAQFyG2Mwj6n+qTfiiDn7OMsCGIjfEF/+PAFHdESYWd7Kin55Ygc3Fo9UB9WxUWcQL4r",
	"AVArWmUhb4KKnM9lpORJm2wA+JL57EnfIQlbt6qLpwvhk2ur5ZerdpRbDBex8QP8HGpzrZ1MWC063bSb",
	"61MH6gNmLcGYaMUAXVTVkHvxC+A4cvgBYbh1xbz1xsntAwxanzenx1AsX2eZGodFdD7gulTxdzr5kYby",
	"pqPCuNbN9mMtIW/FJ9+gvLhLtddUv26nusDGN4AGNzV58eCmJra7aAl683W+a2PWTZQY6hQtlNrgvywl",
	"XoSP4UJhVrwPHgOJ8VbwhSHPPHuTJfG0tRwPubr+Lcv6nFOsTBgnzavFSUew4hLexB2MEDJ7u/J41pgY",
	"Azvl/V3j59v2TTCmdw9uXafaenl0HdOObIuvipXidmaP+wAwLlI0ivfL+hsWVmKnEKyMPTHGr0L4gDVh",
	"eR8HY7Oc3IDgbbf6aTsllZNrmb6YPFhExboKxriFRMClebdnx7p8BW7NHCQre8daQfmX98buY9L6WSgg",
	"wASt0Wg9yl1MVz2Ry5p22Faf903ssbOGGHqOvHLseEv7Z+Q/r86TY8fbvdTVIc8PLrKNBkG7K2DAgmTs",
	"TSBEd1nKIfonJ+VYLpOIgRGXkTDHJRGTsd3FvhxDGNOpBENIL2Y4qNebHOQ/ZQdjfdi7J38R6wli/dCw",
	"j4Xj4xnpIvaMS5l+NCdkzE7vlRKZQV/57AAgVRttR/UsPX+ipeUP6GUiS25jjcB9m1W8YGG/1yKzd/mE",
	"sMXNJ/xYIC73fkDvbFr6oN7xD+ot/+befrz1HQOuT0lKPBGX/K60oS5WHi5DJDBoZcpz/U/+Y4E4hRwu",
	"Z/O79urqAPlHKeZzsQcS2QEpF+sjJ9EnHd2wL5yTS4HOsL/HVKsG5ePUmhyWppqRlItylhijGwCsApVF",
	"s/DC41QYkPtVZOmiQa4ovBmREOoW3WNVFzWJTYGTO8zicqGG8z4/zhKm6ixByOD0LCGhfOgSGIv4gNw8",
	"4oz6RrtD9emgr5RWdeb+FaeNUQiv1mYtUcV9UDmLbW3X78ya/n6FMEGxLqhFiCPyw2AGCLOgjlQxQ45e",
	"MCNewYZLYhif1jz+KlFBWCbJwdJVY248yMkrlPZ359Hn24Jq3ELp4M5D89oj29wyH70y1tYP1Ifl13eY",
	"6YVIojiyYBVWfr17sLTKgSCtSLrONlrk2HX2O1gOv5tW6qxP5mz6VCp/yK3FEtItTFabdtZs3nzmy8zZ",
	"fDqdyhw2WhFCCDjIujE3UmtraeFnnvejFY3Sa6q98Z/R40eId8K/DIgLcvuwnQ0Ic9UhCAJnPbVTf8/X",
	"Vnc1C3w+UW25rW59eBqyQCamxGpJTKcCJRw80wksCdeFVB5rWFO+DXnyHg2nzjjF2IWSXYwN1+4H6Hze",
	"ufofVImOYeLGvU6xvqkKITEXVllqlqG95N4JyyPjYUuIrJ+0M5wYpsqanXTie6qGzYTsJ6GZk34FYgdp",
	"twua3I5JkBd927+ui34nk5PcOvCepGOWeSQVRlPYMTJHjJeQcM1UHlkxxl8fLM6JjteRopyWKhSr0ItQ",
	"vVV751gDqmqeDXNYcFL1r+9y3GY/D4pp+EkVc/jgs/Hgpf2ZHTRGY4VakfFHVAUzAxED2BPIPLO8dXc6",
	"RXejglaEJuoJ29/2cgJsbd0QMBM5XQmWlcuTK9zl5A2iNk6f6vtj5QPCbtrnV94omguzGPR3avgLJUFe",
	"cPTN2H5feb5i57+ZOyt2AX/tyjye7ILrCfitzGZWD8ccKpn9C/ekbDY/IMdPp7vSPvWKpaKdgmyvnZwm",
	"TC8HLd4/2d4m8PrJqMdlafW3AmOHyOqvLd+FmRjo83cxxUQOFmfsr86iIhO/YlmBBw+uulCsY6FGebvK",
	"b/MRz6g1a9gQ+BtcdyaSmOEQdAk0YpW3TRkTM/578xv4HyIQHwNRt/gdztwXbg66nxnZsPJkXUn+PmXK",
	"jKmRzLCL7Vwb6uKLQ/i5K+GXM2+n5IrV9lSfFy8x1aYczt3fucZcMiblhQzfk5XVLfGnkICfC/WyVnNf",
	"kMaySKvoZCYlM4aD+zsr5a1tJ5O0Gs+WfuT/Yeqrva2uLksoR+rhOSvojlrY9wSEbDCPLMlnUhnp3+WE",
	"b+14NcSQBOiMjdZYh4zcCzBcI439MBkuQTvlnJRIHuGusG5d+YEBCUOoV3xTt/gfDUkZ6+UpH+HSI2Xl",
	"LustgQYzmSDJS8oovgV0lcd3WI0tu7bgWYJf+3jdpxSxlkXqYQ+HxLCw9mpWOe/sOdfHbtKuGEsvDn76",
	"qXzziTH76zFzRRtuvoIVEJuYXPugHb4KhIXIYvTYseOQMwNXRMrl5AwM839+iDZ/fv7KseFm9qF9+F/8",
	"bCvPMfo81vLjNyn/ukzQzH44q0MqW4OvLO8/amLYIZF4+KJxLnOC4mJpaduhFpvnqPvR2mBbw/fBE073",
	"l9IOc1Zt24mqiCgUtQSZSQURROEpFFoodZ1lkROwakefl29shGph1jXh6Oof+tL+33MEuia4XBM3rpf+",
	"kUZV0c/KZgNsIjYqG6LWHvJ7YymeI4wjML4nhVCUnlbloKeQsCefwViYlJGSg9lEVgxu9Ejx5OAF+89s",
	"UpaBqt6MLP9ffwK+d5KB603sDbMMMnAiNyjEUPym+KuTPVxvimxeQTAEdVxWwjhNVkld9hkXjjGh9Kb8",
	"7v5dqj+HMBzkiWq08BA/3KD6E/ig77K6RozWOYgvD9gVSub6VHl7AvLwC8zIeAtPfKH/u1+6aa7fNkbH",
	"KyvTQZZtRf73F19/hS9a3Nje3wEpzitK/5QK/jHWlwpFCFzzLqSPREjX5URvjr1BZlUL6vPWE5N2rPOc",
	"Aj8UVliya+XxbPnlSPDUV1/8pfOPLQPxUAfkokHJNOEZPapmV06T9lb7W706a5aBXduk1XPTWboVK23l",
	"qbQnTvDkOU9TqiMapm2Trr7U5XjqskIYhcL7bkukLx2Rcv2RuNwbyaalSDYdj2TTMh+x8mQG0/kYcgNF",
	"zFgbtg21lDAZvIPHnts80xkUymswoux+DhMbOBU3mNFZug22oyt0nEvkUEulU/0yVGrDmQbCAbBXGddE",
	"W1pboswrlhUpnQh0BNpboi3tTJ2xoGlESici0Bv+SKcYmAbSDn08ACjwIRa7QF98dLSGIeM0idiPkg6H",
	"67Z1ngsdPs/EmZzNfZmKD360JzvFN4GG3TKTp1+43gtti0Y/8tT8pbCqJ0PZRS2/mjPvLcN5HYtGaw1o",
	"U2g9QBoOHD9i6/YjtLalW4M9EKHmFk+glVzKklbiK5WAf6WLWaxbBu47D11tZozA8wMiR9asBNhmNYZb",
	"XD5gSqr4iAOHTjhGBeW77FkHfGzkCX/cwf0qRAgTf95ggW+RHQrmVKvG7mM7odpKp/7cSsf1vHoZ7Obv",
	"JnQTjuBCVvV7BPW2ifVjB4F3NTuI8ComJpmC7oj0pSNWcX2kryfCC+thO48DqgZF04QI72K6e8atnvFI",
	"X9zb0/MqJu8EDdqggfgqZjNxViJk7rgfybQezal+J5OqOiupteoY+WuXFibo/65lM3Gh5sJDrRxBF192",
	"BfmISNciZpPDif7Hgti//GoE826WRKoaQ9+BlKYm1/uo2ran7pc9oNXUFOT7BPF0kT6q6lWVwjdw77Zc",
	"7Yi9gRh/e804i5DKyjRCzdukOykr1iwhmAb+dm1Ft+tPIj5dS+y3OyAshCsi3Ra00E3EYzzkRUFy6FuC",
	"QaHsvx1xO08tPoOR362GLCVWrWogyPlfXNF4X1z+xMrG8xaqn8JhSBVnw+I/neap9YyPINmdoIX4nmYd",
	"tcTrQ2trJjTSxql2P8KTTrX73ve2eHwH8EuqajbOzQjk4u3QDB3r1Ij4zkLIeZlYRKLt53pc0aPuDmJF",
	"jqZtit10esmzdzR4ur2NGBMz5iy8m0a+JI5W6+RIPStgC3mBUCbNujG6gPKmOu4n0GohnSKtNfbUS6s9",
	"YPALgbpTv406d7ixmVhAO6oM9zFZidQ8fTrE9YADxePLTUVjdMPRSJg/WpWcMMJn0XVzWaW6Xtn7CQqx",
	"u86S/dJtbLRuKzIgChXGC1jlxwhleLmPL+s/r87DsqiquVeF6Qq/loyfFyDSC7tojG4wZemJilBV73bF",
	"JnCj7WwT4/00Kr9JXsuKQQvo4wD22MGOZvAHSmAPzJ8flldZCRk+ammHQ2bnoBJLn2da2j7sytqYefOZ",
	"dRnXy6/uwevc799SXa2tmngw4L+4dvIkT3xi5eQOENbUTewA/4lUEme1KsHlqwBs4VRbH4HXH5d/jNjQ",
	"7EXZx3fvkqVMrI+hr5+Ia8NX2L/j8fe8nBl0/hmPvwcO/ddC/DslEwOJnKujf1V5W9187PMfyNINIeCw",
	"zz7hjCoWF50THh35UPZyhtTn7YfMjLkZfKJyxrz1hmUXmmvL5ZerAldxNvJhLIj512Osr7HNfzPW781Y",
	"sM8NMRYG3T4WS02qH42ZWIJgbXb6KpHNfcPbfErt+nsfHFtTQ0eHRtfHOjrrdVE2XtBKBV60i+BCDR2b",
	"9fjM4VKAxxM/oRzw5hyKLFoUWTRY3txlyBgkx5de00IJrz7zC9ZDgbCvePhNMsVJqGrIELJSSf9JRFRV",
	"2kJdjrfy3THdi8O0H0t2uQJmH0uI8dsQudIvDw7XvBN/knP/vy9EQ5kOBGrchAwH5EGICzksyMLxtf/F",
	"tUaTDD6YAxuYiKfZ+PAZ463K5ovyy2fMoTj2qYx+m63Z7EHxFU4xAwFQfHWdFkpi+kwNEQ0TyJlLFku5",
	"12o9xFZ+NV2+8TwQDuQzyUBHIILqjg9WHVy23lDEp994agSgvJj661iWAp1MwYQcVrEIrGZG34i069+w",
	"KZRsZ4ePhr7O8Pnh/zcA",
}

// decodeSpec returns the embedded OpenAPI spec as raw JSON bytes,
// after base64-decoding and flate-decompressing the embedded blob.
func decodeSpec() ([]byte, error) {
	encoded := strings.Join(swaggerSpec, "")
	compressed, err := base64.StdEncoding.DecodeString(encoded)
	if err != nil {
		return nil, fmt.Errorf("error base64 decoding spec: %w", err)
	}
	zr := flate.NewReader(bytes.NewReader(compressed))
	var buf bytes.Buffer
	if _, err := buf.ReadFrom(zr); err != nil {
		return nil, fmt.Errorf("read flate: %w", err)
	}
	if err := zr.Close(); err != nil {
		return nil, fmt.Errorf("close flate reader: %w", err)
	}

	return buf.Bytes(), nil
}

var rawSpec = decodeSpecCached()

// a naive cache of the decoded OpenAPI spec
func decodeSpecCached() func() ([]byte, error) {
	data, err := decodeSpec()
	return func() ([]byte, error) {
		return data, err
	}
}

// Constructs a synthetic filesystem for resolving external references when loading openapi specifications.
func PathToRawSpec(pathToFile string) map[string]func() ([]byte, error) {
	res := make(map[string]func() ([]byte, error))
	if len(pathToFile) > 0 {
		res[pathToFile] = rawSpec
	}

	return res
}

// GetSpec returns the OpenAPI specification corresponding to the generated
// code in this file. External references in the spec are resolved through
// PathToRawSpec; externally-referenced files must be embedded in their
// corresponding Go packages (via the import-mapping feature). URL-based
// external refs are not supported.
func GetSpec() (swagger *openapi3.T, err error) {
	resolvePath := PathToRawSpec("")

	loader := openapi3.NewLoader()
	loader.IsExternalRefsAllowed = true
	loader.ReadFromURIFunc = func(loader *openapi3.Loader, url *url.URL) ([]byte, error) {
		pathToFile := url.String()
		pathToFile = path.Clean(pathToFile)
		getSpec, ok := resolvePath[pathToFile]
		if !ok {
			err1 := fmt.Errorf("path not found: %s", pathToFile)
			return nil, err1
		}
		return getSpec()
	}
	var specData []byte
	specData, err = rawSpec()
	if err != nil {
		return
	}
	swagger, err = loader.LoadFromData(specData)
	if err != nil {
		return
	}
	return
}

// GetSpecJSON returns the raw JSON bytes of the embedded OpenAPI
// specification: decompressed but not unmarshaled. External references
// are not resolved here; the bytes are the spec exactly as embedded by
// codegen. The result is cached at package init time, so repeated calls
// are cheap.
func GetSpecJSON() ([]byte, error) {
	return rawSpec()
}

// GetSwagger returns the OpenAPI specification corresponding to the
// generated code in this file.
//
// Deprecated: GetSwagger predates kin-openapi renaming openapi3.Swagger
// to openapi3.T. Use [GetSpec] instead. This wrapper is retained for
// backwards compatibility.
func GetSwagger() (*openapi3.T, error) {
	return GetSpec()
}
