// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"bytes"
	"context"
	"encoding/json"
	"fmt"
	"io"
	"mime/multipart"
	"net/http"
	"strings"
	"time"

	"github.com/labstack/echo/v5"
	"github.com/oapi-codegen/nullable"
	"github.com/oapi-codegen/runtime"
	openapi_types "github.com/oapi-codegen/runtime/types"
)

// Defines values for ErrorCode.
const (
	ErrorCodeBadGateway     ErrorCode = "bad_gateway"
	ErrorCodeBadRequest     ErrorCode = "bad_request"
	ErrorCodeInternal       ErrorCode = "internal"
	ErrorCodeNotFound       ErrorCode = "not_found"
	ErrorCodeNotImplemented ErrorCode = "not_implemented"
	ErrorCodeUnauthorized   ErrorCode = "unauthorized"
	ErrorCodeUnprocessable  ErrorCode = "unprocessable"
)

// Valid indicates whether the value is a known member of the ErrorCode enum.
func (e ErrorCode) Valid() bool {
	switch e {
	case ErrorCodeBadGateway:
		return true
	case ErrorCodeBadRequest:
		return true
	case ErrorCodeInternal:
		return true
	case ErrorCodeNotFound:
		return true
	case ErrorCodeNotImplemented:
		return true
	case ErrorCodeUnauthorized:
		return true
	case ErrorCodeUnprocessable:
		return true
	default:
		return false
	}
}

// Defines values for EstimateStatus.
const (
	EstimateStatusFailed   EstimateStatus = "failed"
	EstimateStatusNoResult EstimateStatus = "no_result"
	EstimateStatusOk       EstimateStatus = "ok"
)

// Valid indicates whether the value is a known member of the EstimateStatus enum.
func (e EstimateStatus) Valid() bool {
	switch e {
	case EstimateStatusFailed:
		return true
	case EstimateStatusNoResult:
		return true
	case EstimateStatusOk:
		return true
	default:
		return false
	}
}

// Defines values for FetchType.
const (
	Api      FetchType = "api"
	Headless FetchType = "headless"
	LinkOnly FetchType = "link_only"
	Scrape   FetchType = "scrape"
)

// Valid indicates whether the value is a known member of the FetchType enum.
func (e FetchType) Valid() bool {
	switch e {
	case Api:
		return true
	case Headless:
		return true
	case LinkOnly:
		return true
	case Scrape:
		return true
	default:
		return false
	}
}

// Defines values for HealthStatus.
const (
	HealthStatusOk HealthStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthStatus enum.
func (e HealthStatus) Valid() bool {
	switch e {
	case HealthStatusOk:
		return true
	default:
		return false
	}
}

// Defines values for SuspiciousReason.
const (
	BelowMin      SuspiciousReason = "below_min"
	TitleMismatch SuspiciousReason = "title_mismatch"
	TooCheap      SuspiciousReason = "too_cheap"
)

// Valid indicates whether the value is a known member of the SuspiciousReason enum.
func (e SuspiciousReason) Valid() bool {
	switch e {
	case BelowMin:
		return true
	case TitleMismatch:
		return true
	case TooCheap:
		return true
	default:
		return false
	}
}

// AliasGroups 表記揺れの辞書(フェーズ4-1。docs/phase4-spec.md)。1 グループは同じものを指す語の集合(例 `["S.H.Figuarts", "SHフィギュアーツ", "フィギュアーツ"]`)。
// 参考外の判定(title_mismatch)で、商品名のトークンがグループの語と正規化して一致すれば、同じグループのどの語がタイトルに含まれても一致とみなす。
// 応答では常に返す(無ければ `[]`)。作成・更新で渡すと全件置き換え(更新で省略すれば変えない)。
// 各語は前後の空白を除いて 1〜64 文字、1 グループは 2 語以上、正規化後の語はジャンル内で重複しない(違反は 422)
type AliasGroups = [][]string

// DayLow その日の全サイトの low の最小
type DayLow struct {
	Day openapi_types.Date `json:"day"`
	Low int                `json:"low"`
}

// Error defines model for Error.
type Error struct {
	Code    ErrorCode `json:"code"`
	Message string    `json:"message"`
}

// ErrorCode defines model for Error.Code.
type ErrorCode string

// EstimateStatus defines model for EstimateStatus.
type EstimateStatus string

// FetchType defines model for FetchType.
type FetchType string

// FromURLRequest defines model for FromURLRequest.
type FromURLRequest struct {
	GenreId *ID `json:"genre_id,omitempty"`

	// Url http(s) の商品ページ URL
	Url string `json:"url"`
}

// Genre defines model for Genre.
type Genre struct {
	// Aliases 表記揺れの辞書(フェーズ4-1。docs/phase4-spec.md)。1 グループは同じものを指す語の集合(例 `["S.H.Figuarts", "SHフィギュアーツ", "フィギュアーツ"]`)。
	// 参考外の判定(title_mismatch)で、商品名のトークンがグループの語と正規化して一致すれば、同じグループのどの語がタイトルに含まれても一致とみなす。
	// 応答では常に返す(無ければ `[]`)。作成・更新で渡すと全件置き換え(更新で省略すれば変えない)。
	// 各語は前後の空白を除いて 1〜64 文字、1 グループは 2 語以上、正規化後の語はジャンル内で重複しない(違反は 422)
	Aliases *AliasGroups `json:"aliases,omitempty"`
	Id      ID           `json:"id"`
	Name    string       `json:"name"`

	// QueryTemplate `{name}` と `{option}` を埋め込む
	QueryTemplate string `json:"query_template"`

	// SiteIds 表示するサイト(表示順)
	SiteIds   []ID `json:"site_ids"`
	SortOrder int  `json:"sort_order"`
}

// GenreCreate defines model for GenreCreate.
type GenreCreate struct {
	// Aliases 表記揺れの辞書(フェーズ4-1。docs/phase4-spec.md)。1 グループは同じものを指す語の集合(例 `["S.H.Figuarts", "SHフィギュアーツ", "フィギュアーツ"]`)。
	// 参考外の判定(title_mismatch)で、商品名のトークンがグループの語と正規化して一致すれば、同じグループのどの語がタイトルに含まれても一致とみなす。
	// 応答では常に返す(無ければ `[]`)。作成・更新で渡すと全件置き換え(更新で省略すれば変えない)。
	// 各語は前後の空白を除いて 1〜64 文字、1 グループは 2 語以上、正規化後の語はジャンル内で重複しない(違反は 422)
	Aliases       *AliasGroups `json:"aliases,omitempty"`
	Name          string       `json:"name"`
	QueryTemplate *string      `json:"query_template,omitempty"`
	SiteIds       *[]ID        `json:"site_ids,omitempty"`
	SortOrder     *int         `json:"sort_order,omitempty"`
}

// GenreUpdate defines model for GenreUpdate.
type GenreUpdate struct {
	// Aliases 表記揺れの辞書(フェーズ4-1。docs/phase4-spec.md)。1 グループは同じものを指す語の集合(例 `["S.H.Figuarts", "SHフィギュアーツ", "フィギュアーツ"]`)。
	// 参考外の判定(title_mismatch)で、商品名のトークンがグループの語と正規化して一致すれば、同じグループのどの語がタイトルに含まれても一致とみなす。
	// 応答では常に返す(無ければ `[]`)。作成・更新で渡すと全件置き換え(更新で省略すれば変えない)。
	// 各語は前後の空白を除いて 1〜64 文字、1 グループは 2 語以上、正規化後の語はジャンル内で重複しない(違反は 422)
	Aliases       *AliasGroups `json:"aliases,omitempty"`
	Name          *string      `json:"name,omitempty"`
	QueryTemplate *string      `json:"query_template,omitempty"`

	// SiteIds 渡すと表示するサイトと順序を全件置き換える
	SiteIds   *[]ID `json:"site_ids,omitempty"`
	SortOrder *int  `json:"sort_order,omitempty"`
}

// Health defines model for Health.
type Health struct {
	Status HealthStatus `json:"status"`
}

// HealthStatus defines model for Health.Status.
type HealthStatus string

// ID defines model for ID.
type ID = int64

// Item defines model for Item.
type Item struct {
	CreatedAt time.Time `json:"created_at"`
	GenreId   ID        `json:"genre_id"`
	Id        ID        `json:"id"`

	// ImageUrl 画像のパス `images/<name>`(先頭に / を付けない)。API のベース URL(例 `https://<host>/wishlist/`)を基準に解決する
	// (オリジン基準で解決すると前置 `/wishlist` が抜けるため。docs/design.md W-03)
	ImageUrl      string                    `json:"image_url"`
	MinPrice      nullable.Nullable[int]    `json:"min_price,omitempty"`
	Name          string                    `json:"name"`
	OptionText    nullable.Nullable[string] `json:"option_text,omitempty"`
	QueryOverride nullable.Nullable[string] `json:"query_override,omitempty"`
	SiteOverrides []SiteOverride            `json:"site_overrides"`
	SortOrder     int                       `json:"sort_order"`
	SourceUrl     nullable.Nullable[string] `json:"source_url,omitempty"`
	UpdatedAt     time.Time                 `json:"updated_at"`
}

// ItemCreateJSON defines model for ItemCreateJSON.
type ItemCreateJSON struct {
	GenreId ID `json:"genre_id"`

	// ImageUrl http(s) の画像 URL。サーバーが取得して保存する
	ImageUrl      string  `json:"image_url"`
	MinPrice      *int    `json:"min_price,omitempty"`
	Name          string  `json:"name"`
	OptionText    *string `json:"option_text,omitempty"`
	QueryOverride *string `json:"query_override,omitempty"`
	SortOrder     *int    `json:"sort_order,omitempty"`
	SourceUrl     *string `json:"source_url,omitempty"`
}

// ItemCreateMultipart defines model for ItemCreateMultipart.
type ItemCreateMultipart struct {
	GenreId       ID                 `json:"genre_id"`
	Image         openapi_types.File `json:"image"`
	MinPrice      *int               `json:"min_price,omitempty"`
	Name          string             `json:"name"`
	OptionText    *string            `json:"option_text,omitempty"`
	QueryOverride *string            `json:"query_override,omitempty"`
	SortOrder     *int               `json:"sort_order,omitempty"`
	SourceUrl     *string            `json:"source_url,omitempty"`
}

// ItemDraft defines model for ItemDraft.
type ItemDraft struct {
	// GenreId リクエストの genre_id をそのまま返す(未指定なら null)
	GenreId nullable.Nullable[int64] `json:"genre_id,omitempty"`

	// ImageUrl og:image の絶対 URL(無ければ null)
	ImageUrl nullable.Nullable[string] `json:"image_url,omitempty"`

	// Name og:title(無ければ <title>)
	Name      string `json:"name"`
	SourceUrl string `json:"source_url"`
}

// ItemEstimates defines model for ItemEstimates.
type ItemEstimates struct {
	ItemId     ID             `json:"item_id"`
	Refreshing bool           `json:"refreshing"`
	Sites      []SiteEstimate `json:"sites"`

	// SummaryFetchedAt low を持つサイトの fetched_at のうち最も古いもの
	SummaryFetchedAt nullable.Nullable[time.Time] `json:"summary_fetched_at,omitempty"`

	// SummaryLow `sites` の low の最小(low を持つサイトが無ければ null)
	SummaryLow nullable.Nullable[int] `json:"summary_low,omitempty"`

	// SummaryMid summary_low を出したサイトの mid(その mid が null なら summary_low)
	SummaryMid nullable.Nullable[int] `json:"summary_mid,omitempty"`
}

// ItemFields defines model for ItemFields.
type ItemFields struct {
	GenreId       ID      `json:"genre_id"`
	MinPrice      *int    `json:"min_price,omitempty"`
	Name          string  `json:"name"`
	OptionText    *string `json:"option_text,omitempty"`
	QueryOverride *string `json:"query_override,omitempty"`
	SortOrder     *int    `json:"sort_order,omitempty"`
	SourceUrl     *string `json:"source_url,omitempty"`
}

// ItemUpdate defines model for ItemUpdate.
type ItemUpdate struct {
	GenreId       *ID                       `json:"genre_id,omitempty"`
	MinPrice      nullable.Nullable[int]    `json:"min_price,omitempty"`
	Name          *string                   `json:"name,omitempty"`
	OptionText    nullable.Nullable[string] `json:"option_text,omitempty"`
	QueryOverride nullable.Nullable[string] `json:"query_override,omitempty"`
	SiteOverrides *[]SiteOverride           `json:"site_overrides,omitempty"`
	SortOrder     *int                      `json:"sort_order,omitempty"`
	SourceUrl     nullable.Nullable[string] `json:"source_url,omitempty"`
}

// Listing defines model for Listing.
type Listing struct {
	FetchedAt time.Time                 `json:"fetched_at"`
	Id        ID                        `json:"id"`
	ImageUrl  nullable.Nullable[string] `json:"image_url,omitempty"`
	InStock   bool                      `json:"in_stock"`
	Price     int                       `json:"price"`
	SiteId    ID                        `json:"site_id"`

	// SuspiciousReasons 空なら参考にしている出品
	SuspiciousReasons []SuspiciousReason `json:"suspicious_reasons"`
	Title             string             `json:"title"`
	Url               string             `json:"url"`
}

// PriceHistory defines model for PriceHistory.
type PriceHistory struct {
	// Days 返した期間(日数。省略時は 90)
	Days   int `json:"days"`
	ItemId ID  `json:"item_id"`

	// Overall day 昇順。点のある日だけ
	Overall []DayLow `json:"overall"`

	// Sites 点のあるサイトだけ。ジャンルの表示順、ジャンルに無いサイトはその後に site_id 昇順
	Sites []SitePriceHistory `json:"sites"`
}

// PricePoint 1 サイトの 1 日(JST)の目安。その日の最後に取得した値
type PricePoint struct {
	// Day JST の日付(YYYY-MM-DD)
	Day openapi_types.Date `json:"day"`
	Low int                `json:"low"`

	// Mid 件数 3 未満の日は null
	Mid nullable.Nullable[int] `json:"mid,omitempty"`
}

// Site defines model for Site.
type Site struct {
	FetchType   FetchType `json:"fetch_type"`
	Id          ID        `json:"id"`
	IsReference bool      `json:"is_reference"`
	Name        string    `json:"name"`

	// SearchUrlTemplate `{q}` を encodeURIComponent(検索ワード) で置き換える
	SearchUrlTemplate string `json:"search_url_template"`
}

// SiteCreate defines model for SiteCreate.
type SiteCreate struct {
	FetchType   *FetchType `json:"fetch_type,omitempty"`
	IsReference *bool      `json:"is_reference,omitempty"`
	Name        string     `json:"name"`

	// SearchUrlTemplate http(s) の URL で、`{q}` を含むこと
	SearchUrlTemplate string `json:"search_url_template"`
}

// SiteEstimate サイトごとの目安。仕様 §3 の「状態(在庫あり等)」は `in_stock_count` で表す(docs/phase3-api-spec.md)。
// `status` が failed のとき、low・mid・count・suspicious_count・in_stock_count・fetched_at は前回の値。
type SiteEstimate struct {
	// Count 参考外を除いた件数
	Count     int       `json:"count"`
	FetchedAt time.Time `json:"fetched_at"`

	// InStockCount 参考外を除き、在庫ありの件数
	InStockCount int `json:"in_stock_count"`

	// Low 下位25パーセンタイル(件数3未満なら最小値)
	Low nullable.Nullable[int] `json:"low,omitempty"`

	// Mid 中央値(件数3未満なら null)
	Mid    nullable.Nullable[int] `json:"mid,omitempty"`
	SiteId ID                     `json:"site_id"`
	Status EstimateStatus         `json:"status"`

	// SuspiciousCount 参考外の件数
	SuspiciousCount int `json:"suspicious_count"`
}

// SiteOverride defines model for SiteOverride.
type SiteOverride struct {
	// Enabled false ならこの商品ではこのサイトを出さない
	Enabled bool `json:"enabled"`

	// Query このサイトだけで使う検索ワード(テンプレート・query_override より優先)
	Query  nullable.Nullable[string] `json:"query,omitempty"`
	SiteId ID                        `json:"site_id"`
}

// SitePriceHistory defines model for SitePriceHistory.
type SitePriceHistory struct {
	// Points day 昇順。点のある日だけ
	Points []PricePoint `json:"points"`
	SiteId ID           `json:"site_id"`
}

// SiteUpdate defines model for SiteUpdate.
type SiteUpdate struct {
	FetchType         *FetchType `json:"fetch_type,omitempty"`
	IsReference       *bool      `json:"is_reference,omitempty"`
	Name              *string    `json:"name,omitempty"`
	SearchUrlTemplate *string    `json:"search_url_template,omitempty"`
}

// SuspiciousReason defines model for SuspiciousReason.
type SuspiciousReason string

// GenreID defines model for GenreID.
type GenreID = ID

// ItemID defines model for ItemID.
type ItemID = ID

// SiteID defines model for SiteID.
type SiteID = ID

// BadGateway defines model for BadGateway.
type BadGateway = Error

// BadRequest defines model for BadRequest.
type BadRequest = Error

// Internal defines model for Internal.
type Internal = Error

// NotFound defines model for NotFound.
type NotFound = Error

// Unauthorized defines model for Unauthorized.
type Unauthorized = Error

// Unprocessable defines model for Unprocessable.
type Unprocessable = Error

// ListItemsParams defines parameters for ListItems.
type ListItemsParams struct {
	GenreId *ID `form:"genre_id,omitempty" json:"genre_id,omitempty"`
}

// ReplaceItemImageMultipartBody defines parameters for ReplaceItemImage.
type ReplaceItemImageMultipartBody struct {
	Image openapi_types.File `json:"image"`
}

// ListItemListingsParams defines parameters for ListItemListings.
type ListItemListingsParams struct {
	SiteId *ID `form:"site_id,omitempty" json:"site_id,omitempty"`
}

// GetItemPriceHistoryParams defines parameters for GetItemPriceHistory.
type GetItemPriceHistoryParams struct {
	// Days 直近何日分か(今日を含む)。省略は 90。1〜180 の外は 400
	Days *int `form:"days,omitempty" json:"days,omitempty"`
}

// CreateGenreJSONRequestBody defines body for CreateGenre for application/json ContentType.
type CreateGenreJSONRequestBody = GenreCreate

// UpdateGenreJSONRequestBody defines body for UpdateGenre for application/json ContentType.
type UpdateGenreJSONRequestBody = GenreUpdate

// CreateItemJSONRequestBody defines body for CreateItem for application/json ContentType.
type CreateItemJSONRequestBody = ItemCreateJSON

// CreateItemMultipartRequestBody defines body for CreateItem for multipart/form-data ContentType.
type CreateItemMultipartRequestBody = ItemCreateMultipart

// DraftItemFromURLJSONRequestBody defines body for DraftItemFromURL for application/json ContentType.
type DraftItemFromURLJSONRequestBody = FromURLRequest

// UpdateItemJSONRequestBody defines body for UpdateItem for application/json ContentType.
type UpdateItemJSONRequestBody = ItemUpdate

// ReplaceItemImageMultipartRequestBody defines body for ReplaceItemImage for multipart/form-data ContentType.
type ReplaceItemImageMultipartRequestBody ReplaceItemImageMultipartBody

// CreateSiteJSONRequestBody defines body for CreateSite for application/json ContentType.
type CreateSiteJSONRequestBody = SiteCreate

// UpdateSiteJSONRequestBody defines body for UpdateSite for application/json ContentType.
type UpdateSiteJSONRequestBody = SiteUpdate

// ServerInterface represents all server handlers.
type ServerInterface interface {

	// (GET /api/genres)
	ListGenres(ctx *echo.Context) error

	// (POST /api/genres)
	CreateGenre(ctx *echo.Context) error

	// (PATCH /api/genres/{id})
	UpdateGenre(ctx *echo.Context, id GenreID) error

	// (GET /api/items)
	ListItems(ctx *echo.Context, params ListItemsParams) error

	// (POST /api/items)
	CreateItem(ctx *echo.Context) error

	// (POST /api/items/from-url)
	DraftItemFromURL(ctx *echo.Context) error

	// (DELETE /api/items/{id})
	DeleteItem(ctx *echo.Context, id ItemID) error

	// (GET /api/items/{id})
	GetItem(ctx *echo.Context, id ItemID) error

	// (PATCH /api/items/{id})
	UpdateItem(ctx *echo.Context, id ItemID) error

	// (GET /api/items/{id}/estimates)
	GetItemEstimates(ctx *echo.Context, id ItemID) error

	// (POST /api/items/{id}/estimates/refresh)
	RefreshItemEstimates(ctx *echo.Context, id ItemID) error

	// (PUT /api/items/{id}/image)
	ReplaceItemImage(ctx *echo.Context, id ItemID) error

	// (GET /api/items/{id}/listings)
	ListItemListings(ctx *echo.Context, id ItemID, params ListItemListingsParams) error

	// (GET /api/items/{id}/price-history)
	GetItemPriceHistory(ctx *echo.Context, id ItemID, params GetItemPriceHistoryParams) error

	// (GET /api/sites)
	ListSites(ctx *echo.Context) error

	// (POST /api/sites)
	CreateSite(ctx *echo.Context) error

	// (PATCH /api/sites/{id})
	UpdateSite(ctx *echo.Context, id SiteID) error

	// (GET /healthz)
	GetHealthz(ctx *echo.Context) error

	// (GET /images/{name})
	GetImage(ctx *echo.Context, name string) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// ListGenres converts echo context to params.
func (w *ServerInterfaceWrapper) ListGenres(ctx *echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListGenres(ctx)
	return err
}

// CreateGenre converts echo context to params.
func (w *ServerInterfaceWrapper) CreateGenre(ctx *echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateGenre(ctx)
	return err
}

// UpdateGenre converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateGenre(ctx *echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id GenreID

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateGenre(ctx, id)
	return err
}

// ListItems converts echo context to params.
func (w *ServerInterfaceWrapper) ListItems(ctx *echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListItemsParams
	// ------------- Optional query parameter "genre_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "genre_id", ctx.QueryParams(), &params.GenreId, runtime.BindQueryParameterOptions{Type: "integer", Format: "int64"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter genre_id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListItems(ctx, params)
	return err
}

// CreateItem converts echo context to params.
func (w *ServerInterfaceWrapper) CreateItem(ctx *echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateItem(ctx)
	return err
}

// DraftItemFromURL converts echo context to params.
func (w *ServerInterfaceWrapper) DraftItemFromURL(ctx *echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DraftItemFromURL(ctx)
	return err
}

// DeleteItem converts echo context to params.
func (w *ServerInterfaceWrapper) DeleteItem(ctx *echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id ItemID

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.DeleteItem(ctx, id)
	return err
}

// GetItem converts echo context to params.
func (w *ServerInterfaceWrapper) GetItem(ctx *echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id ItemID

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetItem(ctx, id)
	return err
}

// UpdateItem converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateItem(ctx *echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id ItemID

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateItem(ctx, id)
	return err
}

// GetItemEstimates converts echo context to params.
func (w *ServerInterfaceWrapper) GetItemEstimates(ctx *echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id ItemID

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetItemEstimates(ctx, id)
	return err
}

// RefreshItemEstimates converts echo context to params.
func (w *ServerInterfaceWrapper) RefreshItemEstimates(ctx *echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id ItemID

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.RefreshItemEstimates(ctx, id)
	return err
}

// ReplaceItemImage converts echo context to params.
func (w *ServerInterfaceWrapper) ReplaceItemImage(ctx *echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id ItemID

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ReplaceItemImage(ctx, id)
	return err
}

// ListItemListings converts echo context to params.
func (w *ServerInterfaceWrapper) ListItemListings(ctx *echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id ItemID

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params ListItemListingsParams
	// ------------- Optional query parameter "site_id" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "site_id", ctx.QueryParams(), &params.SiteId, runtime.BindQueryParameterOptions{Type: "integer", Format: "int64"})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter site_id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListItemListings(ctx, id, params)
	return err
}

// GetItemPriceHistory converts echo context to params.
func (w *ServerInterfaceWrapper) GetItemPriceHistory(ctx *echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id ItemID

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Parameter object where we will unmarshal all parameters from the context
	var params GetItemPriceHistoryParams
	// ------------- Optional query parameter "days" -------------

	err = runtime.BindQueryParameterWithOptions("form", true, false, "days", ctx.QueryParams(), &params.Days, runtime.BindQueryParameterOptions{Type: "integer", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter days: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetItemPriceHistory(ctx, id, params)
	return err
}

// ListSites converts echo context to params.
func (w *ServerInterfaceWrapper) ListSites(ctx *echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListSites(ctx)
	return err
}

// CreateSite converts echo context to params.
func (w *ServerInterfaceWrapper) CreateSite(ctx *echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.CreateSite(ctx)
	return err
}

// UpdateSite converts echo context to params.
func (w *ServerInterfaceWrapper) UpdateSite(ctx *echo.Context) error {
	var err error
	// ------------- Path parameter "id" -------------
	var id SiteID

	err = runtime.BindStyledParameterWithOptions("simple", "id", ctx.Param("id"), &id, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "integer", Format: "int64", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter id: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.UpdateSite(ctx, id)
	return err
}

// GetHealthz converts echo context to params.
func (w *ServerInterfaceWrapper) GetHealthz(ctx *echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetHealthz(ctx)
	return err
}

// GetImage converts echo context to params.
func (w *ServerInterfaceWrapper) GetImage(ctx *echo.Context) error {
	var err error
	// ------------- Path parameter "name" -------------
	var name string

	err = runtime.BindStyledParameterWithOptions("simple", "name", ctx.Param("name"), &name, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationPath, Explode: false, Required: true, Type: "string", Format: "", ValueIsUnescaped: ctx.Request().URL.RawPath == ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter name: %s", err))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetImage(ctx, name)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
}

// RegisterHandlersOptions configures RegisterHandlersWithOptions.
type RegisterHandlersOptions struct {
	// BaseURL is prepended to every registered path so the API can be served
	// under a prefix.
	BaseURL string
	// OperationMiddlewares lets the caller attach per-operation middleware at
	// registration time. The map key is the OpenAPI `operationId` value as it
	// appears in the spec (the raw, un-normalized form). Operations that have
	// no entry are registered with no extra middleware. A nil map disables
	// per-operation middleware entirely.
	OperationMiddlewares map[string][]echo.MiddlewareFunc
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{})
}

// RegisterHandlersWithBaseURL registers handlers and prepends BaseURL to the
// paths so the API can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{BaseURL: baseURL})
}

// RegisterHandlersWithOptions registers handlers using the supplied options,
// including any per-operation middleware.
func RegisterHandlersWithOptions(router EchoRouter, si ServerInterface, options RegisterHandlersOptions) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(options.BaseURL+"/healthz", wrapper.GetHealthz, options.OperationMiddlewares["getHealthz"]...)
	router.GET(options.BaseURL+"/api/items", wrapper.ListItems, options.OperationMiddlewares["listItems"]...)
	router.POST(options.BaseURL+"/api/items", wrapper.CreateItem, options.OperationMiddlewares["createItem"]...)
	router.POST(options.BaseURL+"/api/items/from-url", wrapper.DraftItemFromURL, options.OperationMiddlewares["draftItemFromURL"]...)
	router.DELETE(options.BaseURL+"/api/items/:id", wrapper.DeleteItem, options.OperationMiddlewares["deleteItem"]...)
	router.GET(options.BaseURL+"/api/items/:id", wrapper.GetItem, options.OperationMiddlewares["getItem"]...)
	router.PATCH(options.BaseURL+"/api/items/:id", wrapper.UpdateItem, options.OperationMiddlewares["updateItem"]...)
	router.PUT(options.BaseURL+"/api/items/:id/image", wrapper.ReplaceItemImage, options.OperationMiddlewares["replaceItemImage"]...)
	router.GET(options.BaseURL+"/api/items/:id/estimates", wrapper.GetItemEstimates, options.OperationMiddlewares["getItemEstimates"]...)
	router.POST(options.BaseURL+"/api/items/:id/estimates/refresh", wrapper.RefreshItemEstimates, options.OperationMiddlewares["refreshItemEstimates"]...)
	router.GET(options.BaseURL+"/api/items/:id/listings", wrapper.ListItemListings, options.OperationMiddlewares["listItemListings"]...)
	router.GET(options.BaseURL+"/api/items/:id/price-history", wrapper.GetItemPriceHistory, options.OperationMiddlewares["getItemPriceHistory"]...)
	router.GET(options.BaseURL+"/api/genres", wrapper.ListGenres, options.OperationMiddlewares["listGenres"]...)
	router.POST(options.BaseURL+"/api/genres", wrapper.CreateGenre, options.OperationMiddlewares["createGenre"]...)
	router.PATCH(options.BaseURL+"/api/genres/:id", wrapper.UpdateGenre, options.OperationMiddlewares["updateGenre"]...)
	router.GET(options.BaseURL+"/api/sites", wrapper.ListSites, options.OperationMiddlewares["listSites"]...)
	router.POST(options.BaseURL+"/api/sites", wrapper.CreateSite, options.OperationMiddlewares["createSite"]...)
	router.PATCH(options.BaseURL+"/api/sites/:id", wrapper.UpdateSite, options.OperationMiddlewares["updateSite"]...)
	router.GET(options.BaseURL+"/images/:name", wrapper.GetImage, options.OperationMiddlewares["getImage"]...)

}

type BadGatewayJSONResponse Error

type BadRequestJSONResponse Error

type InternalJSONResponse Error

type NotFoundJSONResponse Error

type UnauthorizedJSONResponse Error

type UnprocessableJSONResponse Error

type ListGenresRequestObject struct {
}

type ListGenresResponseObject interface {
	VisitListGenresResponse(w http.ResponseWriter) error
}

type ListGenres200JSONResponse struct {
	Genres []Genre `json:"genres"`
}

func (response ListGenres200JSONResponse) VisitListGenresResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListGenres401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListGenres401JSONResponse) VisitListGenresResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListGenres500JSONResponse struct{ InternalJSONResponse }

func (response ListGenres500JSONResponse) VisitListGenresResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type CreateGenreRequestObject struct {
	Body *CreateGenreJSONRequestBody
}

type CreateGenreResponseObject interface {
	VisitCreateGenreResponse(w http.ResponseWriter) error
}

type CreateGenre201JSONResponse Genre

func (response CreateGenre201JSONResponse) VisitCreateGenreResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateGenre400JSONResponse struct{ BadRequestJSONResponse }

func (response CreateGenre400JSONResponse) VisitCreateGenreResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateGenre401JSONResponse struct{ UnauthorizedJSONResponse }

func (response CreateGenre401JSONResponse) VisitCreateGenreResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CreateGenre422JSONResponse struct{ UnprocessableJSONResponse }

func (response CreateGenre422JSONResponse) VisitCreateGenreResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type CreateGenre500JSONResponse struct{ InternalJSONResponse }

func (response CreateGenre500JSONResponse) VisitCreateGenreResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateGenreRequestObject struct {
	Id   GenreID `json:"id"`
	Body *UpdateGenreJSONRequestBody
}

type UpdateGenreResponseObject interface {
	VisitUpdateGenreResponse(w http.ResponseWriter) error
}

type UpdateGenre200JSONResponse Genre

func (response UpdateGenre200JSONResponse) VisitUpdateGenreResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateGenre400JSONResponse struct{ BadRequestJSONResponse }

func (response UpdateGenre400JSONResponse) VisitUpdateGenreResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateGenre401JSONResponse struct{ UnauthorizedJSONResponse }

func (response UpdateGenre401JSONResponse) VisitUpdateGenreResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateGenre404JSONResponse struct{ NotFoundJSONResponse }

func (response UpdateGenre404JSONResponse) VisitUpdateGenreResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateGenre422JSONResponse struct{ UnprocessableJSONResponse }

func (response UpdateGenre422JSONResponse) VisitUpdateGenreResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateGenre500JSONResponse struct{ InternalJSONResponse }

func (response UpdateGenre500JSONResponse) VisitUpdateGenreResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type ListItemsRequestObject struct {
	Params ListItemsParams
}

type ListItemsResponseObject interface {
	VisitListItemsResponse(w http.ResponseWriter) error
}

type ListItems200JSONResponse struct {
	Items []Item `json:"items"`
}

func (response ListItems200JSONResponse) VisitListItemsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListItems400JSONResponse struct{ BadRequestJSONResponse }

func (response ListItems400JSONResponse) VisitListItemsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ListItems401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListItems401JSONResponse) VisitListItemsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListItems500JSONResponse struct{ InternalJSONResponse }

func (response ListItems500JSONResponse) VisitListItemsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type CreateItemRequestObject struct {
	JSONBody      *CreateItemJSONRequestBody
	MultipartBody *multipart.Reader
}

type CreateItemResponseObject interface {
	VisitCreateItemResponse(w http.ResponseWriter) error
}

type CreateItem201JSONResponse Item

func (response CreateItem201JSONResponse) VisitCreateItemResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateItem400JSONResponse struct{ BadRequestJSONResponse }

func (response CreateItem400JSONResponse) VisitCreateItemResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateItem401JSONResponse struct{ UnauthorizedJSONResponse }

func (response CreateItem401JSONResponse) VisitCreateItemResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CreateItem422JSONResponse struct{ UnprocessableJSONResponse }

func (response CreateItem422JSONResponse) VisitCreateItemResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type CreateItem500JSONResponse struct{ InternalJSONResponse }

func (response CreateItem500JSONResponse) VisitCreateItemResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type CreateItem502JSONResponse struct{ BadGatewayJSONResponse }

func (response CreateItem502JSONResponse) VisitCreateItemResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(502)
	_, err := buf.WriteTo(w)
	return err
}

type DraftItemFromURLRequestObject struct {
	Body *DraftItemFromURLJSONRequestBody
}

type DraftItemFromURLResponseObject interface {
	VisitDraftItemFromURLResponse(w http.ResponseWriter) error
}

type DraftItemFromURL200JSONResponse ItemDraft

func (response DraftItemFromURL200JSONResponse) VisitDraftItemFromURLResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type DraftItemFromURL400JSONResponse struct{ BadRequestJSONResponse }

func (response DraftItemFromURL400JSONResponse) VisitDraftItemFromURLResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type DraftItemFromURL401JSONResponse struct{ UnauthorizedJSONResponse }

func (response DraftItemFromURL401JSONResponse) VisitDraftItemFromURLResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type DraftItemFromURL422JSONResponse struct{ UnprocessableJSONResponse }

func (response DraftItemFromURL422JSONResponse) VisitDraftItemFromURLResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type DraftItemFromURL500JSONResponse struct{ InternalJSONResponse }

func (response DraftItemFromURL500JSONResponse) VisitDraftItemFromURLResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type DraftItemFromURL502JSONResponse struct{ BadGatewayJSONResponse }

func (response DraftItemFromURL502JSONResponse) VisitDraftItemFromURLResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(502)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteItemRequestObject struct {
	Id ItemID `json:"id"`
}

type DeleteItemResponseObject interface {
	VisitDeleteItemResponse(w http.ResponseWriter) error
}

type DeleteItem204Response struct {
}

func (response DeleteItem204Response) VisitDeleteItemResponse(w http.ResponseWriter) error {
	w.WriteHeader(204)
	return nil
}

type DeleteItem401JSONResponse struct{ UnauthorizedJSONResponse }

func (response DeleteItem401JSONResponse) VisitDeleteItemResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteItem404JSONResponse struct{ NotFoundJSONResponse }

func (response DeleteItem404JSONResponse) VisitDeleteItemResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type DeleteItem500JSONResponse struct{ InternalJSONResponse }

func (response DeleteItem500JSONResponse) VisitDeleteItemResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetItemRequestObject struct {
	Id ItemID `json:"id"`
}

type GetItemResponseObject interface {
	VisitGetItemResponse(w http.ResponseWriter) error
}

type GetItem200JSONResponse Item

func (response GetItem200JSONResponse) VisitGetItemResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetItem401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetItem401JSONResponse) VisitGetItemResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetItem404JSONResponse struct{ NotFoundJSONResponse }

func (response GetItem404JSONResponse) VisitGetItemResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetItem500JSONResponse struct{ InternalJSONResponse }

func (response GetItem500JSONResponse) VisitGetItemResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateItemRequestObject struct {
	Id   ItemID `json:"id"`
	Body *UpdateItemJSONRequestBody
}

type UpdateItemResponseObject interface {
	VisitUpdateItemResponse(w http.ResponseWriter) error
}

type UpdateItem200JSONResponse Item

func (response UpdateItem200JSONResponse) VisitUpdateItemResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateItem400JSONResponse struct{ BadRequestJSONResponse }

func (response UpdateItem400JSONResponse) VisitUpdateItemResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateItem401JSONResponse struct{ UnauthorizedJSONResponse }

func (response UpdateItem401JSONResponse) VisitUpdateItemResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateItem404JSONResponse struct{ NotFoundJSONResponse }

func (response UpdateItem404JSONResponse) VisitUpdateItemResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateItem422JSONResponse struct{ UnprocessableJSONResponse }

func (response UpdateItem422JSONResponse) VisitUpdateItemResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateItem500JSONResponse struct{ InternalJSONResponse }

func (response UpdateItem500JSONResponse) VisitUpdateItemResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetItemEstimatesRequestObject struct {
	Id ItemID `json:"id"`
}

type GetItemEstimatesResponseObject interface {
	VisitGetItemEstimatesResponse(w http.ResponseWriter) error
}

type GetItemEstimates200JSONResponse ItemEstimates

func (response GetItemEstimates200JSONResponse) VisitGetItemEstimatesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetItemEstimates401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetItemEstimates401JSONResponse) VisitGetItemEstimatesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetItemEstimates404JSONResponse struct{ NotFoundJSONResponse }

func (response GetItemEstimates404JSONResponse) VisitGetItemEstimatesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetItemEstimates500JSONResponse struct{ InternalJSONResponse }

func (response GetItemEstimates500JSONResponse) VisitGetItemEstimatesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type RefreshItemEstimatesRequestObject struct {
	Id ItemID `json:"id"`
}

type RefreshItemEstimatesResponseObject interface {
	VisitRefreshItemEstimatesResponse(w http.ResponseWriter) error
}

type RefreshItemEstimates202JSONResponse ItemEstimates

func (response RefreshItemEstimates202JSONResponse) VisitRefreshItemEstimatesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(202)
	_, err := buf.WriteTo(w)
	return err
}

type RefreshItemEstimates401JSONResponse struct{ UnauthorizedJSONResponse }

func (response RefreshItemEstimates401JSONResponse) VisitRefreshItemEstimatesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type RefreshItemEstimates404JSONResponse struct{ NotFoundJSONResponse }

func (response RefreshItemEstimates404JSONResponse) VisitRefreshItemEstimatesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type RefreshItemEstimates500JSONResponse struct{ InternalJSONResponse }

func (response RefreshItemEstimates500JSONResponse) VisitRefreshItemEstimatesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type ReplaceItemImageRequestObject struct {
	Id   ItemID `json:"id"`
	Body *multipart.Reader
}

type ReplaceItemImageResponseObject interface {
	VisitReplaceItemImageResponse(w http.ResponseWriter) error
}

type ReplaceItemImage200JSONResponse Item

func (response ReplaceItemImage200JSONResponse) VisitReplaceItemImageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ReplaceItemImage400JSONResponse struct{ BadRequestJSONResponse }

func (response ReplaceItemImage400JSONResponse) VisitReplaceItemImageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ReplaceItemImage401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ReplaceItemImage401JSONResponse) VisitReplaceItemImageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ReplaceItemImage404JSONResponse struct{ NotFoundJSONResponse }

func (response ReplaceItemImage404JSONResponse) VisitReplaceItemImageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type ReplaceItemImage422JSONResponse struct{ UnprocessableJSONResponse }

func (response ReplaceItemImage422JSONResponse) VisitReplaceItemImageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type ReplaceItemImage500JSONResponse struct{ InternalJSONResponse }

func (response ReplaceItemImage500JSONResponse) VisitReplaceItemImageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type ListItemListingsRequestObject struct {
	Id     ItemID `json:"id"`
	Params ListItemListingsParams
}

type ListItemListingsResponseObject interface {
	VisitListItemListingsResponse(w http.ResponseWriter) error
}

type ListItemListings200JSONResponse struct {
	Listings []Listing `json:"listings"`
}

func (response ListItemListings200JSONResponse) VisitListItemListingsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListItemListings400JSONResponse struct{ BadRequestJSONResponse }

func (response ListItemListings400JSONResponse) VisitListItemListingsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type ListItemListings401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListItemListings401JSONResponse) VisitListItemListingsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListItemListings404JSONResponse struct{ NotFoundJSONResponse }

func (response ListItemListings404JSONResponse) VisitListItemListingsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type ListItemListings500JSONResponse struct{ InternalJSONResponse }

func (response ListItemListings500JSONResponse) VisitListItemListingsResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetItemPriceHistoryRequestObject struct {
	Id     ItemID `json:"id"`
	Params GetItemPriceHistoryParams
}

type GetItemPriceHistoryResponseObject interface {
	VisitGetItemPriceHistoryResponse(w http.ResponseWriter) error
}

type GetItemPriceHistory200JSONResponse PriceHistory

func (response GetItemPriceHistory200JSONResponse) VisitGetItemPriceHistoryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetItemPriceHistory400JSONResponse struct{ BadRequestJSONResponse }

func (response GetItemPriceHistory400JSONResponse) VisitGetItemPriceHistoryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type GetItemPriceHistory401JSONResponse struct{ UnauthorizedJSONResponse }

func (response GetItemPriceHistory401JSONResponse) VisitGetItemPriceHistoryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type GetItemPriceHistory404JSONResponse struct{ NotFoundJSONResponse }

func (response GetItemPriceHistory404JSONResponse) VisitGetItemPriceHistoryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type GetItemPriceHistory500JSONResponse struct{ InternalJSONResponse }

func (response GetItemPriceHistory500JSONResponse) VisitGetItemPriceHistoryResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type ListSitesRequestObject struct {
}

type ListSitesResponseObject interface {
	VisitListSitesResponse(w http.ResponseWriter) error
}

type ListSites200JSONResponse struct {
	Sites []Site `json:"sites"`
}

func (response ListSites200JSONResponse) VisitListSitesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type ListSites401JSONResponse struct{ UnauthorizedJSONResponse }

func (response ListSites401JSONResponse) VisitListSitesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type ListSites500JSONResponse struct{ InternalJSONResponse }

func (response ListSites500JSONResponse) VisitListSitesResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type CreateSiteRequestObject struct {
	Body *CreateSiteJSONRequestBody
}

type CreateSiteResponseObject interface {
	VisitCreateSiteResponse(w http.ResponseWriter) error
}

type CreateSite201JSONResponse Site

func (response CreateSite201JSONResponse) VisitCreateSiteResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(201)
	_, err := buf.WriteTo(w)
	return err
}

type CreateSite400JSONResponse struct{ BadRequestJSONResponse }

func (response CreateSite400JSONResponse) VisitCreateSiteResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type CreateSite401JSONResponse struct{ UnauthorizedJSONResponse }

func (response CreateSite401JSONResponse) VisitCreateSiteResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type CreateSite422JSONResponse struct{ UnprocessableJSONResponse }

func (response CreateSite422JSONResponse) VisitCreateSiteResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type CreateSite500JSONResponse struct{ InternalJSONResponse }

func (response CreateSite500JSONResponse) VisitCreateSiteResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateSiteRequestObject struct {
	Id   SiteID `json:"id"`
	Body *UpdateSiteJSONRequestBody
}

type UpdateSiteResponseObject interface {
	VisitUpdateSiteResponse(w http.ResponseWriter) error
}

type UpdateSite200JSONResponse Site

func (response UpdateSite200JSONResponse) VisitUpdateSiteResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateSite400JSONResponse struct{ BadRequestJSONResponse }

func (response UpdateSite400JSONResponse) VisitUpdateSiteResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(400)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateSite401JSONResponse struct{ UnauthorizedJSONResponse }

func (response UpdateSite401JSONResponse) VisitUpdateSiteResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(401)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateSite404JSONResponse struct{ NotFoundJSONResponse }

func (response UpdateSite404JSONResponse) VisitUpdateSiteResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateSite422JSONResponse struct{ UnprocessableJSONResponse }

func (response UpdateSite422JSONResponse) VisitUpdateSiteResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(422)
	_, err := buf.WriteTo(w)
	return err
}

type UpdateSite500JSONResponse struct{ InternalJSONResponse }

func (response UpdateSite500JSONResponse) VisitUpdateSiteResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(500)
	_, err := buf.WriteTo(w)
	return err
}

type GetHealthzRequestObject struct {
}

type GetHealthzResponseObject interface {
	VisitGetHealthzResponse(w http.ResponseWriter) error
}

type GetHealthz200JSONResponse Health

func (response GetHealthz200JSONResponse) VisitGetHealthzResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(200)
	_, err := buf.WriteTo(w)
	return err
}

type GetImageRequestObject struct {
	Name string `json:"name"`
}

type GetImageResponseObject interface {
	VisitGetImageResponse(w http.ResponseWriter) error
}

type GetImage200ResponseHeaders struct {
	CacheControl *string
}

type GetImage200ImageResponse struct {
	Body          io.Reader
	Headers       GetImage200ResponseHeaders
	ContentType   string
	ContentLength int64
}

func (response GetImage200ImageResponse) VisitGetImageResponse(w http.ResponseWriter) error {

	w.Header().Set("Content-Type", response.ContentType)
	if response.ContentLength != 0 {
		w.Header().Set("Content-Length", fmt.Sprint(response.ContentLength))
	}
	if response.Headers.CacheControl != nil {
		w.Header().Set("Cache-Control", fmt.Sprint(*response.Headers.CacheControl))
	}
	w.WriteHeader(200)

	if closer, ok := response.Body.(io.ReadCloser); ok {
		defer closer.Close()
	}
	_, err := io.Copy(w, response.Body)
	return err
}

type GetImage404JSONResponse struct{ NotFoundJSONResponse }

func (response GetImage404JSONResponse) VisitGetImageResponse(w http.ResponseWriter) error {

	var buf bytes.Buffer
	if err := json.NewEncoder(&buf).Encode(response); err != nil {
		return err
	}
	w.Header().Set("Content-Type", "application/json")
	w.WriteHeader(404)
	_, err := buf.WriteTo(w)
	return err
}

// StrictServerInterface represents all server handlers.
type StrictServerInterface interface {

	// (GET /api/genres)
	ListGenres(ctx context.Context, request ListGenresRequestObject) (ListGenresResponseObject, error)

	// (POST /api/genres)
	CreateGenre(ctx context.Context, request CreateGenreRequestObject) (CreateGenreResponseObject, error)

	// (PATCH /api/genres/{id})
	UpdateGenre(ctx context.Context, request UpdateGenreRequestObject) (UpdateGenreResponseObject, error)

	// (GET /api/items)
	ListItems(ctx context.Context, request ListItemsRequestObject) (ListItemsResponseObject, error)

	// (POST /api/items)
	CreateItem(ctx context.Context, request CreateItemRequestObject) (CreateItemResponseObject, error)

	// (POST /api/items/from-url)
	DraftItemFromURL(ctx context.Context, request DraftItemFromURLRequestObject) (DraftItemFromURLResponseObject, error)

	// (DELETE /api/items/{id})
	DeleteItem(ctx context.Context, request DeleteItemRequestObject) (DeleteItemResponseObject, error)

	// (GET /api/items/{id})
	GetItem(ctx context.Context, request GetItemRequestObject) (GetItemResponseObject, error)

	// (PATCH /api/items/{id})
	UpdateItem(ctx context.Context, request UpdateItemRequestObject) (UpdateItemResponseObject, error)

	// (GET /api/items/{id}/estimates)
	GetItemEstimates(ctx context.Context, request GetItemEstimatesRequestObject) (GetItemEstimatesResponseObject, error)

	// (POST /api/items/{id}/estimates/refresh)
	RefreshItemEstimates(ctx context.Context, request RefreshItemEstimatesRequestObject) (RefreshItemEstimatesResponseObject, error)

	// (PUT /api/items/{id}/image)
	ReplaceItemImage(ctx context.Context, request ReplaceItemImageRequestObject) (ReplaceItemImageResponseObject, error)

	// (GET /api/items/{id}/listings)
	ListItemListings(ctx context.Context, request ListItemListingsRequestObject) (ListItemListingsResponseObject, error)

	// (GET /api/items/{id}/price-history)
	GetItemPriceHistory(ctx context.Context, request GetItemPriceHistoryRequestObject) (GetItemPriceHistoryResponseObject, error)

	// (GET /api/sites)
	ListSites(ctx context.Context, request ListSitesRequestObject) (ListSitesResponseObject, error)

	// (POST /api/sites)
	CreateSite(ctx context.Context, request CreateSiteRequestObject) (CreateSiteResponseObject, error)

	// (PATCH /api/sites/{id})
	UpdateSite(ctx context.Context, request UpdateSiteRequestObject) (UpdateSiteResponseObject, error)

	// (GET /healthz)
	GetHealthz(ctx context.Context, request GetHealthzRequestObject) (GetHealthzResponseObject, error)

	// (GET /images/{name})
	GetImage(ctx context.Context, request GetImageRequestObject) (GetImageResponseObject, error)
}

type StrictHandlerFunc func(ctx *echo.Context, request any) (any, error)
type StrictMiddlewareFunc func(f StrictHandlerFunc, operationID string) StrictHandlerFunc

func NewStrictHandler(ssi StrictServerInterface, middlewares []StrictMiddlewareFunc) ServerInterface {
	return &strictHandler{ssi: ssi, middlewares: middlewares}
}

type strictHandler struct {
	ssi         StrictServerInterface
	middlewares []StrictMiddlewareFunc
}

// ListGenres operation middleware
func (sh *strictHandler) ListGenres(ctx *echo.Context) error {
	var request ListGenresRequestObject

	handler := func(ctx *echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListGenres(ctx.Request().Context(), request.(ListGenresRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListGenres")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(ListGenresResponseObject); ok {
		return validResponse.VisitListGenresResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// CreateGenre operation middleware
func (sh *strictHandler) CreateGenre(ctx *echo.Context) error {
	var request CreateGenreRequestObject

	var body CreateGenreJSONRequestBody
	var err error
	if _, ok := ctx.Echo().Binder.(*echo.DefaultBinder); ok {
		// Bind only the request body, so that path and query parameters
		// are not also bound into the body struct.
		err = echo.BindBody(ctx, &body)
	} else {
		// A custom binder is installed on the Echo instance; defer to it
		// entirely, since echo.Binder does not expose body-only binding.
		err = ctx.Bind(&body)
	}
	if err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx *echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateGenre(ctx.Request().Context(), request.(CreateGenreRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateGenre")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(CreateGenreResponseObject); ok {
		return validResponse.VisitCreateGenreResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// UpdateGenre operation middleware
func (sh *strictHandler) UpdateGenre(ctx *echo.Context, id GenreID) error {
	var request UpdateGenreRequestObject

	request.Id = id

	var body UpdateGenreJSONRequestBody
	var err error
	if _, ok := ctx.Echo().Binder.(*echo.DefaultBinder); ok {
		// Bind only the request body, so that path and query parameters
		// are not also bound into the body struct.
		err = echo.BindBody(ctx, &body)
	} else {
		// A custom binder is installed on the Echo instance; defer to it
		// entirely, since echo.Binder does not expose body-only binding.
		err = ctx.Bind(&body)
	}
	if err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx *echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateGenre(ctx.Request().Context(), request.(UpdateGenreRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateGenre")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(UpdateGenreResponseObject); ok {
		return validResponse.VisitUpdateGenreResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// ListItems operation middleware
func (sh *strictHandler) ListItems(ctx *echo.Context, params ListItemsParams) error {
	var request ListItemsRequestObject

	request.Params = params

	handler := func(ctx *echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListItems(ctx.Request().Context(), request.(ListItemsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListItems")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(ListItemsResponseObject); ok {
		return validResponse.VisitListItemsResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// CreateItem operation middleware
func (sh *strictHandler) CreateItem(ctx *echo.Context) error {
	var request CreateItemRequestObject

	if strings.HasPrefix(ctx.Request().Header.Get("Content-Type"), "application/json") {
		var body CreateItemJSONRequestBody
		var err error
		if _, ok := ctx.Echo().Binder.(*echo.DefaultBinder); ok {
			// Bind only the request body, so that path and query parameters
			// are not also bound into the body struct.
			err = echo.BindBody(ctx, &body)
		} else {
			// A custom binder is installed on the Echo instance; defer to it
			// entirely, since echo.Binder does not expose body-only binding.
			err = ctx.Bind(&body)
		}
		if err != nil {
			return err
		}
		request.JSONBody = &body

	}
	if strings.HasPrefix(ctx.Request().Header.Get("Content-Type"), "multipart/form-data") {
		if reader, err := ctx.Request().MultipartReader(); err != nil {
			return err
		} else {
			request.MultipartBody = reader
		}
	}

	handler := func(ctx *echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateItem(ctx.Request().Context(), request.(CreateItemRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateItem")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(CreateItemResponseObject); ok {
		return validResponse.VisitCreateItemResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// DraftItemFromURL operation middleware
func (sh *strictHandler) DraftItemFromURL(ctx *echo.Context) error {
	var request DraftItemFromURLRequestObject

	var body DraftItemFromURLJSONRequestBody
	var err error
	if _, ok := ctx.Echo().Binder.(*echo.DefaultBinder); ok {
		// Bind only the request body, so that path and query parameters
		// are not also bound into the body struct.
		err = echo.BindBody(ctx, &body)
	} else {
		// A custom binder is installed on the Echo instance; defer to it
		// entirely, since echo.Binder does not expose body-only binding.
		err = ctx.Bind(&body)
	}
	if err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx *echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.DraftItemFromURL(ctx.Request().Context(), request.(DraftItemFromURLRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DraftItemFromURL")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(DraftItemFromURLResponseObject); ok {
		return validResponse.VisitDraftItemFromURLResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// DeleteItem operation middleware
func (sh *strictHandler) DeleteItem(ctx *echo.Context, id ItemID) error {
	var request DeleteItemRequestObject

	request.Id = id

	handler := func(ctx *echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.DeleteItem(ctx.Request().Context(), request.(DeleteItemRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "DeleteItem")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(DeleteItemResponseObject); ok {
		return validResponse.VisitDeleteItemResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetItem operation middleware
func (sh *strictHandler) GetItem(ctx *echo.Context, id ItemID) error {
	var request GetItemRequestObject

	request.Id = id

	handler := func(ctx *echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetItem(ctx.Request().Context(), request.(GetItemRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetItem")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetItemResponseObject); ok {
		return validResponse.VisitGetItemResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// UpdateItem operation middleware
func (sh *strictHandler) UpdateItem(ctx *echo.Context, id ItemID) error {
	var request UpdateItemRequestObject

	request.Id = id

	var body UpdateItemJSONRequestBody
	var err error
	if _, ok := ctx.Echo().Binder.(*echo.DefaultBinder); ok {
		// Bind only the request body, so that path and query parameters
		// are not also bound into the body struct.
		err = echo.BindBody(ctx, &body)
	} else {
		// A custom binder is installed on the Echo instance; defer to it
		// entirely, since echo.Binder does not expose body-only binding.
		err = ctx.Bind(&body)
	}
	if err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx *echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateItem(ctx.Request().Context(), request.(UpdateItemRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateItem")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(UpdateItemResponseObject); ok {
		return validResponse.VisitUpdateItemResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetItemEstimates operation middleware
func (sh *strictHandler) GetItemEstimates(ctx *echo.Context, id ItemID) error {
	var request GetItemEstimatesRequestObject

	request.Id = id

	handler := func(ctx *echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetItemEstimates(ctx.Request().Context(), request.(GetItemEstimatesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetItemEstimates")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetItemEstimatesResponseObject); ok {
		return validResponse.VisitGetItemEstimatesResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// RefreshItemEstimates operation middleware
func (sh *strictHandler) RefreshItemEstimates(ctx *echo.Context, id ItemID) error {
	var request RefreshItemEstimatesRequestObject

	request.Id = id

	handler := func(ctx *echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.RefreshItemEstimates(ctx.Request().Context(), request.(RefreshItemEstimatesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "RefreshItemEstimates")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(RefreshItemEstimatesResponseObject); ok {
		return validResponse.VisitRefreshItemEstimatesResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// ReplaceItemImage operation middleware
func (sh *strictHandler) ReplaceItemImage(ctx *echo.Context, id ItemID) error {
	var request ReplaceItemImageRequestObject

	request.Id = id

	if reader, err := ctx.Request().MultipartReader(); err != nil {
		return err
	} else {
		request.Body = reader
	}

	handler := func(ctx *echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ReplaceItemImage(ctx.Request().Context(), request.(ReplaceItemImageRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ReplaceItemImage")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(ReplaceItemImageResponseObject); ok {
		return validResponse.VisitReplaceItemImageResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// ListItemListings operation middleware
func (sh *strictHandler) ListItemListings(ctx *echo.Context, id ItemID, params ListItemListingsParams) error {
	var request ListItemListingsRequestObject

	request.Id = id
	request.Params = params

	handler := func(ctx *echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListItemListings(ctx.Request().Context(), request.(ListItemListingsRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListItemListings")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(ListItemListingsResponseObject); ok {
		return validResponse.VisitListItemListingsResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetItemPriceHistory operation middleware
func (sh *strictHandler) GetItemPriceHistory(ctx *echo.Context, id ItemID, params GetItemPriceHistoryParams) error {
	var request GetItemPriceHistoryRequestObject

	request.Id = id
	request.Params = params

	handler := func(ctx *echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetItemPriceHistory(ctx.Request().Context(), request.(GetItemPriceHistoryRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetItemPriceHistory")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetItemPriceHistoryResponseObject); ok {
		return validResponse.VisitGetItemPriceHistoryResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// ListSites operation middleware
func (sh *strictHandler) ListSites(ctx *echo.Context) error {
	var request ListSitesRequestObject

	handler := func(ctx *echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.ListSites(ctx.Request().Context(), request.(ListSitesRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "ListSites")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(ListSitesResponseObject); ok {
		return validResponse.VisitListSitesResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// CreateSite operation middleware
func (sh *strictHandler) CreateSite(ctx *echo.Context) error {
	var request CreateSiteRequestObject

	var body CreateSiteJSONRequestBody
	var err error
	if _, ok := ctx.Echo().Binder.(*echo.DefaultBinder); ok {
		// Bind only the request body, so that path and query parameters
		// are not also bound into the body struct.
		err = echo.BindBody(ctx, &body)
	} else {
		// A custom binder is installed on the Echo instance; defer to it
		// entirely, since echo.Binder does not expose body-only binding.
		err = ctx.Bind(&body)
	}
	if err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx *echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.CreateSite(ctx.Request().Context(), request.(CreateSiteRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "CreateSite")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(CreateSiteResponseObject); ok {
		return validResponse.VisitCreateSiteResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// UpdateSite operation middleware
func (sh *strictHandler) UpdateSite(ctx *echo.Context, id SiteID) error {
	var request UpdateSiteRequestObject

	request.Id = id

	var body UpdateSiteJSONRequestBody
	var err error
	if _, ok := ctx.Echo().Binder.(*echo.DefaultBinder); ok {
		// Bind only the request body, so that path and query parameters
		// are not also bound into the body struct.
		err = echo.BindBody(ctx, &body)
	} else {
		// A custom binder is installed on the Echo instance; defer to it
		// entirely, since echo.Binder does not expose body-only binding.
		err = ctx.Bind(&body)
	}
	if err != nil {
		return err
	}
	request.Body = &body

	handler := func(ctx *echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.UpdateSite(ctx.Request().Context(), request.(UpdateSiteRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "UpdateSite")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(UpdateSiteResponseObject); ok {
		return validResponse.VisitUpdateSiteResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetHealthz operation middleware
func (sh *strictHandler) GetHealthz(ctx *echo.Context) error {
	var request GetHealthzRequestObject

	handler := func(ctx *echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetHealthz(ctx.Request().Context(), request.(GetHealthzRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetHealthz")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetHealthzResponseObject); ok {
		return validResponse.VisitGetHealthzResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}

// GetImage operation middleware
func (sh *strictHandler) GetImage(ctx *echo.Context, name string) error {
	var request GetImageRequestObject

	request.Name = name

	handler := func(ctx *echo.Context, request interface{}) (interface{}, error) {
		return sh.ssi.GetImage(ctx.Request().Context(), request.(GetImageRequestObject))
	}
	for _, middleware := range sh.middlewares {
		handler = middleware(handler, "GetImage")
	}

	response, err := handler(ctx, request)

	if err != nil {
		return err
	} else if validResponse, ok := response.(GetImageResponseObject); ok {
		return validResponse.VisitGetImageResponse(ctx.Response())
	} else if response != nil {
		return fmt.Errorf("unexpected response type: %T", response)
	}
	return nil
}
