apiVersion: v1
kind: Service
metadata:
  name: balance
  labels:
    app.kubernetes.io/name: balance
    app.kubernetes.io/part-of: pokecalc
spec:
  selector:
    app.kubernetes.io/name: balance
  ports:
    - name: http
      port: 80
      targetPort: http
