// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1
// source: pokedex.sql

package store

import (
	"context"
	"database/sql"
	"encoding/json"
	"time"
)

const deleteAbilities = `-- name: DeleteAbilities :exec
DELETE FROM abilities
`

func (q *Queries) DeleteAbilities(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAbilities)
	return err
}

const deleteAbilityEffects = `-- name: DeleteAbilityEffects :exec
DELETE FROM ability_effects
`

func (q *Queries) DeleteAbilityEffects(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteAbilityEffects)
	return err
}

const deleteDataVersions = `-- name: DeleteDataVersions :exec
DELETE FROM data_versions
`

func (q *Queries) DeleteDataVersions(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteDataVersions)
	return err
}

const deleteItemEffects = `-- name: DeleteItemEffects :exec
DELETE FROM item_effects
`

func (q *Queries) DeleteItemEffects(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteItemEffects)
	return err
}

const deleteItems = `-- name: DeleteItems :exec
DELETE FROM items
`

func (q *Queries) DeleteItems(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteItems)
	return err
}

const deleteLearnsets = `-- name: DeleteLearnsets :exec
DELETE FROM learnsets
`

func (q *Queries) DeleteLearnsets(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteLearnsets)
	return err
}

const deleteMegaSpecies = `-- name: DeleteMegaSpecies :exec
DELETE FROM species WHERE is_mega = 1
`

func (q *Queries) DeleteMegaSpecies(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteMegaSpecies)
	return err
}

const deleteMoves = `-- name: DeleteMoves :exec
DELETE FROM moves
`

func (q *Queries) DeleteMoves(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteMoves)
	return err
}

const deleteNatures = `-- name: DeleteNatures :exec
DELETE FROM natures
`

func (q *Queries) DeleteNatures(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteNatures)
	return err
}

const deleteRegulationAbilities = `-- name: DeleteRegulationAbilities :exec
DELETE FROM regulation_abilities
`

func (q *Queries) DeleteRegulationAbilities(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteRegulationAbilities)
	return err
}

const deleteRegulationItems = `-- name: DeleteRegulationItems :exec
DELETE FROM regulation_items
`

func (q *Queries) DeleteRegulationItems(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteRegulationItems)
	return err
}

const deleteRegulationMoves = `-- name: DeleteRegulationMoves :exec
DELETE FROM regulation_moves
`

func (q *Queries) DeleteRegulationMoves(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteRegulationMoves)
	return err
}

const deleteRegulationSpecies = `-- name: DeleteRegulationSpecies :exec
DELETE FROM regulation_species
`

func (q *Queries) DeleteRegulationSpecies(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteRegulationSpecies)
	return err
}

const deleteRegulations = `-- name: DeleteRegulations :exec
DELETE FROM regulations
`

func (q *Queries) DeleteRegulations(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteRegulations)
	return err
}

const deleteRemainingSpecies = `-- name: DeleteRemainingSpecies :exec
DELETE FROM species
`

func (q *Queries) DeleteRemainingSpecies(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteRemainingSpecies)
	return err
}

const deleteSpeciesAbilities = `-- name: DeleteSpeciesAbilities :exec
DELETE FROM species_abilities
`

func (q *Queries) DeleteSpeciesAbilities(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteSpeciesAbilities)
	return err
}

const deleteTypeChart = `-- name: DeleteTypeChart :exec
DELETE FROM type_chart
`

func (q *Queries) DeleteTypeChart(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteTypeChart)
	return err
}

const deleteTypes = `-- name: DeleteTypes :exec
DELETE FROM types
`

func (q *Queries) DeleteTypes(ctx context.Context) error {
	_, err := q.db.ExecContext(ctx, deleteTypes)
	return err
}

const getAbility = `-- name: GetAbility :one
SELECT id, name_ja, name_ja_source, name_en
FROM abilities
WHERE id = ?
`

func (q *Queries) GetAbility(ctx context.Context, id string) (Ability, error) {
	row := q.db.QueryRowContext(ctx, getAbility, id)
	var i Ability
	err := row.Scan(
		&i.ID,
		&i.NameJa,
		&i.NameJaSource,
		&i.NameEn,
	)
	return i, err
}

const getAbilityEffect = `-- name: GetAbilityEffect :one
SELECT ability_id, effect
FROM ability_effects
WHERE ability_id = ?
`

func (q *Queries) GetAbilityEffect(ctx context.Context, abilityID string) (AbilityEffect, error) {
	row := q.db.QueryRowContext(ctx, getAbilityEffect, abilityID)
	var i AbilityEffect
	err := row.Scan(&i.AbilityID, &i.Effect)
	return i, err
}

const getDataVersion = `-- name: GetDataVersion :one
SELECT source, version, checksum, imported_at
FROM data_versions
WHERE source = ?
`

func (q *Queries) GetDataVersion(ctx context.Context, source string) (DataVersion, error) {
	row := q.db.QueryRowContext(ctx, getDataVersion, source)
	var i DataVersion
	err := row.Scan(
		&i.Source,
		&i.Version,
		&i.Checksum,
		&i.ImportedAt,
	)
	return i, err
}

const getDefaultRegulation = `-- name: GetDefaultRegulation :one
SELECT id, name_ja, is_default, starts_on, ends_on
FROM regulations
WHERE is_default = 1
`

type GetDefaultRegulationRow struct {
	ID        string
	NameJa    string
	IsDefault bool
	StartsOn  sql.NullTime
	EndsOn    sql.NullTime
}

func (q *Queries) GetDefaultRegulation(ctx context.Context) (GetDefaultRegulationRow, error) {
	row := q.db.QueryRowContext(ctx, getDefaultRegulation)
	var i GetDefaultRegulationRow
	err := row.Scan(
		&i.ID,
		&i.NameJa,
		&i.IsDefault,
		&i.StartsOn,
		&i.EndsOn,
	)
	return i, err
}

const getItem = `-- name: GetItem :one
SELECT id, name_ja, name_ja_source, name_en
FROM items
WHERE id = ?
`

func (q *Queries) GetItem(ctx context.Context, id string) (Item, error) {
	row := q.db.QueryRowContext(ctx, getItem, id)
	var i Item
	err := row.Scan(
		&i.ID,
		&i.NameJa,
		&i.NameJaSource,
		&i.NameEn,
	)
	return i, err
}

const getItemEffect = `-- name: GetItemEffect :one
SELECT item_id, effect
FROM item_effects
WHERE item_id = ?
`

func (q *Queries) GetItemEffect(ctx context.Context, itemID string) (ItemEffect, error) {
	row := q.db.QueryRowContext(ctx, getItemEffect, itemID)
	var i ItemEffect
	err := row.Scan(&i.ItemID, &i.Effect)
	return i, err
}

const getSpeciesByKey = `-- name: GetSpeciesByKey :one
SELECT ` + "`" + `key` + "`" + `, dex_no, form, showdown_id, name_ja, name_ja_source, name_en, type1, type2,
       base_hp, base_atk, base_def, base_spa, base_spd, base_spe,
       is_mega, base_species_key, required_item_id
FROM species
WHERE ` + "`" + `key` + "`" + ` = ?
`

func (q *Queries) GetSpeciesByKey(ctx context.Context, key string) (Species, error) {
	row := q.db.QueryRowContext(ctx, getSpeciesByKey, key)
	var i Species
	err := row.Scan(
		&i.Key,
		&i.DexNo,
		&i.Form,
		&i.ShowdownID,
		&i.NameJa,
		&i.NameJaSource,
		&i.NameEn,
		&i.Type1,
		&i.Type2,
		&i.BaseHp,
		&i.BaseAtk,
		&i.BaseDef,
		&i.BaseSpa,
		&i.BaseSpd,
		&i.BaseSpe,
		&i.IsMega,
		&i.BaseSpeciesKey,
		&i.RequiredItemID,
	)
	return i, err
}

const insertAbility = `-- name: InsertAbility :exec
INSERT INTO abilities (id, name_ja, name_ja_source, name_en)
VALUES (?, ?, ?, ?)
`

type InsertAbilityParams struct {
	ID           string
	NameJa       string
	NameJaSource string
	NameEn       string
}

func (q *Queries) InsertAbility(ctx context.Context, arg InsertAbilityParams) error {
	_, err := q.db.ExecContext(ctx, insertAbility,
		arg.ID,
		arg.NameJa,
		arg.NameJaSource,
		arg.NameEn,
	)
	return err
}

const insertAbilityEffect = `-- name: InsertAbilityEffect :exec
INSERT INTO ability_effects (ability_id, effect)
VALUES (?, ?)
`

type InsertAbilityEffectParams struct {
	AbilityID string
	Effect    json.RawMessage
}

func (q *Queries) InsertAbilityEffect(ctx context.Context, arg InsertAbilityEffectParams) error {
	_, err := q.db.ExecContext(ctx, insertAbilityEffect, arg.AbilityID, arg.Effect)
	return err
}

const insertDataVersion = `-- name: InsertDataVersion :exec
INSERT INTO data_versions (source, version, checksum, imported_at)
VALUES (?, ?, ?, ?)
`

type InsertDataVersionParams struct {
	Source     string
	Version    string
	Checksum   string
	ImportedAt time.Time
}

func (q *Queries) InsertDataVersion(ctx context.Context, arg InsertDataVersionParams) error {
	_, err := q.db.ExecContext(ctx, insertDataVersion,
		arg.Source,
		arg.Version,
		arg.Checksum,
		arg.ImportedAt,
	)
	return err
}

const insertItem = `-- name: InsertItem :exec
INSERT INTO items (id, name_ja, name_ja_source, name_en)
VALUES (?, ?, ?, ?)
`

type InsertItemParams struct {
	ID           string
	NameJa       string
	NameJaSource string
	NameEn       string
}

func (q *Queries) InsertItem(ctx context.Context, arg InsertItemParams) error {
	_, err := q.db.ExecContext(ctx, insertItem,
		arg.ID,
		arg.NameJa,
		arg.NameJaSource,
		arg.NameEn,
	)
	return err
}

const insertItemEffect = `-- name: InsertItemEffect :exec
INSERT INTO item_effects (item_id, effect)
VALUES (?, ?)
`

type InsertItemEffectParams struct {
	ItemID string
	Effect json.RawMessage
}

func (q *Queries) InsertItemEffect(ctx context.Context, arg InsertItemEffectParams) error {
	_, err := q.db.ExecContext(ctx, insertItemEffect, arg.ItemID, arg.Effect)
	return err
}

const insertLearnset = `-- name: InsertLearnset :exec
INSERT INTO learnsets (species_key, move_id)
VALUES (?, ?)
`

type InsertLearnsetParams struct {
	SpeciesKey string
	MoveID     string
}

func (q *Queries) InsertLearnset(ctx context.Context, arg InsertLearnsetParams) error {
	_, err := q.db.ExecContext(ctx, insertLearnset, arg.SpeciesKey, arg.MoveID)
	return err
}

const insertMove = `-- name: InsertMove :exec
INSERT INTO moves (id, name_ja, name_ja_source, name_en, type, category, power, accuracy, pp, priority)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertMoveParams struct {
	ID           string
	NameJa       string
	NameJaSource string
	NameEn       string
	Type         string
	Category     string
	Power        uint16
	Accuracy     sql.NullInt16
	Pp           uint8
	Priority     int8
}

func (q *Queries) InsertMove(ctx context.Context, arg InsertMoveParams) error {
	_, err := q.db.ExecContext(ctx, insertMove,
		arg.ID,
		arg.NameJa,
		arg.NameJaSource,
		arg.NameEn,
		arg.Type,
		arg.Category,
		arg.Power,
		arg.Accuracy,
		arg.Pp,
		arg.Priority,
	)
	return err
}

const insertNature = `-- name: InsertNature :exec
INSERT INTO natures (id, name_ja, name_ja_source, name_en, plus, minus)
VALUES (?, ?, ?, ?, ?, ?)
`

type InsertNatureParams struct {
	ID           string
	NameJa       string
	NameJaSource string
	NameEn       string
	Plus         sql.NullString
	Minus        sql.NullString
}

func (q *Queries) InsertNature(ctx context.Context, arg InsertNatureParams) error {
	_, err := q.db.ExecContext(ctx, insertNature,
		arg.ID,
		arg.NameJa,
		arg.NameJaSource,
		arg.NameEn,
		arg.Plus,
		arg.Minus,
	)
	return err
}

const insertRegulation = `-- name: InsertRegulation :exec
INSERT INTO regulations (id, name_ja, is_default, starts_on, ends_on)
VALUES (?, ?, ?, ?, ?)
`

type InsertRegulationParams struct {
	ID        string
	NameJa    string
	IsDefault bool
	StartsOn  sql.NullTime
	EndsOn    sql.NullTime
}

func (q *Queries) InsertRegulation(ctx context.Context, arg InsertRegulationParams) error {
	_, err := q.db.ExecContext(ctx, insertRegulation,
		arg.ID,
		arg.NameJa,
		arg.IsDefault,
		arg.StartsOn,
		arg.EndsOn,
	)
	return err
}

const insertRegulationAbility = `-- name: InsertRegulationAbility :exec
INSERT INTO regulation_abilities (regulation_id, ability_id)
VALUES (?, ?)
`

type InsertRegulationAbilityParams struct {
	RegulationID string
	AbilityID    string
}

func (q *Queries) InsertRegulationAbility(ctx context.Context, arg InsertRegulationAbilityParams) error {
	_, err := q.db.ExecContext(ctx, insertRegulationAbility, arg.RegulationID, arg.AbilityID)
	return err
}

const insertRegulationItem = `-- name: InsertRegulationItem :exec
INSERT INTO regulation_items (regulation_id, item_id)
VALUES (?, ?)
`

type InsertRegulationItemParams struct {
	RegulationID string
	ItemID       string
}

func (q *Queries) InsertRegulationItem(ctx context.Context, arg InsertRegulationItemParams) error {
	_, err := q.db.ExecContext(ctx, insertRegulationItem, arg.RegulationID, arg.ItemID)
	return err
}

const insertRegulationMove = `-- name: InsertRegulationMove :exec
INSERT INTO regulation_moves (regulation_id, move_id)
VALUES (?, ?)
`

type InsertRegulationMoveParams struct {
	RegulationID string
	MoveID       string
}

func (q *Queries) InsertRegulationMove(ctx context.Context, arg InsertRegulationMoveParams) error {
	_, err := q.db.ExecContext(ctx, insertRegulationMove, arg.RegulationID, arg.MoveID)
	return err
}

const insertRegulationSpecies = `-- name: InsertRegulationSpecies :exec
INSERT INTO regulation_species (regulation_id, species_key)
VALUES (?, ?)
`

type InsertRegulationSpeciesParams struct {
	RegulationID string
	SpeciesKey   string
}

func (q *Queries) InsertRegulationSpecies(ctx context.Context, arg InsertRegulationSpeciesParams) error {
	_, err := q.db.ExecContext(ctx, insertRegulationSpecies, arg.RegulationID, arg.SpeciesKey)
	return err
}

const insertSpecies = `-- name: InsertSpecies :exec
INSERT INTO species (` + "`" + `key` + "`" + `, dex_no, form, showdown_id, name_ja, name_ja_source, name_en, type1, type2,
                      base_hp, base_atk, base_def, base_spa, base_spd, base_spe, is_mega, base_species_key, required_item_id)
VALUES (?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?, ?)
`

type InsertSpeciesParams struct {
	Key            string
	DexNo          uint16
	Form           uint16
	ShowdownID     string
	NameJa         string
	NameJaSource   string
	NameEn         string
	Type1          string
	Type2          sql.NullString
	BaseHp         uint16
	BaseAtk        uint16
	BaseDef        uint16
	BaseSpa        uint16
	BaseSpd        uint16
	BaseSpe        uint16
	IsMega         bool
	BaseSpeciesKey sql.NullString
	RequiredItemID sql.NullString
}

func (q *Queries) InsertSpecies(ctx context.Context, arg InsertSpeciesParams) error {
	_, err := q.db.ExecContext(ctx, insertSpecies,
		arg.Key,
		arg.DexNo,
		arg.Form,
		arg.ShowdownID,
		arg.NameJa,
		arg.NameJaSource,
		arg.NameEn,
		arg.Type1,
		arg.Type2,
		arg.BaseHp,
		arg.BaseAtk,
		arg.BaseDef,
		arg.BaseSpa,
		arg.BaseSpd,
		arg.BaseSpe,
		arg.IsMega,
		arg.BaseSpeciesKey,
		arg.RequiredItemID,
	)
	return err
}

const insertSpeciesAbility = `-- name: InsertSpeciesAbility :exec
INSERT INTO species_abilities (species_key, slot, ability_id)
VALUES (?, ?, ?)
`

type InsertSpeciesAbilityParams struct {
	SpeciesKey string
	Slot       uint8
	AbilityID  string
}

func (q *Queries) InsertSpeciesAbility(ctx context.Context, arg InsertSpeciesAbilityParams) error {
	_, err := q.db.ExecContext(ctx, insertSpeciesAbility, arg.SpeciesKey, arg.Slot, arg.AbilityID)
	return err
}

const insertType = `-- name: InsertType :exec
INSERT INTO types (id, sort_order, name_ja, name_ja_source)
VALUES (?, ?, ?, ?)
`

type InsertTypeParams struct {
	ID           string
	SortOrder    uint16
	NameJa       string
	NameJaSource string
}

func (q *Queries) InsertType(ctx context.Context, arg InsertTypeParams) error {
	_, err := q.db.ExecContext(ctx, insertType,
		arg.ID,
		arg.SortOrder,
		arg.NameJa,
		arg.NameJaSource,
	)
	return err
}

const insertTypeChart = `-- name: InsertTypeChart :exec
INSERT INTO type_chart (attack_type, defense_type, code)
VALUES (?, ?, ?)
`

type InsertTypeChartParams struct {
	AttackType  string
	DefenseType string
	Code        uint8
}

func (q *Queries) InsertTypeChart(ctx context.Context, arg InsertTypeChartParams) error {
	_, err := q.db.ExecContext(ctx, insertTypeChart, arg.AttackType, arg.DefenseType, arg.Code)
	return err
}

const listAbilities = `-- name: ListAbilities :many
SELECT id, name_ja, name_ja_source, name_en
FROM abilities
ORDER BY id
`

func (q *Queries) ListAbilities(ctx context.Context) ([]Ability, error) {
	rows, err := q.db.QueryContext(ctx, listAbilities)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Ability
	for rows.Next() {
		var i Ability
		if err := rows.Scan(
			&i.ID,
			&i.NameJa,
			&i.NameJaSource,
			&i.NameEn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAbilityEffects = `-- name: ListAbilityEffects :many
SELECT ability_id, effect
FROM ability_effects
ORDER BY ability_id
`

func (q *Queries) ListAbilityEffects(ctx context.Context) ([]AbilityEffect, error) {
	rows, err := q.db.QueryContext(ctx, listAbilityEffects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []AbilityEffect
	for rows.Next() {
		var i AbilityEffect
		if err := rows.Scan(&i.AbilityID, &i.Effect); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listAllSpeciesAbilities = `-- name: ListAllSpeciesAbilities :many
SELECT species_key, slot, ability_id
FROM species_abilities
ORDER BY species_key, slot
`

func (q *Queries) ListAllSpeciesAbilities(ctx context.Context) ([]SpeciesAbility, error) {
	rows, err := q.db.QueryContext(ctx, listAllSpeciesAbilities)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SpeciesAbility
	for rows.Next() {
		var i SpeciesAbility
		if err := rows.Scan(&i.SpeciesKey, &i.Slot, &i.AbilityID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listDataVersions = `-- name: ListDataVersions :many
SELECT source, version, checksum, imported_at
FROM data_versions
ORDER BY source
`

func (q *Queries) ListDataVersions(ctx context.Context) ([]DataVersion, error) {
	rows, err := q.db.QueryContext(ctx, listDataVersions)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []DataVersion
	for rows.Next() {
		var i DataVersion
		if err := rows.Scan(
			&i.Source,
			&i.Version,
			&i.Checksum,
			&i.ImportedAt,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItemEffects = `-- name: ListItemEffects :many
SELECT item_id, effect
FROM item_effects
ORDER BY item_id
`

func (q *Queries) ListItemEffects(ctx context.Context) ([]ItemEffect, error) {
	rows, err := q.db.QueryContext(ctx, listItemEffects)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ItemEffect
	for rows.Next() {
		var i ItemEffect
		if err := rows.Scan(&i.ItemID, &i.Effect); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listItems = `-- name: ListItems :many
SELECT id, name_ja, name_ja_source, name_en
FROM items
ORDER BY id
`

func (q *Queries) ListItems(ctx context.Context) ([]Item, error) {
	rows, err := q.db.QueryContext(ctx, listItems)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Item
	for rows.Next() {
		var i Item
		if err := rows.Scan(
			&i.ID,
			&i.NameJa,
			&i.NameJaSource,
			&i.NameEn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listMoves = `-- name: ListMoves :many
SELECT id, name_ja, name_ja_source, name_en, type, category, power, accuracy, pp, priority
FROM moves
ORDER BY id
`

func (q *Queries) ListMoves(ctx context.Context) ([]Move, error) {
	rows, err := q.db.QueryContext(ctx, listMoves)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Move
	for rows.Next() {
		var i Move
		if err := rows.Scan(
			&i.ID,
			&i.NameJa,
			&i.NameJaSource,
			&i.NameEn,
			&i.Type,
			&i.Category,
			&i.Power,
			&i.Accuracy,
			&i.Pp,
			&i.Priority,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listNatures = `-- name: ListNatures :many

SELECT id, name_ja, name_ja_source, name_en, plus, minus
FROM natures
ORDER BY id
`

// ---------------------------------------------------------------------------------------------
// 性格(000006。ADR-0105 §4)
func (q *Queries) ListNatures(ctx context.Context) ([]Nature, error) {
	rows, err := q.db.QueryContext(ctx, listNatures)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Nature
	for rows.Next() {
		var i Nature
		if err := rows.Scan(
			&i.ID,
			&i.NameJa,
			&i.NameJaSource,
			&i.NameEn,
			&i.Plus,
			&i.Minus,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRegulationAbilityIDs = `-- name: ListRegulationAbilityIDs :many
SELECT ability_id
FROM regulation_abilities
WHERE regulation_id = ?
ORDER BY ability_id
`

func (q *Queries) ListRegulationAbilityIDs(ctx context.Context, regulationID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listRegulationAbilityIDs, regulationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var ability_id string
		if err := rows.Scan(&ability_id); err != nil {
			return nil, err
		}
		items = append(items, ability_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRegulationMoveIDs = `-- name: ListRegulationMoveIDs :many
SELECT move_id
FROM regulation_moves
WHERE regulation_id = ?
ORDER BY move_id
`

func (q *Queries) ListRegulationMoveIDs(ctx context.Context, regulationID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listRegulationMoveIDs, regulationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var move_id string
		if err := rows.Scan(&move_id); err != nil {
			return nil, err
		}
		items = append(items, move_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRegulationSpeciesKeys = `-- name: ListRegulationSpeciesKeys :many
SELECT species_key
FROM regulation_species
WHERE regulation_id = ?
ORDER BY species_key
`

func (q *Queries) ListRegulationSpeciesKeys(ctx context.Context, regulationID string) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listRegulationSpeciesKeys, regulationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var species_key string
		if err := rows.Scan(&species_key); err != nil {
			return nil, err
		}
		items = append(items, species_key)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listRegulations = `-- name: ListRegulations :many
SELECT id, name_ja, is_default, starts_on, ends_on
FROM regulations
ORDER BY id
`

type ListRegulationsRow struct {
	ID        string
	NameJa    string
	IsDefault bool
	StartsOn  sql.NullTime
	EndsOn    sql.NullTime
}

func (q *Queries) ListRegulations(ctx context.Context) ([]ListRegulationsRow, error) {
	rows, err := q.db.QueryContext(ctx, listRegulations)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListRegulationsRow
	for rows.Next() {
		var i ListRegulationsRow
		if err := rows.Scan(
			&i.ID,
			&i.NameJa,
			&i.IsDefault,
			&i.StartsOn,
			&i.EndsOn,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSpecies = `-- name: ListSpecies :many

SELECT ` + "`" + `key` + "`" + `, dex_no, form, showdown_id, name_ja, name_ja_source, name_en, type1, type2,
       base_hp, base_atk, base_def, base_spa, base_spd, base_spe,
       is_mega, base_species_key, required_item_id
FROM species
ORDER BY ` + "`" + `key` + "`" + `
`

// ---------------------------------------------------------------------------------------------
// 内部 API GET /internal/pokedex/master と pokedex export の全件読み出し(ADR-0105 §2・§5)。
// 使用可能集合で絞らない(絞り込みは export と検索が集合テーブルで行う)。
func (q *Queries) ListSpecies(ctx context.Context) ([]Species, error) {
	rows, err := q.db.QueryContext(ctx, listSpecies)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Species
	for rows.Next() {
		var i Species
		if err := rows.Scan(
			&i.Key,
			&i.DexNo,
			&i.Form,
			&i.ShowdownID,
			&i.NameJa,
			&i.NameJaSource,
			&i.NameEn,
			&i.Type1,
			&i.Type2,
			&i.BaseHp,
			&i.BaseAtk,
			&i.BaseDef,
			&i.BaseSpa,
			&i.BaseSpd,
			&i.BaseSpe,
			&i.IsMega,
			&i.BaseSpeciesKey,
			&i.RequiredItemID,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSpeciesAbilities = `-- name: ListSpeciesAbilities :many
SELECT species_key, slot, ability_id
FROM species_abilities
WHERE species_key = ?
ORDER BY slot
`

func (q *Queries) ListSpeciesAbilities(ctx context.Context, speciesKey string) ([]SpeciesAbility, error) {
	rows, err := q.db.QueryContext(ctx, listSpeciesAbilities, speciesKey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SpeciesAbility
	for rows.Next() {
		var i SpeciesAbility
		if err := rows.Scan(&i.SpeciesKey, &i.Slot, &i.AbilityID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSpeciesAbilityNames = `-- name: ListSpeciesAbilityNames :many
SELECT sa.slot, a.id, a.name_ja
FROM species_abilities sa
JOIN abilities a ON a.id = sa.ability_id
WHERE sa.species_key = ?
ORDER BY sa.slot
`

type ListSpeciesAbilityNamesRow struct {
	Slot   uint8
	ID     string
	NameJa string
}

func (q *Queries) ListSpeciesAbilityNames(ctx context.Context, speciesKey string) ([]ListSpeciesAbilityNamesRow, error) {
	rows, err := q.db.QueryContext(ctx, listSpeciesAbilityNames, speciesKey)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSpeciesAbilityNamesRow
	for rows.Next() {
		var i ListSpeciesAbilityNamesRow
		if err := rows.Scan(&i.Slot, &i.ID, &i.NameJa); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSpeciesKeys = `-- name: ListSpeciesKeys :many

SELECT ` + "`" + `key` + "`" + `, showdown_id
FROM species
`

type ListSpeciesKeysRow struct {
	Key        string
	ShowdownID string
}

// 冪等な投入(importer.Apply。ADR-0101 §9)。全置き換えを1トランザクションで行う。
// 自己参照の外部キー(species.base_species_key)があるので、削除はメガを先・挿入はメガを後にする。
func (q *Queries) ListSpeciesKeys(ctx context.Context) ([]ListSpeciesKeysRow, error) {
	rows, err := q.db.QueryContext(ctx, listSpeciesKeys)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []ListSpeciesKeysRow
	for rows.Next() {
		var i ListSpeciesKeysRow
		if err := rows.Scan(&i.Key, &i.ShowdownID); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listSpeciesLearnset = `-- name: ListSpeciesLearnset :many
SELECT l.move_id
FROM learnsets l
JOIN regulation_moves rm ON rm.move_id = l.move_id
WHERE l.species_key = ? AND rm.regulation_id = ?
ORDER BY l.move_id
`

type ListSpeciesLearnsetParams struct {
	SpeciesKey   string
	RegulationID string
}

func (q *Queries) ListSpeciesLearnset(ctx context.Context, arg ListSpeciesLearnsetParams) ([]string, error) {
	rows, err := q.db.QueryContext(ctx, listSpeciesLearnset, arg.SpeciesKey, arg.RegulationID)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []string
	for rows.Next() {
		var move_id string
		if err := rows.Scan(&move_id); err != nil {
			return nil, err
		}
		items = append(items, move_id)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTypeChart = `-- name: ListTypeChart :many
SELECT attack_type, defense_type, code
FROM type_chart
`

func (q *Queries) ListTypeChart(ctx context.Context) ([]TypeChart, error) {
	rows, err := q.db.QueryContext(ctx, listTypeChart)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []TypeChart
	for rows.Next() {
		var i TypeChart
		if err := rows.Scan(&i.AttackType, &i.DefenseType, &i.Code); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const listTypes = `-- name: ListTypes :many

SELECT id, sort_order, name_ja, name_ja_source
FROM types
ORDER BY sort_order
`

// sqlc のクエリ(ADR-0100 §1)。services/internal/master(DB行→engine型の写像)が
// 受け取る素朴な行の型(TypeRow・SpeciesRow 等)にそのまま詰め替えられる列の並びにする。
func (q *Queries) ListTypes(ctx context.Context) ([]Type, error) {
	rows, err := q.db.QueryContext(ctx, listTypes)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []Type
	for rows.Next() {
		var i Type
		if err := rows.Scan(
			&i.ID,
			&i.SortOrder,
			&i.NameJa,
			&i.NameJaSource,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchItems = `-- name: SearchItems :many
SELECT i.id, i.name_ja
FROM items i
JOIN regulation_items ri ON ri.item_id = i.id
WHERE ri.regulation_id = ? AND i.name_ja LIKE ?
ORDER BY i.name_ja, i.id
LIMIT ?
`

type SearchItemsParams struct {
	RegulationID string
	Pattern      string
	Limit        int32
}

type SearchItemsRow struct {
	ID     string
	NameJa string
}

func (q *Queries) SearchItems(ctx context.Context, arg SearchItemsParams) ([]SearchItemsRow, error) {
	rows, err := q.db.QueryContext(ctx, searchItems, arg.RegulationID, arg.Pattern, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchItemsRow
	for rows.Next() {
		var i SearchItemsRow
		if err := rows.Scan(&i.ID, &i.NameJa); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchMoves = `-- name: SearchMoves :many
SELECT m.id, m.name_ja, m.type, m.category, m.power, m.priority
FROM moves m
JOIN regulation_moves rm ON rm.move_id = m.id
WHERE rm.regulation_id = ? AND m.name_ja LIKE ?
ORDER BY m.name_ja, m.id
LIMIT ?
`

type SearchMovesParams struct {
	RegulationID string
	Pattern      string
	Limit        int32
}

type SearchMovesRow struct {
	ID       string
	NameJa   string
	Type     string
	Category string
	Power    uint16
	Priority int8
}

func (q *Queries) SearchMoves(ctx context.Context, arg SearchMovesParams) ([]SearchMovesRow, error) {
	rows, err := q.db.QueryContext(ctx, searchMoves, arg.RegulationID, arg.Pattern, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchMovesRow
	for rows.Next() {
		var i SearchMovesRow
		if err := rows.Scan(
			&i.ID,
			&i.NameJa,
			&i.Type,
			&i.Category,
			&i.Power,
			&i.Priority,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}

const searchSpecies = `-- name: SearchSpecies :many

SELECT s.` + "`" + `key` + "`" + `, s.dex_no, s.form, s.name_ja, s.type1, s.type2
FROM species s
JOIN regulation_species rs ON rs.species_key = s.` + "`" + `key` + "`" + `
WHERE rs.regulation_id = ? AND s.name_ja LIKE ?
ORDER BY s.dex_no, s.form
LIMIT ?
`

type SearchSpeciesParams struct {
	RegulationID string
	Pattern      string
	Limit        int32
}

type SearchSpeciesRow struct {
	Key    string
	DexNo  uint16
	Form   uint16
	NameJa string
	Type1  string
	Type2  sql.NullString
}

// ---------------------------------------------------------------------------------------------
// 公開の検索 API(/api/pokedex/*。ADR-0105 §3)。pattern は呼び出し側が LIKE の特殊文字(\ % _)を
// \ でエスケープし、末尾に % を付けた前方一致のパターン。name_ja の照合順序は utf8mb4_ja_0900_as_cs
// (ADR-0100 §2。ひらがなとカタカナを区別しない)。
func (q *Queries) SearchSpecies(ctx context.Context, arg SearchSpeciesParams) ([]SearchSpeciesRow, error) {
	rows, err := q.db.QueryContext(ctx, searchSpecies, arg.RegulationID, arg.Pattern, arg.Limit)
	if err != nil {
		return nil, err
	}
	defer rows.Close()
	var items []SearchSpeciesRow
	for rows.Next() {
		var i SearchSpeciesRow
		if err := rows.Scan(
			&i.Key,
			&i.DexNo,
			&i.Form,
			&i.NameJa,
			&i.Type1,
			&i.Type2,
		); err != nil {
			return nil, err
		}
		items = append(items, i)
	}
	if err := rows.Close(); err != nil {
		return nil, err
	}
	if err := rows.Err(); err != nil {
		return nil, err
	}
	return items, nil
}
