// Code generated by sqlc. DO NOT EDIT.
// versions:
//   sqlc v1.31.1

package store

import (
	"context"
)

type Querier interface {
	DeleteAbilities(ctx context.Context) error
	DeleteAbilityEffects(ctx context.Context) error
	DeleteDataVersions(ctx context.Context) error
	DeleteItemEffects(ctx context.Context) error
	DeleteItems(ctx context.Context) error
	DeleteLearnsets(ctx context.Context) error
	DeleteMegaSpecies(ctx context.Context) error
	DeleteMoveEffects(ctx context.Context) error
	DeleteMoves(ctx context.Context) error
	DeleteNatures(ctx context.Context) error
	DeleteRegulationAbilities(ctx context.Context) error
	DeleteRegulationItems(ctx context.Context) error
	DeleteRegulationMoves(ctx context.Context) error
	DeleteRegulationSpecies(ctx context.Context) error
	DeleteRegulations(ctx context.Context) error
	DeleteRemainingSpecies(ctx context.Context) error
	DeleteSpeciesAbilities(ctx context.Context) error
	DeleteTypeChart(ctx context.Context) error
	DeleteTypes(ctx context.Context) error
	GetAbility(ctx context.Context, id string) (Ability, error)
	GetAbilityEffect(ctx context.Context, abilityID string) (AbilityEffect, error)
	GetDataVersion(ctx context.Context, source string) (DataVersion, error)
	GetDefaultRegulation(ctx context.Context) (GetDefaultRegulationRow, error)
	GetItem(ctx context.Context, id string) (Item, error)
	GetItemEffect(ctx context.Context, itemID string) (ItemEffect, error)
	GetMove(ctx context.Context, id string) (GetMoveRow, error)
	GetSpeciesByKey(ctx context.Context, key string) (Species, error)
	InsertAbility(ctx context.Context, arg InsertAbilityParams) error
	InsertAbilityEffect(ctx context.Context, arg InsertAbilityEffectParams) error
	InsertDataVersion(ctx context.Context, arg InsertDataVersionParams) error
	InsertItem(ctx context.Context, arg InsertItemParams) error
	InsertItemEffect(ctx context.Context, arg InsertItemEffectParams) error
	InsertLearnset(ctx context.Context, arg InsertLearnsetParams) error
	InsertMove(ctx context.Context, arg InsertMoveParams) error
	InsertMoveEffect(ctx context.Context, arg InsertMoveEffectParams) error
	InsertNature(ctx context.Context, arg InsertNatureParams) error
	InsertRegulation(ctx context.Context, arg InsertRegulationParams) error
	InsertRegulationAbility(ctx context.Context, arg InsertRegulationAbilityParams) error
	InsertRegulationItem(ctx context.Context, arg InsertRegulationItemParams) error
	InsertRegulationMove(ctx context.Context, arg InsertRegulationMoveParams) error
	InsertRegulationSpecies(ctx context.Context, arg InsertRegulationSpeciesParams) error
	InsertSpecies(ctx context.Context, arg InsertSpeciesParams) error
	InsertSpeciesAbility(ctx context.Context, arg InsertSpeciesAbilityParams) error
	InsertType(ctx context.Context, arg InsertTypeParams) error
	InsertTypeChart(ctx context.Context, arg InsertTypeChartParams) error
	ListAbilities(ctx context.Context) ([]Ability, error)
	ListAbilityEffects(ctx context.Context) ([]AbilityEffect, error)
	ListAllSpeciesAbilities(ctx context.Context) ([]SpeciesAbility, error)
	ListDataVersions(ctx context.Context) ([]DataVersion, error)
	ListItemEffects(ctx context.Context) ([]ItemEffect, error)
	ListItems(ctx context.Context) ([]Item, error)
	ListMoveEffects(ctx context.Context) ([]MoveEffect, error)
	ListMoves(ctx context.Context) ([]Move, error)
	// ---------------------------------------------------------------------------------------------
	// 性格(000006。ADR-0105 §4)
	ListNatures(ctx context.Context) ([]Nature, error)
	ListRegulationAbilityIDs(ctx context.Context, regulationID string) ([]string, error)
	ListRegulationMoveIDs(ctx context.Context, regulationID string) ([]string, error)
	ListRegulationSpeciesKeys(ctx context.Context, regulationID string) ([]string, error)
	ListRegulations(ctx context.Context) ([]ListRegulationsRow, error)
	// ---------------------------------------------------------------------------------------------
	// 内部 API GET /internal/pokedex/master と pokedex export の全件読み出し(ADR-0105 §2・§5)。
	// 使用可能集合で絞らない(絞り込みは export と検索が集合テーブルで行う)。
	ListSpecies(ctx context.Context) ([]Species, error)
	ListSpeciesAbilities(ctx context.Context, speciesKey string) ([]SpeciesAbility, error)
	ListSpeciesAbilityNames(ctx context.Context, speciesKey string) ([]ListSpeciesAbilityNamesRow, error)
	// 冪等な投入(importer.Apply。ADR-0101 §9)。全置き換えを1トランザクションで行う。
	// 自己参照の外部キー(species.base_species_key)があるので、削除はメガを先・挿入はメガを後にする。
	ListSpeciesKeys(ctx context.Context) ([]ListSpeciesKeysRow, error)
	ListSpeciesLearnset(ctx context.Context, arg ListSpeciesLearnsetParams) ([]string, error)
	ListTypeChart(ctx context.Context) ([]TypeChart, error)
	// sqlc のクエリ(ADR-0100 §1)。services/internal/master(DB行→engine型の写像)が
	// 受け取る素朴な行の型(TypeRow・SpeciesRow 等)にそのまま詰め替えられる列の並びにする。
	ListTypes(ctx context.Context) ([]Type, error)
	SearchItems(ctx context.Context, arg SearchItemsParams) ([]SearchItemsRow, error)
	SearchMoves(ctx context.Context, arg SearchMovesParams) ([]SearchMovesRow, error)
	// ---------------------------------------------------------------------------------------------
	// 公開の検索 API(/api/pokedex/*。ADR-0105 §3)。pattern は呼び出し側が LIKE の特殊文字(\ % _)を
	// \ でエスケープし、末尾に % を付けた前方一致のパターン。name_ja の照合順序は utf8mb4_ja_0900_as_cs
	// (ADR-0100 §2。ひらがなとカタカナを区別しない)。
	SearchSpecies(ctx context.Context, arg SearchSpeciesParams) ([]SearchSpeciesRow, error)
}

var _ Querier = (*Queries)(nil)
