// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"fmt"
	"net/http"

	"github.com/labstack/echo/v5"
	"github.com/oapi-codegen/runtime"
)

// Defines values for ErrorCode.
const (
	InternalError     ErrorCode = "internal_error"
	InvalidRequest    ErrorCode = "invalid_request"
	MasterUnavailable ErrorCode = "master_unavailable"
)

// Valid indicates whether the value is a known member of the ErrorCode enum.
func (e ErrorCode) Valid() bool {
	switch e {
	case InternalError:
		return true
	case InvalidRequest:
		return true
	case MasterUnavailable:
		return true
	default:
		return false
	}
}

// Defines values for HealthStatus.
const (
	Ok HealthStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthStatus enum.
func (e HealthStatus) Valid() bool {
	switch e {
	case Ok:
		return true
	default:
		return false
	}
}

// Error defines model for Error.
type Error struct {
	Code    ErrorCode `json:"code"`
	Message string    `json:"message"`
}

// ErrorCode defines model for ErrorCode.
type ErrorCode string

// Health defines model for Health.
type Health struct {
	Status HealthStatus `json:"status"`
}

// HealthStatus defines model for Health.Status.
type HealthStatus string

// PokemonListResponse defines model for PokemonListResponse.
type PokemonListResponse struct {
	// Pokemon The available pokemon, sorted by pokemonId in ascending order.
	Pokemon []SpeedPokemon `json:"pokemon"`

	// RegulationId The regulation whose available set the list is (ADR-0600 §4).
	//
	// Example: example
	RegulationId string `json:"regulationId"`
}

// SpeedPokemon defines model for SpeedPokemon.
type SpeedPokemon struct {
	// BaseSpeed Example: 100
	BaseSpeed int `json:"baseSpeed"`

	// NameJa Example: カソウドリ
	NameJa string `json:"nameJa"`

	// PokemonId Example: 9001-000
	PokemonId string `json:"pokemonId"`

	// Types One or two lowercase type IDs, for display only (the 18 types are not listed in the contract).
	Types []string `json:"types"`
}

// DeviceId defines model for DeviceId.
type DeviceId = string

// SessionId defines model for SessionId.
type SessionId = string

// ListPokemonParams defines parameters for ListPokemon.
type ListPokemonParams struct {
	XDeviceId  DeviceId  `json:"X-Device-Id"`
	XSessionId SessionId `json:"X-Session-Id"`
}

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// PublicHealth Ingress smoke check
	// (GET /api/speed/healthz)
	PublicHealth(ctx *echo.Context) error
	// ListPokemon List the pokemon available in the default regulation
	// (GET /api/speed/v1/pokemon)
	ListPokemon(ctx *echo.Context, params ListPokemonParams) error
	// Health Pod health check
	// (GET /healthz)
	Health(ctx *echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// PublicHealth converts echo context to params.
func (w *ServerInterfaceWrapper) PublicHealth(ctx *echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PublicHealth(ctx)
	return err
}

// ListPokemon converts echo context to params.
func (w *ServerInterfaceWrapper) ListPokemon(ctx *echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListPokemonParams

	headers := ctx.Request().Header
	// ------------- Required header parameter "X-Device-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Device-Id")]; found {
		var XDeviceId DeviceId
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-Device-Id, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Device-Id", valueList[0], &XDeviceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-Device-Id: %s", err))
		}

		params.XDeviceId = XDeviceId
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter X-Device-Id is required, but not found"))
	}
	// ------------- Required header parameter "X-Session-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Session-Id")]; found {
		var XSessionId SessionId
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-Session-Id, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Session-Id", valueList[0], &XSessionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-Session-Id: %s", err))
		}

		params.XSessionId = XSessionId
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter X-Session-Id is required, but not found"))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListPokemon(ctx, params)
	return err
}

// Health converts echo context to params.
func (w *ServerInterfaceWrapper) Health(ctx *echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Health(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
}

// RegisterHandlersOptions configures RegisterHandlersWithOptions.
type RegisterHandlersOptions struct {
	// BaseURL is prepended to every registered path so the API can be served
	// under a prefix.
	BaseURL string
	// OperationMiddlewares lets the caller attach per-operation middleware at
	// registration time. The map key is the OpenAPI `operationId` value as it
	// appears in the spec (the raw, un-normalized form). Operations that have
	// no entry are registered with no extra middleware. A nil map disables
	// per-operation middleware entirely.
	OperationMiddlewares map[string][]echo.MiddlewareFunc
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{})
}

// RegisterHandlersWithBaseURL registers handlers and prepends BaseURL to the
// paths so the API can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{BaseURL: baseURL})
}

// RegisterHandlersWithOptions registers handlers using the supplied options,
// including any per-operation middleware.
func RegisterHandlersWithOptions(router EchoRouter, si ServerInterface, options RegisterHandlersOptions) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(options.BaseURL+"/healthz", wrapper.Health, options.OperationMiddlewares["health"]...)
	router.GET(options.BaseURL+"/api/speed/healthz", wrapper.PublicHealth, options.OperationMiddlewares["publicHealth"]...)
	router.GET(options.BaseURL+"/api/speed/v1/pokemon", wrapper.ListPokemon, options.OperationMiddlewares["listPokemon"]...)

}
