// Package api provides primitives to interact with the openapi HTTP API.
//
// Code generated by github.com/oapi-codegen/oapi-codegen/v2 version v2.8.0 DO NOT EDIT.
package api

import (
	"fmt"
	"net/http"

	"github.com/labstack/echo/v5"
	"github.com/oapi-codegen/runtime"
)

// Defines values for ErrorCode.
const (
	InternalError     ErrorCode = "internal_error"
	InvalidRequest    ErrorCode = "invalid_request"
	MasterUnavailable ErrorCode = "master_unavailable"
	RequestTooLarge   ErrorCode = "request_too_large"
	UnknownPokemon    ErrorCode = "unknown_pokemon"
)

// Valid indicates whether the value is a known member of the ErrorCode enum.
func (e ErrorCode) Valid() bool {
	switch e {
	case InternalError:
		return true
	case InvalidRequest:
		return true
	case MasterUnavailable:
		return true
	case RequestTooLarge:
		return true
	case UnknownPokemon:
		return true
	default:
		return false
	}
}

// Defines values for HealthStatus.
const (
	Ok HealthStatus = "ok"
)

// Valid indicates whether the value is a known member of the HealthStatus enum.
func (e HealthStatus) Valid() bool {
	switch e {
	case Ok:
		return true
	default:
		return false
	}
}

// Defines values for MinimalPresetId.
const (
	MinimalPresetIdMax        MinimalPresetId = "max"
	MinimalPresetIdNeutralMax MinimalPresetId = "neutral-max"
	MinimalPresetIdUninvested MinimalPresetId = "uninvested"
)

// Valid indicates whether the value is a known member of the MinimalPresetId enum.
func (e MinimalPresetId) Valid() bool {
	switch e {
	case MinimalPresetIdMax:
		return true
	case MinimalPresetIdNeutralMax:
		return true
	case MinimalPresetIdUninvested:
		return true
	default:
		return false
	}
}

// Defines values for NatureId.
const (
	Minus   NatureId = "minus"
	Neutral NatureId = "neutral"
	Plus    NatureId = "plus"
)

// Valid indicates whether the value is a known member of the NatureId enum.
func (e NatureId) Valid() bool {
	switch e {
	case Minus:
		return true
	case Neutral:
		return true
	case Plus:
		return true
	default:
		return false
	}
}

// Defines values for PositionRequestMode.
const (
	Custom PositionRequestMode = "custom"
	Preset PositionRequestMode = "preset"
	Raw    PositionRequestMode = "raw"
)

// Valid indicates whether the value is a known member of the PositionRequestMode enum.
func (e PositionRequestMode) Valid() bool {
	switch e {
	case Custom:
		return true
	case Preset:
		return true
	case Raw:
		return true
	default:
		return false
	}
}

// Defines values for PresetId.
const (
	PresetIdMax        PresetId = "max"
	PresetIdMaxPlus1   PresetId = "max-plus1"
	PresetIdMaxPlus2   PresetId = "max-plus2"
	PresetIdMaxScarf   PresetId = "max-scarf"
	PresetIdNeutralMax PresetId = "neutral-max"
	PresetIdUninvested PresetId = "uninvested"
)

// Valid indicates whether the value is a known member of the PresetId enum.
func (e PresetId) Valid() bool {
	switch e {
	case PresetIdMax:
		return true
	case PresetIdMaxPlus1:
		return true
	case PresetIdMaxPlus2:
		return true
	case PresetIdMaxScarf:
		return true
	case PresetIdNeutralMax:
		return true
	case PresetIdUninvested:
		return true
	default:
		return false
	}
}

// Error defines model for Error.
type Error struct {
	Code    ErrorCode `json:"code"`
	Message string    `json:"message"`
}

// ErrorCode defines model for ErrorCode.
type ErrorCode string

// Health defines model for Health.
type Health struct {
	Status HealthStatus `json:"status"`
}

// HealthStatus defines model for Health.Status.
type HealthStatus string

// MinimalPresetId A preset one can pick for one's own pokemon (ADR-0602 §5): the three rows of ADR-0601 §2 that carry
// no Choice Scarf, because `scarf` is chosen separately in a position request. The SP, nature and rank
// of each are the ones PresetId describes.
//
// Example: max
type MinimalPresetId string

// NatureId The effect of the nature on speed (ADR-0600 §3, the same meaning as the core's NatureEffect):
// minus = speed-down, neutral = no nature change, plus = speed-up.
//
// Example: plus
type NatureId string

// PokemonListResponse defines model for PokemonListResponse.
type PokemonListResponse struct {
	// Pokemon The available pokemon, sorted by pokemonId in ascending order.
	Pokemon []SpeedPokemon `json:"pokemon"`

	// RegulationId The regulation whose available set the list is (ADR-0600 §4).
	//
	// Example: example
	RegulationId string `json:"regulationId"`
}

// PositionRequest One's own pokemon, in one of the three shapes of ADR-0602 §2. Only `mode` is always required;
// which of the other fields must be present, and which must be absent, depends on `mode`.
type PositionRequest struct {
	// Mode Which shape the request has (ADR-0602 §2).
	// preset: pokemonId + preset + scarf. custom: pokemonId + sp + nature + rank + scarf.
	// raw: value, with an optional pokemonId for display only.
	//
	//
	// Example: preset
	Mode PositionRequestMode `json:"mode"`

	// Nature The effect of the nature on speed (ADR-0600 §3, the same meaning as the core's NatureEffect):
	// minus = speed-down, neutral = no nature change, plus = speed-up.
	//
	//
	// Example: plus
	Nature *NatureId `json:"nature,omitempty"`

	// PokemonId The pokemon of the read model. Required for preset and custom (its base speed is the input of
	// the formula); optional for raw, where it only resolves the name and types of the response.
	//
	//
	// Example: 9001-000
	PokemonId *string `json:"pokemonId,omitempty"`

	// Preset A preset one can pick for one's own pokemon (ADR-0602 §5): the three rows of ADR-0601 §2 that carry
	// no Choice Scarf, because `scarf` is chosen separately in a position request. The SP, nature and rank
	// of each are the ones PresetId describes.
	//
	//
	// Example: max
	Preset *MinimalPresetId `json:"preset,omitempty"`

	// Rank The speed rank (custom only), -6 to +6 (ADR-0600 §3).
	//
	// Example: 1
	Rank *int `json:"rank,omitempty"`

	// Scarf Whether one's own pokemon holds a Choice Scarf (preset and custom only).
	//
	// Example: false
	Scarf *bool `json:"scarf,omitempty"`

	// Sp The speed SP (custom only). The upper bound is the per-stat SP cap of the domain
	// (CLAUDE.md のドメイン規約・ADR-0600 §3。コアは engine.MaxSPPerStat を使う)。
	//
	//
	// Example: 32
	Sp *int `json:"sp,omitempty"`

	// Value The in-battle speed itself (raw only), used as given. Accepted values are the theoretical
	// minimum and maximum of the formula of ADR-0600 §3 over every base speed, SP, nature, rank and
	// Choice Scarf (ADR-0602 §3); the service derives those bounds from the formula, so they are
	// deliberately not repeated here as numbers.
	//
	//
	// Example: 301
	Value *int `json:"value,omitempty"`
}

// PositionRequestMode Which shape the request has (ADR-0602 §2).
// preset: pokemonId + preset + scarf. custom: pokemonId + sp + nature + rank + scarf.
// raw: value, with an optional pokemonId for display only.
//
// Example: preset
type PositionRequestMode string

// PositionResponse defines model for PositionResponse.
type PositionResponse struct {
	// Faster The number of table rows strictly faster than `speed`.
	//
	// Example: 12
	Faster  int           `json:"faster"`
	Pokemon *SpeedPokemon `json:"pokemon,omitempty"`

	// Slower The number of table rows strictly slower than `speed`.
	//
	// Example: 30
	Slower int `json:"slower"`

	// Speed The in-battle speed of one's own pokemon (ADR-0602 §3).
	//
	// Example: 301
	Speed int `json:"speed"`

	// Tie The table rows with exactly this speed, sorted as a tier is (pokemonId ascending, then the
	// preset order of ADR-0601 §2). An empty array means no speed tie.
	Tie []SpeedTableEntry `json:"tie"`
}

// PresetId A row preset of the speed table (ADR-0601 §2), listed in the table order. Display names are client
// resources and are not part of the contract.
// uninvested = SP 0, neutral nature; neutral-max = SP 32, neutral; max = SP 32, speed-up nature;
// max-scarf = max with Choice Scarf; max-plus1 = max at +1; max-plus2 = max at +2.
//
// Example: max-scarf
type PresetId string

// SpeedPokemon defines model for SpeedPokemon.
type SpeedPokemon struct {
	// BaseSpeed Example: 100
	BaseSpeed int `json:"baseSpeed"`

	// NameJa Example: テストカソウドリ
	NameJa string `json:"nameJa"`

	// PokemonId Example: 9001-000
	PokemonId string `json:"pokemonId"`

	// Types One or two lowercase type IDs, for display only (the 18 types are not listed in the contract).
	Types []string `json:"types"`
}

// SpeedTableEntry defines model for SpeedTableEntry.
type SpeedTableEntry struct {
	// BaseSpeed Example: 100
	BaseSpeed int `json:"baseSpeed"`

	// NameJa Example: テストカソウドリ
	NameJa string `json:"nameJa"`

	// PokemonId Example: 9001-000
	PokemonId string `json:"pokemonId"`

	// Preset A row preset of the speed table (ADR-0601 §2), listed in the table order. Display names are client
	// resources and are not part of the contract.
	// uninvested = SP 0, neutral nature; neutral-max = SP 32, neutral; max = SP 32, speed-up nature;
	// max-scarf = max with Choice Scarf; max-plus1 = max at +1; max-plus2 = max at +2.
	//
	//
	// Example: max-scarf
	Preset PresetId `json:"preset"`

	// Types One or two lowercase type IDs, for display only (the 18 types are not listed in the contract).
	Types []string `json:"types"`
}

// SpeedTier defines model for SpeedTier.
type SpeedTier struct {
	// Entries The rows with this speed, sorted by pokemonId ascending, then by the preset order of ADR-0601 §2.
	// Two or more entries mean a speed tie.
	Entries []SpeedTableEntry `json:"entries"`

	// Speed The in-battle speed shared by every entry of the tier.
	//
	// Example: 250
	Speed int `json:"speed"`
}

// TableResponse defines model for TableResponse.
type TableResponse struct {
	// Presets The presets actually used, in the order of ADR-0601 §2 (not the query order).
	Presets []PresetId `json:"presets"`

	// RegulationId The regulation whose available set the table is (ADR-0600 §4).
	//
	// Example: example
	RegulationId string `json:"regulationId"`

	// Tiers Tiers of the same speed, sorted by speed in descending order.
	Tiers []SpeedTier `json:"tiers"`
}

// DeviceId defines model for DeviceId.
type DeviceId = string

// SessionId defines model for SessionId.
type SessionId = string

// ListPokemonParams defines parameters for ListPokemon.
type ListPokemonParams struct {
	XDeviceId  DeviceId  `json:"X-Device-Id"`
	XSessionId SessionId `json:"X-Session-Id"`
}

// GetSpeedPositionParams defines parameters for GetSpeedPosition.
type GetSpeedPositionParams struct {
	XDeviceId  DeviceId  `json:"X-Device-Id"`
	XSessionId SessionId `json:"X-Session-Id"`
}

// GetSpeedTableParams defines parameters for GetSpeedTable.
type GetSpeedTableParams struct {
	// Presets The rows to include, comma separated (ADR-0601 §4). Omitted means all six presets.
	// The order given does not affect the result. An unknown ID, a duplicate, or an empty value
	// (`presets=`) is 400 invalid_request.
	Presets    *[]PresetId `form:"presets,omitempty" json:"presets,omitempty"`
	XDeviceId  DeviceId    `json:"X-Device-Id"`
	XSessionId SessionId   `json:"X-Session-Id"`
}

// GetSpeedPositionJSONRequestBody defines body for GetSpeedPosition for application/json ContentType.
type GetSpeedPositionJSONRequestBody = PositionRequest

// ServerInterface represents all server handlers.
type ServerInterface interface {
	// PublicHealth Ingress smoke check
	// (GET /api/speed/healthz)
	PublicHealth(ctx *echo.Context) error
	// ListPokemon List the pokemon available in the default regulation
	// (GET /api/speed/v1/pokemon)
	ListPokemon(ctx *echo.Context, params ListPokemonParams) error
	// GetSpeedPosition Locate one's own pokemon in the speed table
	// (POST /api/speed/v1/position)
	GetSpeedPosition(ctx *echo.Context, params GetSpeedPositionParams) error
	// GetSpeedTable Get the speed table of the default regulation
	// (GET /api/speed/v1/table)
	GetSpeedTable(ctx *echo.Context, params GetSpeedTableParams) error
	// Health Pod health check
	// (GET /healthz)
	Health(ctx *echo.Context) error
}

// ServerInterfaceWrapper converts echo contexts to parameters.
type ServerInterfaceWrapper struct {
	Handler ServerInterface
}

// PublicHealth converts echo context to params.
func (w *ServerInterfaceWrapper) PublicHealth(ctx *echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.PublicHealth(ctx)
	return err
}

// ListPokemon converts echo context to params.
func (w *ServerInterfaceWrapper) ListPokemon(ctx *echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params ListPokemonParams

	headers := ctx.Request().Header
	// ------------- Required header parameter "X-Device-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Device-Id")]; found {
		var XDeviceId DeviceId
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-Device-Id, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Device-Id", valueList[0], &XDeviceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-Device-Id: %s", err))
		}

		params.XDeviceId = XDeviceId
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter X-Device-Id is required, but not found"))
	}
	// ------------- Required header parameter "X-Session-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Session-Id")]; found {
		var XSessionId SessionId
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-Session-Id, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Session-Id", valueList[0], &XSessionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-Session-Id: %s", err))
		}

		params.XSessionId = XSessionId
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter X-Session-Id is required, but not found"))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.ListPokemon(ctx, params)
	return err
}

// GetSpeedPosition converts echo context to params.
func (w *ServerInterfaceWrapper) GetSpeedPosition(ctx *echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetSpeedPositionParams

	headers := ctx.Request().Header
	// ------------- Required header parameter "X-Device-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Device-Id")]; found {
		var XDeviceId DeviceId
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-Device-Id, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Device-Id", valueList[0], &XDeviceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-Device-Id: %s", err))
		}

		params.XDeviceId = XDeviceId
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter X-Device-Id is required, but not found"))
	}
	// ------------- Required header parameter "X-Session-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Session-Id")]; found {
		var XSessionId SessionId
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-Session-Id, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Session-Id", valueList[0], &XSessionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-Session-Id: %s", err))
		}

		params.XSessionId = XSessionId
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter X-Session-Id is required, but not found"))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetSpeedPosition(ctx, params)
	return err
}

// GetSpeedTable converts echo context to params.
func (w *ServerInterfaceWrapper) GetSpeedTable(ctx *echo.Context) error {
	var err error

	// Parameter object where we will unmarshal all parameters from the context
	var params GetSpeedTableParams
	// ------------- Optional query parameter "presets" -------------

	err = runtime.BindQueryParameterWithOptions("form", false, false, "presets", ctx.QueryParams(), &params.Presets, runtime.BindQueryParameterOptions{Type: "array", Format: ""})
	if err != nil {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter presets: %s", err))
	}

	headers := ctx.Request().Header
	// ------------- Required header parameter "X-Device-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Device-Id")]; found {
		var XDeviceId DeviceId
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-Device-Id, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Device-Id", valueList[0], &XDeviceId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-Device-Id: %s", err))
		}

		params.XDeviceId = XDeviceId
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter X-Device-Id is required, but not found"))
	}
	// ------------- Required header parameter "X-Session-Id" -------------
	if valueList, found := headers[http.CanonicalHeaderKey("X-Session-Id")]; found {
		var XSessionId SessionId
		n := len(valueList)
		if n != 1 {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Expected one value for X-Session-Id, got %d", n))
		}

		err = runtime.BindStyledParameterWithOptions("simple", "X-Session-Id", valueList[0], &XSessionId, runtime.BindStyledParameterOptions{ParamLocation: runtime.ParamLocationHeader, Explode: false, Required: true, Type: "string", Format: ""})
		if err != nil {
			return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Invalid format for parameter X-Session-Id: %s", err))
		}

		params.XSessionId = XSessionId
	} else {
		return echo.NewHTTPError(http.StatusBadRequest, fmt.Sprintf("Header parameter X-Session-Id is required, but not found"))
	}

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.GetSpeedTable(ctx, params)
	return err
}

// Health converts echo context to params.
func (w *ServerInterfaceWrapper) Health(ctx *echo.Context) error {
	var err error

	// Invoke the callback with all the unmarshaled arguments
	err = w.Handler.Health(ctx)
	return err
}

// This is a simple interface which specifies echo.Route addition functions which
// are present on both echo.Echo and echo.Group, since we want to allow using
// either of them for path registration
type EchoRouter interface {
	CONNECT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	DELETE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	GET(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	HEAD(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	OPTIONS(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	PATCH(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	POST(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	PUT(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
	TRACE(path string, h echo.HandlerFunc, m ...echo.MiddlewareFunc) echo.RouteInfo
}

// RegisterHandlersOptions configures RegisterHandlersWithOptions.
type RegisterHandlersOptions struct {
	// BaseURL is prepended to every registered path so the API can be served
	// under a prefix.
	BaseURL string
	// OperationMiddlewares lets the caller attach per-operation middleware at
	// registration time. The map key is the OpenAPI `operationId` value as it
	// appears in the spec (the raw, un-normalized form). Operations that have
	// no entry are registered with no extra middleware. A nil map disables
	// per-operation middleware entirely.
	OperationMiddlewares map[string][]echo.MiddlewareFunc
}

// RegisterHandlers adds each server route to the EchoRouter.
func RegisterHandlers(router EchoRouter, si ServerInterface) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{})
}

// RegisterHandlersWithBaseURL registers handlers and prepends BaseURL to the
// paths so the API can be served under a prefix.
func RegisterHandlersWithBaseURL(router EchoRouter, si ServerInterface, baseURL string) {
	RegisterHandlersWithOptions(router, si, RegisterHandlersOptions{BaseURL: baseURL})
}

// RegisterHandlersWithOptions registers handlers using the supplied options,
// including any per-operation middleware.
func RegisterHandlersWithOptions(router EchoRouter, si ServerInterface, options RegisterHandlersOptions) {

	wrapper := ServerInterfaceWrapper{
		Handler: si,
	}

	router.GET(options.BaseURL+"/healthz", wrapper.Health, options.OperationMiddlewares["health"]...)
	router.GET(options.BaseURL+"/api/speed/healthz", wrapper.PublicHealth, options.OperationMiddlewares["publicHealth"]...)
	router.GET(options.BaseURL+"/api/speed/v1/pokemon", wrapper.ListPokemon, options.OperationMiddlewares["listPokemon"]...)
	router.GET(options.BaseURL+"/api/speed/v1/table", wrapper.GetSpeedTable, options.OperationMiddlewares["getSpeedTable"]...)
	router.POST(options.BaseURL+"/api/speed/v1/position", wrapper.GetSpeedPosition, options.OperationMiddlewares["getSpeedPosition"]...)

}
