// SP3: speed API の生成型(ADR-0604 §2)。services/speed/api/openapi.yaml が正で、このファイルは手で編集しない。
// 再生成(web/ ディレクトリで実行):
//   npx openapi-typescript ../services/speed/api/openapi.yaml -o src/speed/speed.gen.ts
//   npx prettier --write src/speed/speed.gen.ts
// ルートの `make gen-ts` は Web レーンの持ち物なので変更せず、素早さレーンは上のコマンドを手で実行して
// 生成物をコミットする(ADR-0604 §2)。
/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
  "/healthz": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Pod health check */
    get: operations["health"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/speed/healthz": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /** Ingress smoke check */
    get: operations["publicHealth"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/speed/v1/pokemon": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * List the pokemon available in the default regulation
     * @description Returns the pokemon of the service-local read model (ADR-0600 §4), which is the available set of
     *     one regulation, sorted by pokemonId in ascending order (ADR-0600 §5).
     */
    get: operations["listPokemon"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/speed/v1/table": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    /**
     * Get the speed table of the default regulation
     * @description Returns, for every pokemon of the service-local read model (ADR-0600 §4), one row per selected preset
     *     (ADR-0601 §2), grouped into tiers of the same speed (ADR-0601 §3). Tiers are sorted by speed in
     *     descending order; inside a tier, entries are sorted by pokemonId ascending, then by the preset order
     *     of ADR-0601 §2. A tier with two or more entries is a speed tie.
     *     Check order: headers (400) → query (400) → read model absent (503) → 200 (ADR-0601 §5).
     */
    get: operations["getSpeedTable"];
    put?: never;
    post?: never;
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
  "/api/speed/v1/position": {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    get?: never;
    put?: never;
    /**
     * Locate one's own pokemon in the speed table
     * @description Returns the in-battle speed of one's own pokemon and where it falls in the speed table of the
     *     default regulation (ADR-0602 §3). The table is always the full six presets of ADR-0601 §2:
     *     `faster` and `slower` count its rows above and below the given speed, and `tie` lists the rows
     *     with exactly that speed (empty means no speed tie).
     *
     *     The input has three shapes, selected by `mode` (ADR-0602 §2):
     *     `preset` needs pokemonId, preset and scarf (the minimal choice: the SP, nature and rank of the
     *     chosen row of ADR-0601 §2, with the Choice Scarf switched independently);
     *     `custom` needs pokemonId, sp, nature, rank and scarf;
     *     `raw` needs value, the in-battle speed itself, and may name pokemonId for display only (its base
     *     speed is not used). A field the chosen mode does not need, a missing required field, a pokemonId
     *     not matching the NNNN-NNN format, or a value out of range is 400 invalid_request. A JSON `null`
     *     for an optional field is treated the same as omitting it.
     *
     *     Check order: headers (400) → body (400, or 413 request_too_large over 4 KiB) → read model
     *     absent (503) → unknown pokemonId (422) → 200.
     */
    post: operations["getSpeedPosition"];
    delete?: never;
    options?: never;
    head?: never;
    patch?: never;
    trace?: never;
  };
}
export type webhooks = Record<string, never>;
export interface components {
  schemas: {
    Health: {
      /** @enum {string} */
      status: "ok";
    };
    PokemonListResponse: {
      /**
       * @description The regulation whose available set the list is (ADR-0600 §4).
       * @example example
       */
      regulationId: string;
      /** @description The available pokemon, sorted by pokemonId in ascending order. */
      pokemon: components["schemas"]["SpeedPokemon"][];
    };
    SpeedPokemon: {
      /** @example 9001-000 */
      pokemonId: string;
      /** @example テストカソウドリ */
      nameJa: string;
      /** @description One or two lowercase type IDs, for display only (the 18 types are not listed in the contract). */
      types: string[];
      /** @example 100 */
      baseSpeed: number;
    };
    /**
     * @description A row preset of the speed table (ADR-0601 §2), listed in the table order. Display names are client
     *     resources and are not part of the contract.
     *     uninvested = SP 0, neutral nature; neutral-max = SP 32, neutral; max = SP 32, speed-up nature;
     *     max-scarf = max with Choice Scarf; max-plus1 = max at +1; max-plus2 = max at +2.
     * @example max-scarf
     * @enum {string}
     */
    PresetId: "uninvested" | "neutral-max" | "max" | "max-scarf" | "max-plus1" | "max-plus2";
    TableResponse: {
      /**
       * @description The regulation whose available set the table is (ADR-0600 §4).
       * @example example
       */
      regulationId: string;
      /** @description The presets actually used, in the order of ADR-0601 §2 (not the query order). */
      presets: components["schemas"]["PresetId"][];
      /** @description Tiers of the same speed, sorted by speed in descending order. */
      tiers: components["schemas"]["SpeedTier"][];
    };
    SpeedTier: {
      /**
       * @description The in-battle speed shared by every entry of the tier.
       * @example 250
       */
      speed: number;
      /**
       * @description The rows with this speed, sorted by pokemonId ascending, then by the preset order of ADR-0601 §2.
       *     Two or more entries mean a speed tie.
       */
      entries: components["schemas"]["SpeedTableEntry"][];
    };
    SpeedTableEntry: {
      /** @example 9001-000 */
      pokemonId: string;
      /** @example テストカソウドリ */
      nameJa: string;
      /** @description One or two lowercase type IDs, for display only (the 18 types are not listed in the contract). */
      types: string[];
      /** @example 100 */
      baseSpeed: number;
      preset: components["schemas"]["PresetId"];
    };
    /**
     * @description A preset one can pick for one's own pokemon (ADR-0602 §5): the three rows of ADR-0601 §2 that carry
     *     no Choice Scarf, because `scarf` is chosen separately in a position request. The SP, nature and rank
     *     of each are the ones PresetId describes.
     * @example max
     * @enum {string}
     */
    MinimalPresetId: "uninvested" | "neutral-max" | "max";
    /**
     * @description The effect of the nature on speed (ADR-0600 §3, the same meaning as the core's NatureEffect):
     *     minus = speed-down, neutral = no nature change, plus = speed-up.
     * @example plus
     * @enum {string}
     */
    NatureId: "minus" | "neutral" | "plus";
    /**
     * @description One's own pokemon, in one of the three shapes of ADR-0602 §2. Only `mode` is always required;
     *     which of the other fields must be present, and which must be absent, depends on `mode`.
     */
    PositionRequest: {
      /**
       * @description Which shape the request has (ADR-0602 §2).
       *     preset: pokemonId + preset + scarf. custom: pokemonId + sp + nature + rank + scarf.
       *     raw: value, with an optional pokemonId for display only.
       * @example preset
       * @enum {string}
       */
      mode: "preset" | "custom" | "raw";
      /**
       * @description The pokemon of the read model. Required for preset and custom (its base speed is the input of
       *     the formula); optional for raw, where it only resolves the name and types of the response.
       * @example 9001-000
       */
      pokemonId?: string;
      preset?: components["schemas"]["MinimalPresetId"];
      /**
       * @description Whether one's own pokemon holds a Choice Scarf (preset and custom only).
       * @example false
       */
      scarf?: boolean;
      /**
       * @description The speed SP (custom only). The upper bound is the per-stat SP cap of the domain
       *     (CLAUDE.md のドメイン規約・ADR-0600 §3。コアは engine.MaxSPPerStat を使う)。
       * @example 32
       */
      sp?: number;
      nature?: components["schemas"]["NatureId"];
      /**
       * @description The speed rank (custom only), -6 to +6 (ADR-0600 §3).
       * @example 1
       */
      rank?: number;
      /**
       * @description The in-battle speed itself (raw only), used as given. Accepted values are the theoretical
       *     minimum and maximum of the formula of ADR-0600 §3 over every base speed, SP, nature, rank and
       *     Choice Scarf (ADR-0602 §3); the service derives those bounds from the formula, so they are
       *     deliberately not repeated here as numbers.
       * @example 301
       */
      value?: number;
    };
    PositionResponse: {
      /**
       * @description The in-battle speed of one's own pokemon (ADR-0602 §3).
       * @example 301
       */
      speed: number;
      /**
       * @description The pokemon the request named, for display. Present only when the request had a pokemonId,
       *     so a raw request without one has no pokemon field (ADR-0602 §4).
       */
      pokemon?: components["schemas"]["SpeedPokemon"];
      /**
       * @description The number of table rows strictly faster than `speed`.
       * @example 12
       */
      faster: number;
      /**
       * @description The number of table rows strictly slower than `speed`.
       * @example 30
       */
      slower: number;
      /**
       * @description The table rows with exactly this speed, sorted as a tier is (pokemonId ascending, then the
       *     preset order of ADR-0601 §2). An empty array means no speed tie.
       */
      tie: components["schemas"]["SpeedTableEntry"][];
    };
    Error: {
      code: components["schemas"]["ErrorCode"];
      message: string;
    };
    /** @enum {string} */
    ErrorCode:
      "invalid_request" | "unknown_pokemon" | "request_too_large" | "master_unavailable" | "internal_error";
  };
  responses: never;
  parameters: {
    DeviceId: string;
    SessionId: string;
  };
  requestBodies: never;
  headers: never;
  pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
  health: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Ready */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Health"];
        };
      };
    };
  };
  publicHealth: {
    parameters: {
      query?: never;
      header?: never;
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description Ready */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Health"];
        };
      };
    };
  };
  listPokemon: {
    parameters: {
      query?: never;
      header: {
        "X-Device-Id": components["parameters"]["DeviceId"];
        "X-Session-Id": components["parameters"]["SessionId"];
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The available pokemon with their base speed */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PokemonListResponse"];
        };
      };
      /** @description X-Device-Id or X-Session-Id is missing, empty, or invalid (invalid_request) */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description An unexpected internal error (internal_error). The message is a fixed string; no internal detail is returned. */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description The pokemon read model is not configured (master_unavailable) */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  getSpeedTable: {
    parameters: {
      query?: {
        /**
         * @description The rows to include, comma separated (ADR-0601 §4). Omitted means all six presets.
         *     The order given does not affect the result. An unknown ID, a duplicate, or an empty value
         *     (`presets=`) is 400 invalid_request.
         * @example [
         *       "max-scarf"
         *     ]
         */
        presets?: components["schemas"]["PresetId"][];
      };
      header: {
        "X-Device-Id": components["parameters"]["DeviceId"];
        "X-Session-Id": components["parameters"]["SessionId"];
      };
      path?: never;
      cookie?: never;
    };
    requestBody?: never;
    responses: {
      /** @description The speed table */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["TableResponse"];
        };
      };
      /** @description X-Device-Id or X-Session-Id is missing, empty, or invalid, or presets is unknown, duplicated, or empty (invalid_request) */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description An unexpected internal error (internal_error). The message is a fixed string; no internal detail is returned. */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description The pokemon read model is not configured (master_unavailable) */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
  getSpeedPosition: {
    parameters: {
      query?: never;
      header: {
        "X-Device-Id": components["parameters"]["DeviceId"];
        "X-Session-Id": components["parameters"]["SessionId"];
      };
      path?: never;
      cookie?: never;
    };
    requestBody: {
      content: {
        "application/json": components["schemas"]["PositionRequest"];
      };
    };
    responses: {
      /** @description The speed of one's own pokemon and its position in the table */
      200: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["PositionResponse"];
        };
      };
      /**
       * @description X-Device-Id or X-Session-Id is missing, empty, or invalid, or the body is not one JSON object,
       *     or the fields do not match the given mode, or a value is out of range (invalid_request)
       */
      400: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description Request body exceeds the 4 KiB limit (request_too_large) */
      413: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description pokemonId is not in the read model (unknown_pokemon) */
      422: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description An unexpected internal error (internal_error). The message is a fixed string; no internal detail is returned. */
      500: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
      /** @description The pokemon read model is not configured (master_unavailable) */
      503: {
        headers: {
          [name: string]: unknown;
        };
        content: {
          "application/json": components["schemas"]["Error"];
        };
      };
    };
  };
}
