apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: pokecalc-balance
  namespace: argocd
spec:
  project: default
  source:
    repoURL: REPLACE_WITH_GIT_REPOSITORY_URL
    targetRevision: main
    path: services/balance/deploy/k8s/overlays/local
  destination:
    server: https://kubernetes.default.svc
    namespace: pokecalc
