apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: pokecalc
resources:
  - ../../base
images:
  - name: pokecalc/balance
    newName: localhost:5000/pokecalc/balance
    digest: sha256:8adc02744ca2bf418852acc616b1e4c2bafcfe1728902f9bd5875f09216fd112
